mongodb-js/mongosh

packages/cli-repl/src/run.ts

Fix for an issue I only noticed moments after merging: We should
always try to look for the build info JSON file, because that
is not just present in compiled builds, but also in npm packages.

fix(cli-repl): use try-require instead of if-else for buildInfo

---

packages/connectivity-tests/test/atlas.sh

Already gave it a go in Evergreen in a patch: https://spruce.mongodb.com/task/mongosh_linux_test_connectivity_patch_db830b31f597682411d793462c898a6ba3c441fa_60f137e1850e614dffa57f95_21_07_16_07_40_31/logs?execution=0

chore(test): add serverless connectivity tests MONGOSH-903

---

packages/cli-repl/src/build-info.ts
packages/cli-repl/src/index.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts

This just occurred to me -- we should probably just include the
full build info in the log file, because it doesn’t hurt to include
it and it’s in line with the things that are already in the initial
event.

feat(cli-repl): add build info to log file

---

packages/cli-repl/test/e2e.spec.ts
packages/shell-api/src/bulk.spec.ts
packages/shell-api/src/bulk.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/decorators.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/result.ts

And also rename the `tojson` method of the `Bulk` class, which had
only been cased that way for compatibility with the legacy shell’s
`tojson()`/`tojsononeline()` methods, which are not present by
default in mongosh.

fix(shell-api): add toJSON for CommandResult MONGOSH-905

---

.evergreen/evergreen.yml.in
.evergreen/setup-env.sh

This should address CI build failures we are seeing right now.

fix(ci): always set npm registry to main registry

---

scripts/gather-licenses.ts

Porting a change from https://github.com/mongodb-js/compass/pull/2362 to mongosh as the scripts are the same. This changes makes package.json lookup a bit stricter.

fix: Check that package.json that we found contains at least the minimal amount of required keys

---

packages/async-rewriter2/src/async-writer-babel.spec.ts
packages/async-rewriter2/src/stages/wrap-as-iife.ts

MONGOSH-916
Handle variable declarations properly for completion records.
Instead of ignoring the assignment expressions we sometimes turn
them into when they show up as completion records, we assign
these assignment expressions to another dummy variable so that
we faithfully replace variable declarations with other variable
declarations and don’t affect completion record computation.
This doesn’t fully fix the referenced issue, but for that a babel
change is necessary. This commit does everything we can do on our side.

fix(async-rewriter2): handle var decls properly for completion records

---

packages/browser-repl/src/components/shell.tsx
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts
packages/cli-repl/src/smoke-tests.ts
packages/history/src/history.spec.ts
packages/history/src/history.ts
packages/history/src/index.ts
packages/history/src/redact-credentials.spec.ts
packages/history/src/redact-credentials.ts
packages/shell-api/src/field-level-encryption.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/replica-set.ts
packages/shell-api/src/shard.ts
packages/shell-evaluator/src/shell-evaluator.ts

- Rename `redactCredentials` to `redactURICredentials` to indicate
that this does not redact credentials in general, but rather
specifically the credentials of connection strings (and it expects
a connection string as an input)
- Remove the optional second parameter of `changeHistory` and require
all call sites to be explicit about which behavior they want
- Do not export `removeCommand` because it is a footgun when used
on its own as it is a no-op when called with default arguments.
Rather, re-export the function exposed by `mongodb-redact` directly
and name it appropriately. This fixes usage of it in the
shell-evaluator package.

fix: clean up history pkg interfaces and use them properly MONGOSH-921

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/ConsoleLogSupport.kt

eea5cd667d9b40 broke the waterfall tests, because BSON uses
console.warn() when applied to the java shell as no secure random
number generator is available, and the change upgraded the
resulting error from a silent unhandled promise rejection to a full
exception.
Solve this by adding warn and info to the java-shell console
for parity with the shell-api code.

fix(java-shell): allow console.warn and console.info

---

.evergreen.yml
.evergreen/evergreen.yml.in
config/repo-config.yml
package-lock.json
package.json
packages/build/src/barque.ts
packages/build/src/config/build-variant.spec.ts
packages/build/src/config/build-variant.ts
packages/build/src/packaging/download-mongocryptd.ts
packages/build/src/packaging/package/create-package.ts
packages/build/src/packaging/package/get-package-file.ts
packages/build/src/run-publish.spec.ts
scripts/docker/amazonlinux1-rpm.Dockerfile
scripts/docker/build.sh

This mirrors what we do for SUSE support.

feat(ci): add x64 Amazon Linux v1 builds MONGOSH-924

---

packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts

This is a bit looser than newer versions of the legacy shell, which
actually reject a single boolean argument, but this way we cover
the behavior across multiple legacy shell versions.

fix(shell-api): align coll.validate() args with legacy shell MONGOSH-925

---

packages/cli-repl/src/build-info.ts
packages/cli-repl/test/e2e.spec.ts

This is not strictly a piece of *build* information, but in cases
where we ask for the `--build-info` output, we most likely also
want to know the Node.js version (in particular, if this is in
“packaged” mode, i.e. homebrew or npm, then the exact Node.js version
used can vary).

feat(cli-repl): add Node.js version to build info

---

packages/browser-repl/package.json
packages/browser-repl/src/components/types/error-output.tsx
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/e2e.spec.ts
packages/errors/src/index.spec.ts
packages/errors/src/index.ts

- Remove the additional text from the error message itself and instead
move that responsibility to the output formatter
- This makes sense, because this is not actually part of the error
condition, and it allows different display methods to adjust
the error output (e.g. include a log file if present, make the
link clickable, refer to another JIRA project if appropriate, etc.)
- Add the path to the log file that the reporter would ideally include
in the CLI package.

feat: make bug reporting information more actionable MONGOSH-459

---

packages/cli-repl/test/e2e-auth.spec.ts

… and restructure the test so there is no further try/catch nesting.

chore(cli-repl): add more valid kerberos auth failure messages

---

packages/cli-repl/test/e2e-bson.spec.ts
packages/java-shell/src/test/resources/collection/insertOne.js
packages/java-shell/src/test/resources/literal/Timestamp.js
packages/service-provider-core/src/printable-bson.spec.ts
packages/service-provider-core/src/printable-bson.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shell-bson.spec.ts
packages/shell-api/src/shell-bson.ts

- Accept a `Timestamp({ t: <number>, i: <number> })` signature
- Reverse the order of arguments when two arguments are passed,
i.e. `Timestamp(t, i)` instead of `Timestamp(i, t)`, to match
the legacy shell
- Print Timestamps using the `Timestamp({ t, i })` format
This should land together with the corresponding BSON package PR,
https://github.com/mongodb/js-bson/pull/449.

feat: reverse and extend Timestamp constructor arguments MONGOSH-930

---

packages/shell-api/src/bulk.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/plan-cache.spec.ts
packages/shell-api/src/replica-set.spec.ts
packages/shell-api/src/shard.spec.ts

I know it’s silly, but it catches me by surprise every time. :)

chore(shell-api): replace ‘catched’ with ‘caught’

---

package-lock.json

Bump a small number of `@types/` npm packages.
This should address CI failures:
[2021/08/03 10:07:50.109] > tsc -p tsconfig.json
[2021/08/03 10:07:55.031] ../../node_modules/@types/express-serve-static-core/index.d.ts(504,18): error TS2430: Interface 'Response<ResBody, StatusCode>' incorrectly extends interface 'ServerResponse'.
[2021/08/03 10:07:55.031]   Types of property 'req' are incompatible.
[2021/08/03 10:07:55.031]     Type 'Request<ParamsDictionary, any, any, ParsedQs> | undefined' is not assignable to type 'IncomingMessage'.
[2021/08/03 10:07:55.031]       Type 'undefined' is not assignable to type 'IncomingMessage'.
I’m not sure why those failures don’t show up in our waterfall builds,
or what exactly introduced them, but they appear in both PR and
Node.js driver integration …

chore(deps): bump multiple types packages

---

packages/cli-repl/test/e2e-auth.spec.ts

This should address failures like
1) Auth e2e
with options in URI on on the command line
can auth when there is -u and -p:
AssertionError: expected 'switched to db test-1628083918784\nEnterprise test-1628083918784> ' to include 'user: \'anna2\''
at Context.<anonymous> (Z:\data\mci\b788e4fc17091587379cabd712aac21b\src\packages\cli-repl\test\e2e-auth.spec.ts:818:13)

chore(cli-repl): fix flaky e2e auth test

---

packages/browser-repl/config/empty.js
packages/browser-repl/config/plain-url.js
packages/browser-repl/config/webpack.config.base.js
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-core/src/uri-generator.ts
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json

This is a slightly cleaner way of accessing authMechanismProperties.

chore(service-provider-core): parse authMechProps rather than applying regex

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/explainable.spec.ts
packages/shell-api/src/explainable.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/result.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

This is in preparation for MONGOSH-537, where it will make things a bit
easier if we have the liberty to make async calls inside all methods
that perform interactions with the database (i.e. fetching
`_baseOptions` can be an async operation).
Also tighten up some types in the tests along with this.

chore(shell-api): make coll.find() an async function

---

packages/cli-repl/test/e2e.spec.ts
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/BaseMongoIterableHelper.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/Cursor.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/ServiceProviderCursor.kt
packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/aggregation-cursor.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/cursor.spec.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/explainable-cursor.spec.ts
packages/shell-api/src/integration.spec.ts

Because the driver expects `.map()` and `.forEach()` callbacks to work
synchronously, but mongosh users can use pseudo-synchronous async
functions, the driver cannot properly handle the functions we pass
to it.
In order to fix this, if we don’t jump through a lot of extra hoops,
it’s easiest to just implement `.map()` and `.forEach()` ourselves.

fix(shell-api): implement own map/forEach for cursors MONGOSH-936

---

packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/js-multiline-to-singleline.spec.ts
packages/cli-repl/src/js-multiline-to-singleline.ts
packages/cli-repl/src/mongosh-repl.spec.ts

Convert single-line `//` comments into `/* ... */` comments when
transforming multiline user input.

feat(cli-repl): retain comments in multiline input MONGOSH-951

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/result/Cursor.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/Cursor.kt
packages/java-shell/src/test/resources/collection/insertOne.expected.txt

A simple fix but it needs to access private fields `Cursor._cursor` and `Cursor._transform`
It sets `resultsUsedInScript` flag to `false` right before cursor is returned to user.
When `resultsUsedInScript` is `false`, internal Java cursor doesn't convert Java objects to JS

feat(JMongosh): don't convert object from Java to JS and back if results are returned directly to user

---

packages/autocomplete/src/index.spec.ts
packages/autocomplete/src/index.ts

Fix completion for e.g. `use ` so that it works like completion
for just `use` (without the space).

fix(autocomplete): fix completion for command + single space MONGOSH-945

---

packages/cli-repl/src/mongosh-repl.ts

This was missed in bf84ae252762a6d31708 when the signature of the
`eval()` return type changed.

fix(cli-repl): do not print ShellResult for interruption MONGOSH-971

---

packages/shell-api/src/collection.ts

This solves point 1 in the issue. I don't know what to do about 2 and if that's even a good idea. This is what the node driver does if you ask for the count. I had a look at mongo's [count method](https://github.com/mongodb/mongo/blob/3675df9065981e30e289c2aa487b23c22c9702ed/src/mongo/shell/collection.js#L1291-L1318) but I'm not sure how we'd get the same behaviour.

fix: print a deprecation warning when trying to use Collection.count() (MONGOSH-957)

---

packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/run.ts

This is just a small bit of cleanup. The arg parser should not
be printing warnings on its own, without knowing where those end up;
specifying the output stream is the top level program’s responsibility.
This also makes running the arg parser test suite a bit nicer, because
now the test output is not mixed with these warnings.

chore(cli-repl): move arg parser warning printing to run.ts

---

packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/deprecation-warning.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/replica-set.ts

Add these helpers for legacy compatibility and point users to
the replacement methods in the deprecation message.

feat(shell-api): add deprecated setSecondaryOk helpers MONGOSH-910

---

packages/cli-repl/src/run.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/fixtures/simple-console-log.js

MONGOSH-981
In compiled mode, `process.argv[0]` and `process.argv[1]` are the same
(both point to the compiled binary), but that still means that
`process.argv[1]` should be removed in order to run the entry point
normally.

fix(cli-repl): handle MONGOSH_RUN_NODE_SCRIPT for compiled binary properly

---

config/eslintrc.base.js
packages/async-rewriter2/.eslintrc.js
packages/autocomplete/.eslintrc.js
packages/browser-repl/.eslintrc.js
packages/browser-runtime-core/.eslintrc.js
packages/browser-runtime-electron/.eslintrc.js
packages/build/.eslintrc.js
packages/cli-repl/.eslintrc.js
packages/errors/.eslintrc.js
packages/history/.eslintrc.js
packages/i18n/.eslintrc.js
packages/node-runtime-worker-thread/.eslintrc.js
packages/service-provider-core/.eslintrc.js
packages/service-provider-server/.eslintrc.js
packages/shell-api/.eslintrc.js
packages/shell-evaluator/.eslintrc.js
packages/snippet-manager/.eslintrc.js
packages/types/.eslintrc.js

chore: fix eslint integration with VS Code ESLint extension

Fix eslint in vscode

---

packages/shell-api/src/database.ts
packages/shell-api/src/helpers.spec.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

MONGOSH-982
Also cache the `db.hello()` result instead of running it for
every single `sh` method call.
Testing the extended `sh.status(verbose, db)` signature is left
for MONGOSH-742.

fix(shell-api): warn instead of throw for sh methods on non-mongos

---

packages/async-rewriter2/src/async-writer-babel.spec.ts
packages/async-rewriter2/src/async-writer-babel.ts
packages/async-rewriter2/src/stages/wrap-as-iife.ts
packages/cli-repl/src/js-multiline-to-singleline.ts
packages/cli-repl/test/e2e.spec.ts

Tell babel that we are targeting script mode, not ES module mode.
(Note that the babel docs indicate that `script` should be the
default – it seems that that is not entirely accurate.)
This fixes the linked bug because unlike ES modules, script mode
does not automatically also enable strict mode.
This also fixes a minor bug in the wrap-as-iife babel plugin,
where if the input was a single string literal, escaped characters
would have remained escaped (e.g., entering `'\x41'` in mongosh
would have returned `\x41`, not 'A'), by keeping the existing
information about the raw source instead of generating an
entirely new string literal in that case.

fix: do babel transformations for script, not module MONGOSH-986

---

package-lock.json
package.json

Mostly just bumping this to be extra sure that the fix in https://github.com/mongodb-js/download-url/pull/245 didn’t break anything :)

chore(deps): bump mongodb-download-url to 1.1.2

---

config/eslintrc.base.js
packages/async-rewriter2/.eslintrc.js
packages/autocomplete/.eslintrc.js
packages/browser-repl/.eslintrc.js
packages/browser-runtime-core/.eslintrc.js
packages/browser-runtime-electron/.eslintrc.js
packages/build/.eslintrc.js
packages/cli-repl/.eslintrc.js
packages/errors/.eslintrc.js
packages/history/.eslintrc.js
packages/i18n/.eslintrc.js
packages/node-runtime-worker-thread/.eslintrc.js
packages/service-provider-core/.eslintrc.js
packages/service-provider-server/.eslintrc.js
packages/shell-api/.eslintrc.js
packages/shell-evaluator/.eslintrc.js
packages/snippet-manager/.eslintrc.js
packages/types/.eslintrc.js

This reverts commit c4372550cc02878738319f7767e9ff896491fed4.
This fixes Windows CI:
[2021/09/13 10:44:59.161] > npm run lint
[2021/09/13 10:44:59.161] > @mongosh/errors@0.0.0-dev.0 lint C:\data\mci\abacfdf08bad6c5c588fc6f7d2007707\src\packages\errors
[2021/09/13 10:44:59.161] > eslint --report-unused-disable-directives "./{src,test}/**/*.{js,ts,tsx}"
[2021/09/13 10:44:59.161] C:\data\mci\abacfdf08bad6c5c588fc6f7d2007707\src\packages\errors\src\common-errors.ts
[2021/09/13 10:44:59.161]   0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
[2021/09/13 10:44:59.161] The file does not match your project config: C:\data\mci\abacfdf08bad6c5c588fc6f7d2007707\src\packages\errors\src\common-errors.ts.
[2021/09/13 10:44:59.161] The file must be included …

Revert "Fix eslint in vscode (#1099)"

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/replica-set.spec.ts

Modify the `.watch()` signature so that it “officially” allows
omitting the first argument.
As a drive-by fix, stop applying `.tryNext()` for cases in which
the change stream cursor starts from a specific point in time.
(Unfortunately, `.hasNext()` is not an option here, unlike
discussed with the Node.js driver team, because it is blocking
like `.next()` and unlike `.tryNext()`.)

fix(shell-api): .watch() signature and behavior fixes MONGOSH-976

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/integration.spec.ts

As suggested by the Node.js driver team, use `.hasNext()` to
force sending the aggregation command to the server early.

fix(shell-api): run $out/$merge aggregations immediately MONGOSH-972

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/test/e2e.spec.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/types/src/index.ts

TS requested that we provide a driver version for connection
attempts from the embedded shell in Compass. This moves the
driver version reporting to the service-provider-server package,
which is a more natural place for it anyway.

chore(logging): provide driver version for every connection MONGOSH-1000

---

packages/editor/src/editor.ts

A user can specify something in the editor that contains multiple parts (eg EDITOR='nano -cA' or EDITOR='code --wait'). We could spawn the editor using a shell flag to support the following cases:
EDITOR=code
EDITOR=C:\Program Files\Editor\editor.exe
EDITOR="code --wait"
Since we cannot easily distinguish between the semantics of the spaces between cases 2 and 3, we will need the OS shell to do that for us.

feat(editor): handle editor specifies as name with multiple parts MONGOSH-996

---

packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json

Only `interruptor` is a real dependency of this package that's required for the package to work when installed externally. This PR removes all the other ones so that when Compass installs this as a dependency, we don't waste time installing the other ones

chore(node-runtime-worker-thread): Clean-up worker runtime prod dependencies so they are not installed with the library

---

packages/cli-repl/test/e2e-direct.spec.ts

This has been one of the most frequent failures in recent CI runs.
Hopefully this is something that can be mitigated by increasing
the timeout for the replset being fully initiated.

chore(cli-repl): increase rs.initiate test timeout

---

.evergreen.yml
.evergreen/evergreen.yml.in
packages/cli-repl/src/cli-repl.spec.ts
packages/editor/src/editor.spec.ts

Bump the Node.js versions to the latest ones in the respective
release line and regenerate the evergreen config (which also
includes adding CI jobs for packages that were only recently
added, i.e. editor, logging, js-multiline-to-singleline).

chore(build): bump Node.js and regen evergreen cfg MONGOSH-1007

---

packages/cli-repl/test/e2e-analytics.spec.ts

This is just like 3e4fd873efd3dca38a5746a41835313bb5ffb746, I just
missed that there is a second test that also runs `rs.initiate()`
and sometimes times out in CI.

chore(cli-repl): also bump analytics node test rs.initiate timeout

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/shell-bson.ts
packages/shell-api/src/shell-instance-state.ts

This makes it so that all database `runCommand` calls go through
the same code path, making it easier to apply modifications that
we think should apply to all such calls.
Instead of using `any` for the shell bson wrapper types, add
proper TypeScript definitions.
Automatically adjust arguments for some server commands that
expect BSON Double values as input where mongosh would currently
send an Int32 by default (unlike the legacy shell).

fix(shell-api): adjust argument types for some commands MONGOSH-967

---

packages/editor/src/editor.ts
packages/js-multiline-to-singleline/src/index.spec.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/types/src/index.ts

Bring `js-multiline-to-singleline` and `logging` to full line
coverage, and fix a few minor issues in the process. These
packages were recently added and not yet counted for coverage/run
in CI, see https://github.com/mongodb-js/mongosh/pull/1121.

chore: increase coverage for newly added packages

---

packages/cli-repl/test/e2e-fle.spec.ts

This is fairly flaky in CI, and while it’s not obvious to me why,
it appears that the `.find()` call is not returning documents
the way we would expect them to. Trying to repeat this should
at least give us some debugging information.

chore(cli-repl): relax FLE e2e test

---

.github/workflows/cron-tasks.yml

This prevents us from forgetting to add new packages to the
config when they are added to the monorepo, as I recently did :)

chore(ci): automatically update evergreen config MONGOSH-1008

---

packages/shell-api/src/integration.spec.ts
packages/shell-api/src/shell-instance-state.ts

feat(shell-api): make db/coll autocompletions case-insensitive 

---

packages/cli-repl/test/e2e-editor.spec.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/repl-helpers.ts
packages/editor/package.json
packages/editor/src/editor.spec.ts
packages/editor/src/editor.ts
packages/shell-evaluator/src/shell-evaluator.spec.ts
packages/shell-evaluator/src/shell-evaluator.ts

Check spawing processes by replacing an external editor with nodejs script.

test(editor): use a node script as an external editor MONGOSH-992

---

packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json

When I used mongosh with aws roles I got the below error in the screenshot attached.
I saw that this package was added it this earlier pr
https://github.com/mongodb-js/mongosh/pull/718/files
and removed in this one
https://github.com/mongodb-js/mongosh/pull/959/files

fix(cli-repl): re-add aws4 as dependency to cli-repl to enable AWS auth

---

packages/build/package-lock.json
packages/editor/package-lock.json
packages/java-shell/package-lock.json

Basit noticed that our github CI is failing due to the package-lock
files being out of date. This should address that issue.

chore: commit results of a clean `npm run bootstrap`

---

packages/service-provider-core/src/uri-generator.ts

MONGOSH-1047
Not necessary anymore since we bumped the Node.js driver to 4.1.2.

chore(service-provider-core): remove tlsCertificateKeyFile option copying

---

packages/async-rewriter2/package.json
packages/async-rewriter2/src/async-writer-babel.spec.ts
packages/async-rewriter2/src/stages/transform-maybe-await.ts

As noted in the ticket, this only fixes the problem partially,
because using `import()` from a function that is then called
from another line in the REPL can crash the process
(depending on garbage collection) due to a Node.js ESM bug.

fix(async-rewriter): properly process dynamic import() MONGOSH-1062

---

packages/cli-repl/test/e2e-bson.spec.ts
packages/shell-api/src/shell-bson.spec.ts
packages/shell-api/src/shell-bson.ts

Add `.toBSON` overrides so that sending `MinKey` or `MaxKey`
over the wire results in the same document that `MinKey()` or
`MaxKey()` would have generated, for compatibility with the
legacy shell.

fix(shell-api): add toBSON overrides to MinKey/MaxKey ctors MONGOSH-1024

---

packages/cli-repl/test/e2e-tls.spec.ts
packages/shell-api/src/database.ts

Authenticating without username/password can be valid for
some authentication mechanisms, so skip that if a mechanism
was passed in explicitly.

fix(shell-api): relax db.auth() input validation MONGOSH-1051

---

packages/cli-repl/src/cli-repl.ts

Log the values of:
- `$TERM`, because knowing the terminal type can be useful for
debugging issues regarding our usage of the Node.js readline module
- `$EDITOR`, because it is used by the `edit` feature
- `$NODE_OPTIONS`, because it influences the way that mongosh runs
(and in particular can contain preload modules)

chore(cli-repl): log env vars useful for troubleshooting MONGOSH-1064

---

packages/browser-repl/src/components/editor.tsx

some reference https://github.com/securingsincity/react-ace/issues/725
See https://jira.mongodb.org/browse/COMPASS-5328 for some future follow-up work

chore: no need for webpack-resolver, set useWorker: false COMPASS-4528

---

packages/java-shell/settings.gradle

Bintray was sunsetted several months ago and seems they finally pulled the plug completely. Kotlin resources are now in Maven Central.

fix: remove sunsetted bintray repo

---

package-lock.json
package.json
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/node-runtime-worker-thread/src/worker-runtime.ts
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/shell-api/src/change-stream-cursor.ts
packages/snippet-manager/package-lock.json
packages/snippet-manager/package.json

Bump the Node.js driver to 4.2.1 and its bson package to 4.6.0.

chore(deps): bump driver to 4.2.1 COMPASS-5340

---

packaging/README

Be more specific about the contents of the packages we generate,
and clarify that `mongosh.1.gz` is a manual page file.

chore: reword package artifact README

---

packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/e2e.spec.ts

Warn the user when the driver appears to connect successfully
but a “ping” command still fails to run.

chore(cli-repl): warn about missing connectivity MONGOSH-1067

---

packages/async-rewriter2/src/async-writer-babel.ts

We should tell babel not to try to load the browerlist config from
disk, especially since we are not interested in it anyway.
A proper regression test seems hard to write, since it would
essentially consist of making sure that mongosh does not access
files from its current working directory when it starts up.

fix(async-rewriter): do not load browserlist config MONGOSH-1085

---

scripts/prep-fle-addon.sh

This seems to be one of the reasons that CI is currently broken.

chore: remove mongocrypt windows packaging bug workaround

---

packages/build/src/run-draft.spec.ts
packages/build/src/run-draft.ts

This reverts commit 01997aba3b8e001c8668656731e12d491972756a.

Revert "chore(build): skip attempted PGP signing for now (#1174)"

---

packages/cli-repl/src/arg-mapper.spec.ts
packages/cli-repl/src/arg-mapper.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/test/e2e.spec.ts

Allow users to overwrite appName in a connection string. Keep the application name via driverInfo metadata.

fix(cli-repl): persist custom appname MONGOSH-1015

---

packages/shell-api/src/helpers.ts
packages/shell-api/src/shell-bson.spec.ts
packages/shell-api/src/shell-bson.ts

MONGOSH-1073
Extend our type validation helper to allow specifying individual
BSON types, and use that to loosen the restrictions on the legacy
`Number*()` constructors.

fix(shell-api): align `Number*` type validation with legacy shell

---

packages/logging/package-lock.json
packages/logging/package.json
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/node-runtime-worker-thread/webpack.config.js
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/types/package-lock.json
packages/types/package.json

In particular, include whether os-dns-native made lookups
using the native OS DNS APIs or not.

feat(service-provider-server): log more detailed information about DNS lookups

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

Starting with 5.0.6, the server allows additional `db.stats()`
options. We extend the shell to also accept an options object.

feat(shell-api): allow db.stats(options) MONGOSH-1108

---

packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/clr.ts
packages/cli-repl/src/config-directory.ts
packages/cli-repl/src/constants.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/test/e2e.spec.ts
packages/i18n/src/locales/en_US.ts
packages/logging/src/analytics-helpers.spec.ts
packages/logging/src/analytics-helpers.ts
packages/logging/src/index.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
packages/node-runtime-worker-thread/src/child-process-proxy.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/shell-api.spec.ts
packages/shell-api/src/shell-api.ts
packages/types/src/index.ts

Please review on a commit-by-commit basis :)
This adds support for a global YAML config file.
mongosh loads one global config file, attempting:
- `.\mongosh.cfg` on Windows, relative to the mongosh.exe binary
- `/usr/local/etc/mongosh.conf`, `/opt/homebrew/etc/mongosh.conf`
and `/etc/mongosh.conf` on Darwin
- `/etc/mongosh.conf` on all other platforms
On Windows, this file is only loaded if mongosh is distributed
as a single-executable binary, since otherwise there is no reasonable
starting point for searching the global config file.
The global config file uses YAML, with options namespaced under
the `mongosh` key, instead of only supporting plain EJSON, since that
matches the mongod global configuration file.
Instead of manually keeping track of whether telemetry is
enabled/disabled …

feat: expand config support MONGOSH-{1063,1055,959}

---

.evergreen.yml
.evergreen/evergreen.yml.in
scripts/docker/README.md
scripts/docker/build.sh
scripts/docker/rocky8-rpm.Dockerfile

The CentOS 8 docker tests are currently failing in CI:
Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Using Rocky Linux as the successor to CentOS instead is probably
the easiest sensible choice here.

chore(ci): use Rocky Linux 8 instead of CentOS 8 for docker tests

---

packages/browser-repl/package-lock.json
packages/browser-repl/package.json
packages/browser-repl/src/components/utils/syntax-highlight.less
packages/browser-repl/src/components/utils/syntax-highlight.spec.tsx
packages/browser-repl/src/components/utils/syntax-highlight.tsx
packages/shell-api/src/shell-instance-state.ts

This is part of [COMPASS-5422](https://jira.mongodb.org/browse/COMPASS-5422) - which COMPASS-5512 depends on.
This doesn't solve the full issue of how to better use the `browser-repl` with better dependency management in Compass (and potentially other places), which I'm still investigating. This won't close that ticket yet.
This pr unblocks the Compass fix. It bumps the leafygreen versions to a version which uses the newer emotion version which Compass needs to align on.
The `Syntax` component in Leafygreen has been deprecated, so this replaces the functionality with a `Code` component. https://www.mongodb.design/component/code/example/
Before:
After:
(^ They should look the same)

chore(browser-repl): Bump leafygreen versions, replace Syntax with Code COMPASS-5422

---

package-lock.json
package.json
packages/browser-repl/package-lock.json
packages/java-shell/package-lock.json
packages/logging/package-lock.json
packages/logging/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/types/package-lock.json
packages/types/package.json

Driver release notes: https://github.com/mongodb/node-mongodb-native/releases/tag/v4.4.0
~(lerna bootstrap never succeeded for me locally failing with various TS errors, but I'm guessing I don't know a proper way to run it in this monorepo or something is messed up with my setup, so I'm opening a PR anyway to see if it will pass in CI)~ I think I finally figured it out, let's see

chore: Bump driver to latest

---

.evergreen/package-and-upload-artifact.sh

After c9151ce70b79e86, which undid one layer of string nesting,
I forgot to take care of the corresponding escapes which should
also have been removed.

fix(ci): fix packaging script for Windows MSI

---

packages/cli-repl/src/cli-repl.spec.ts

`.count()` is deprecated and should not be used, and makes this
test currently fail in `apiStrict` mode because it uses the `count`
command since the recent driver version bump to 4.4.0.

chore(cli-repl): avoid deprecated count in --shell test

---

.evergreen.yml
.evergreen/evergreen.yml.in

The mongosh 1.2.0 failed because the publishing task failed after
three hours (!). This is a good reminder to poke the build team
about BUILD-13863 again, but for now, it seems like we have to
set the timeout to something that seems really unrealistically high.

chore(ci): bump publish task timeout to 1d

---

testing/integration-testing-hooks.ts

No CI because this was one of several patches I ran to avoid going back and forth with CI here: https://spruce.mongodb.com/version/621792013e8e864a7a499e7a/tasks

fix(ci): pin mtools version to python3.6-compatible one

---

packages/node-runtime-worker-thread/.depcheckrc
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/node-runtime-worker-thread/webpack.config.js

COMPASS-4105
In order to be usable in Compass, system-ca and its addon dependencies
need to be externalized in the webpack configuration.
Theoretically, it might be enough to only externalize the addons;
however, since system-ca prefers to use worker threads for loading
certificates asynchronously on macOS and Windows, and we need to
externalize *something*, it makes sense to do it on the system-ca
level.

fix(node-runtime-worker-thread): externalize system-ca and deps

---

packages/autocomplete/package-lock.json
packages/autocomplete/package.json

bump ace-autocomplete version using npm@6

chore: bump ace autocompleter to 0.11.0 COMPASS-5556

---

packages/cli-repl/README.md
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/test/e2e.spec.ts
packages/java-shell/package-lock.json
packages/logging/src/analytics-helpers.spec.ts
packages/logging/src/analytics-helpers.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/types/src/index.spec.ts
packages/types/src/index.ts

In `mongosh`, we don't have MongoDB user identifiers. We randomly generate an ID the first time the product is run and then we use that as a user id. The `userId` should not be a random UUID, it should store only AUID. The randomly generated UUID should be sent as `anonymousId`.
To not break statistics for existing users:
- We should leave all current users with the tracking they have.
- For new users, we should use the `anonymousID` field and fill it with a random UUID.
That being said:
- If `userId` exists we send it to segment. We also copy userId to `anonymousId` and send it to Segment as well.
- If `userId` does not exist we do not create a new one, we only generate a random UUID and send it to Segment as `anonymousId`.

fix: use user id and anonymous id as segment identity MONGOSH-1143

---

packages/shell-api/src/shard.spec.ts

Relax the test expectations to account for upcoming changes in 6.0.

fix(shell-api): relax sharding test expectations MONGOSH-1152

---

packages/cli-repl/src/arg-mapper.spec.ts
packages/cli-repl/src/arg-mapper.ts

MONGOSH-856
Pass down `sspiHostnameCanonicalization` to the driver as-is
and let the driver do the validation. We still map `true` and
`false` from strings to booleans and an empty string to `undefined`,
since the driver would otherwise reject those values.

feat(cli-repl): pass through sspiHostnameCanonicalization to driver MONGOSH-856

---

packaging/rpm-template/SPECS/mongodb-mongosh.spec

This makes the RPMs looks like they did before f2ab09af6100,
and resolves a conflict with the server RPMs.
Evergreen: https://spruce.mongodb.com/version/623219c261837d42053fd295/tasks (no automatic builds for PRs right now because of a github outage)

fix(packaging): create RPMs without .build-id entries MONGOSH-1159

---

.evergreen.yml
.evergreen/evergreen.yml.in
packages/cli-repl/test/e2e-auth.spec.ts

In particular, split out Linux unit tests so that we can
make merging dependent on them, and add macos 11 x64
test tasks (MONGOSH-1107).

chore: restructure evergreen build variants

---

packages/java-shell/build.gradle
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellEvaluator.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt

This is needed to improve JDBC driver performance - we'll create MongoShell instances beforehand

feat(JMongosh): allow setting MongoClient after MongoShell was created

---

packages/node-runtime-worker-thread/src/index.ts
packages/node-runtime-worker-thread/src/serializer.spec.ts
packages/node-runtime-worker-thread/src/serializer.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts

`schemaMap` and the soon-to-be-introduced `encryptedFieldConfigMap`
(or similar) typically contain bson values that are not serialized
properly right now.
We add EJSON serialization for transferring them to the worker runtime.

fix(node-runtime-worker-thread): pass through CSFLE schema options COMPASS-5647

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/ReadableServiceProvider.kt
packages/java-shell/src/test/resources/collection/isCapped.expected.txt
packages/java-shell/src/test/resources/collection/isCapped.js
packages/service-provider-core/src/readable.ts
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/integration.spec.ts

Note: It looks like these will not be deprecated with a deprecation warning in 6.0 yet.
I still wanted to share the work that I’d done so far, partially also because it’s
good cleanup for our `ServiceProvider` API.
---
Instead of using a custom ServiceProvider method for getting the
`collection.isCapped()` information, use the shared `listCollections`
interface instead.
This reduces the ServiceProvider API surface and avoids
diverging implementations for the method, in particular
avoids an instance of the eventually-to-be-deprecated `collStats`
command in the java-shell.
Remove `.stats()` from the service provider interface (which
has the nice side effect of reducing its API surface) and
replace corresponding calls by `$collStats` aggregations.

chore: reduce collStats command usage MONGOSH-1157

---

packages/cli-repl/src/cli-repl.ts
packages/editor/src/editor.ts

Call `.toHexString()` when we convert an `ObjectId` to a string
for internal usage.
This ensures that changes to `ObjectId.prototyp.toString()` from
user code will not affect mongosh internals.
Unfortunately, it is not easily possible to add a regression test
for the original ticket here, since it depends specifically on
the way in which homebrew (or npx) install mongosh, where dependencies
of the different packages in the monorepo are deduplicated during
installation (which makes `service-provider-server` and
`service-provider-core` share a `bson` dependency rather than
using separate ones).

fix: explicitly call ObjectId.toHexString() in internals MONGOSH-1097

---

packages/async-rewriter2/.gitignore
packages/async-rewriter2/bin/make-runtime-support.js
packages/async-rewriter2/package.json
packages/async-rewriter2/src/async-writer-babel.ts
packages/async-rewriter2/src/runtime-support.nocov.js

This improves startup performance significantly by not needing a
async-rewriting pass over the runtime support code at runtime.
This implementation requires first creating a dummy file containing
an empty runtime support code result before compiling typescript,
and only instantiating the contents of that file afterwards.
(Better reviewed with whitespace changes hidden 🙂 )

feat(async-rewriter): cache runtime support code at compile time MONGOSH-1168

---

packages/shell-api/src/collection.ts

MONGOSH-1182
This PR marks the collection `reIndex` function as deprecated.
Should we print a deprecation warning? 
```ts
await this._instanceState.printDeprecationWarning(
'Collection.reIndex() is deprecated and not recommended for use.'
);
```

feat(shell-api): Mark `collection.reIndex()` deprecated MONGOSH-1182

---

packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts
packages/shell-api/src/mongo.ts

MONGOSH-1191
This was missed when porting `KeyVault` over from the legacy shell.
Instead of erroring out if the index could not be created (as the
legacy shell would have done), print a warning instead.
Other fixes here:
- Fix the namespace parsing in the `KeyVault` constructor
- Ensure that the `KeyVault` object is only instantiated
once per `Mongo` object.
- Use `$addToSet` instead of `$push` for adding keyAltName entries to avoid duplicates inside the array
- Fix empty array removal in `removeKeyAlternateName()`
- Account for the broken empty array removal before creating the `keyAltNames` index

fix(shell-api): make .getKeyVault() create index over keyAltNames

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts

MONGOSH-1195
Currently the collection `.save()` command errors with a `MongoshInvalidInputError` error. As this command has been removed in the driver as of 4.0 I'm thinking we should be able to drop it entirely. If folks feel it's better to keep a message being displayed that's cool also.
Currently we are printing a message with the error that states the command is deprecated. If we don't remove I think we should update the message to be explicit that the command has been removed.

fix(shell-api): Remove removed collection save command instead of deprecating MONGOSH-1195

---

.evergreen.yml
.evergreen/evergreen.yml.in
packages/arg-parser/src/arg-mapper.ts
packages/build/src/download-mongodb.ts
packages/build/src/packaging/download-csfle-library.ts
packages/build/src/packaging/run-package.ts
packages/cli-repl/package-lock.json
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/csfle-library-paths.spec.ts
packages/cli-repl/src/csfle-library-paths.ts
packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json

This should be sufficient for bringing the CSFLE shared library work
into a mergeable state.
The ts-expect-error comments can likely be removed pretty soon as well,
with the next driver bump.

chore: bump mongodb-client-encryption, add ts-expect-error MONGOSH-1196

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts

Passing through options is a) documented and b) something we also do for other methods.

fix(shell-api): pass through collection.drop() options MONGOSH-1199

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellConverter.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/result/MongoShellResult.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
packages/java-shell/src/test/resources/collection/bulkWrite.expected.txt
packages/java-shell/src/test/resources/collection/insertOne.expected.txt
packages/java-shell/src/test/resources/collection/insertOne.js
packages/java-shell/src/test/resources/collection/insertOneWriteConcern.expected.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.1.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.2.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.txt
packages/java-shell/src/test/resources/db/showCollections.expected.txt

[DBE-15167](https://youtrack.jetbrains.com/issue/DBE-15167/MongoDB-%60returnedId%60-is-always-UNKNOWN) MongoDB `returnedId` is always UNKNOWN

feat(java-shell): return inserted ids from insert operations

---

packages/browser-repl/package-lock.json
packages/browser-repl/package.json
packages/browser-repl/src/components/shell-output-line.spec.tsx
packages/browser-repl/src/components/types/show-dbs-output.spec.tsx
packages/browser-repl/src/components/types/show-dbs-output.tsx
packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/format-output.spec.ts
packages/cli-repl/src/format-output.ts

This treats 1KB as 1024 bytes, has no space between the number and unit and uses KB, MB, etc all just like legacy shell. BUT I don't know about all the nuances of 0.1GB vs 100MB, for example. How much do we care about matching that level of detail? Also unclear about things like rounding up and down.

numeral rather than pretty bytes MONGOSH-1124

---

packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/shell-api/src/integration.spec.ts

MONGOSH-1172
Adds a few tests for clustered indexes on collections. Checking CI before opening.

 chore(service-provider-server): add clustered collection index tests MONGOSH-1172

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts

If a collection was not listed in the Mongo() `encryptedFieldsMap` and no explicit `encryptedFields` option was passed to `collection.drop(options)`, we always look up the `encryptedFields` from `listCollections` and pass that instead.

feat: drop collection using encrypted fields from collection list MONGOSH-1208

---

packages/shell-api/src/collection.ts

Add `try/catch` when `listCollections`, because a user might have the `dropCollections` privilege but not `listCollections`.

feat: catch errors when listCollections MONGOSH-1208

---

packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/shell-api/src/integration.spec.ts

Since we've updated the driver we can now remove this `any` usage in the creation of clustered collections in tests. https://jira.mongodb.org/browse/NODE-4189

chore(shell-api): Remove `any` usage in create collection test 

---

config/repo-config.yml
packages/build/src/barque.spec.ts
packages/build/src/barque.ts

Revert "fix(build): temporarily remove debian11 publishing (#1283)" 

---

packages/cli-repl/src/arg-parser.spec.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/run.ts
packages/cli-repl/test/e2e.spec.ts

Proper testing of the functionality is left to MONGOSH-1222.
This does not add support for `--sslFIPSMode` or spelling variants
of `--tlsFIPSMode` that would be recognized by yargs, in order to
keep the setup code as straightforward as possible.

feat(cli-repl): add support for the --tlsFIPSMode flag MONGOSH-1221

---

.evergreen.yml
.evergreen/evergreen.yml.in

I was assuming that it would not be necessary to include it here,
but it seems like it is in order for lerna to be able to check
whether the current user has publish access to the packages.
(That also seems like a good thing to check in the dry-run step,
since we’ve had issues before with adding new packages to which
the automation bot did not have access yet.)

fix(ci): use auth token in dry-run-publish step

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts

This also adds the aliases suggested in MONGOSH-1239, since
doing so is straightforward and touches the same code.

feat(shell-api): add new key management helpers MONGOSH-1206

---

packages/cli-repl/test/e2e-fle.spec.ts

I removed this in f765c071880e0f when I shouldn’t have, presumably
because the referenced ticket was marked as closed and I didn’t
check whether this is actually working now. The server *does*
provide a shared library for s390x, but only RHEL 8.x, not 7.x.

chore(cli-repl): add back s390x FLE e2e test skip

---

packages/build/src/packaging/download-crypt-library.ts
packages/cli-repl/src/smoke-tests-fle.ts
packages/cli-repl/test/e2e-fle.spec.ts

The crypt shared library is now (since 6.0.0-rc8) also available
on RHEL 7.2 for s390x. Downgrading it should not affect RHEL 8 support
on s390x, and allows us to also run the FLE tests on all platforms.

feat: lower crypt library version to rhel72 on s390x

---

packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts

Default `analytics-node` behavior is to retry 3 times and have no timeout on the request, we want to mitigate the effect of telemetry flushing on the user experience and so this patch sets timeout to 1 second and disables the retries completely
MONGOSH-1253

chore(cli-repl): Add timeout and disable retries for telemetry flushes MONGOSH-1253

---

packages/arg-parser/src/cli-options.ts
packages/cli-repl/src/arg-parser.spec.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts

- Allow `--eval` to be used multiple times on the command line.
- Only print the result of the last `--eval` invocation.
- Remove the special handling for `--eval` without an argument,
since our args parser does not let us distinguish that case
from no `--eval` being passed in the case of options that
can occur multiple times.

feat(cli-repl): allow multiple --eval args MONGOSH-1194

---

packages/cli-repl/test/e2e-fle.spec.ts

Indexed search requires AES-CTR support, which is not available
in the native crypto implementation of macOS 10.14.

chore(cli-repl): skip QE test on macOS 10.14

---

package-lock.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts

I'm still adding some tests, but decided to open this PR already as I wasn't sure if that's the best place to put this logic and super open to feedback on this

fix(cli-repl): Detect containerized environment and disable telemetry MONGOSH-1278

---

packages/shell-api/src/field-level-encryption.ts

In ad9c6bcbb6ebb0, this workaround was added since the interaction
of `createIndex` with `libmongocrypt` was buggy. Since this is
resolved now, we can just re-enable index creation.

fix(shell-api): remove KeyVault initialization workaround MONGOSH-1245

---

package-lock.json
package.json

Opening as draft for now because it should be possible to update the docker images a bit to account for this, but testing that locally requires new .rpm/.deb packages and the easiest way to get those is to open a draft PR and let CI do its thing. :slightly_smiling_face:

chore(deps): bump boxednode to 1.12.0 MONGOSH-1258

---

.evergreen.yml
config/release-package-matrix.js

Amazon Linux 2022 apparently stopped providing OpenSSL 1.1 in its
rpm repositories.

chore(ci): drop Amazon Linux 2022 OpenSSL 1.1 smoke tests

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts

Return a Proxy that merges the single returned `Document` from a cursor
with the cursor itself (or a copy of it) to migrate users to a more
driver-key-management-like API.

chore(shell-api): make single-doc KeyVault methods return Documents MONGOSH-1266

---

.evergreen.yml
.evergreen/compile-artifact.sh
config/release-package-matrix.js
packages/cli-repl/src/smoke-tests.ts
scripts/docker/compile-and-install-openssl3.sh
scripts/docker/rocky8-epel-rpm.Dockerfile
scripts/docker/rocky9-fips-rpm.Dockerfile
scripts/docker/rocky9-rpm.Dockerfile
scripts/docker/ubuntu22.04-fips-deb.Dockerfile

- Accept a runtime error when trying to use a non-FIPS
crypto algorithm in FIPS mode, rather than just a startup
error, since OpenSSL 3 behaves differently from OpenSSL 1.1
in this regard
- Add a positive smoke test for OpenSSL 3 FIPS confirming
that a simple crypto operation like SHA256 works
- Add docker tests that compile, build and install a version
of OpenSSL that claims to be FIPS-compliant to mongosh.
- Remove “Skip OpenSSL 3 tests” flags for other OpenSSL-3-based
docker containers.

chore: run OpenSSL 3 FIPS smoke tests in Docker tests MONGOSH-1258

---

packages/arg-parser/.depcheckrc
packages/arg-parser/package.json
packages/logging/.depcheckrc
packages/logging/package.json
packages/types/.depcheckrc
packages/types/package.json

Add the driver package as an explicit `devDependencies` entry
for packages where a dependency uses it as a peer dependency.
This is not strictly necessary with modern npm versions,
and hopefully goes away once we move to a more Compass-style
monorepo where dependencies are hoisted, but for now, this is
convenient because it makes it quite a bit easier to update
the driver, and hopefully also paves the way for fixing the
(currently broken) driver integration tests.
(Previously, updating the driver often involved adding the
driver as a dependency to these packages, running bootstrap
to update the package-lock.json, then removing it from the
package.json again, and then running bootstrap again, since
otherwise driver types would start mismatching the driver types
from other packages.)

chore: add driver as explicit dependency where it is a peer dep

---

.evergreen.yml
.evergreen/evergreen.yml.in

This distro does not exhibit the Python problem that macos-1014 has.
Moving over the unit tests seems like a reasonable workaround at this
point, given that all other attempts at solving this issue have failed,
and we still keep end-to-end test coverage on macos-1014 around.

chore(ci): use MacOS 11.00 in unit tests MONGOSH-1058

---

README.md
packages/arg-parser/src/cli-options.ts
packages/cli-repl/README.md
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/constants.ts
packages/cli-repl/src/format-json.ts
packages/i18n/src/locales/en_US.ts

Add a `--json` CLI flag with possible `--json=canonical` and
`--json=relaxed` flags, the default being `canonical`.
When used, mongosh will print Extended JSON as output. This
flag can only be used in conjunction with `--eval`, and is
mutually exclusive with `--shell` and providing files on
the command line.
Errors and regular output are not distinguished based on
the output alone, only in the exit code of mongosh.
Repeated errors while trying to serialize the output to
Extended JSON will not be serialized.

feat(cli-repl): add --json CLI flag MONGOSH-1249

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

Add a shell helper for sharded data distribution info api.
Part of the project [PM-2934](https://jira.mongodb.org/browse/PM-2934).
** This PR wil not be merged until [SERVER-67891](https://jira.mongodb.org/browse/SERVER-67891) is committed.

feat(shell-api): added a new shell helper 'getShardedDataInformation' MONGOSH-1254

---

packages/node-runtime-worker-thread/src/child-process-proxy.spec.ts
packages/node-runtime-worker-thread/src/child-process-proxy.ts

This ensure that the auxilliary child processes stops once its parent process has terminated, even if it did not perform a proper shutdown of the child process.

fix(node-runtime-worker-thread): close child process on parent disconnect

---

packages/shell-api/src/shard.ts

Update `serverVersions` tag for `getShardedDataDistribution` to 6.0.3
Part of the project [PM-3019](https://jira.mongodb.org/browse/PM-3019) (Backport of [PM-2934](https://jira.mongodb.org/browse/PM-2934) to v6.0)
The feature `getShardedDataDistribution` has already been backported to v6.0.

feat(shell-api): Change 'serverVersions' tag for 'getShardedDataDistribution' to v6.0.3 MONGOSH-1303

---

packages/cli-repl/src/format-output.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/shell-api/src/shell-api.spec.ts
packages/shell-api/src/shell-api.ts
packages/shell-api/src/shell-instance-state.ts

Here's how the output looks for `printjson(Array.from({length: 1000}, (_, idx) => ({_id: ObjectId(), idx})));` now:
|mongo|mongosh|
|---|---|
|<img width="588" alt="image" src="https://user-images.githubusercontent.com/5036933/201730865-bed67dcf-52a2-4eeb-adbe-69cef6e0a175.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/5036933/201732397-e5fab13f-17d1-4bc8-9155-c1e2acdf75ed.png">|
TODO:

feat(shell-api, cli-repl): pass print type as part of the onPrint callback; do not limit the output of printjson MONGOSH-955

---

.evergreen.yml
config/release-package-matrix.js
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/smoke-tests.ts
packages/cli-repl/test/e2e.spec.ts
packages/logging/src/analytics-helpers.spec.ts
packages/logging/src/analytics-helpers.ts
scripts/docker/ubuntu22.04-nohome-deb.Dockerfile

Do not enable telemetry unless a new config file has been written or an existing one read.
The alternative would be to send telemetry even when user ids cannot be persisted; this would make it appear as if a new user connected every time mongosh runs, which is probably not what we want.

fix(cli-repl): do not enable telemetry unless user id is persisted MONGOSH-1320

---

packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.ts

nanobus inherently leaks memory, which means that it can make mongosh crash in certain scenarios.
Since we do not actually use the features of nanobus (mostly being able to listen for a generic `'*'` event), just replace it with the standard `EventEmitter` to fix this.

fix(cli-repl): drop nanobus in production usage MONGOSH-1330

---

packages/service-provider-server/src/cli-service-provider.ts

See the ticket/source comments for details. I’ve confirmed that this fixes the bug, although the main thing to address here is probably writing an e2e test in Compass.

fix(service-provider-server): pass in driver to fle addon directly COMPASS-6342

---

packages/cli-repl/test/e2e-analytics.spec.ts

Change replset member priorities so that no node other than the one we expect to become primary can become a primary, increase the timeout for doing so, and as a drive-by use more inclusively named helpers where available.

chore(cli-repl): try to reduce analytics node test flakiness

---

packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

MONGOSH-1301
Two questions for reviewers:
- Are there specific cases for when we show `MongoshRuntimeError`? I wasn't sure if that should be used here, in these changes we are going back to showing `MongoServerError`.
- Should we make this do a full check for the server version before showing the server version part of the error message? We can do something like https://github.com/mongodb-js/mongosh/blob/bed1edfe73b4b374d4ba6089d8c48d01fa56f93f/packages/shell-api/src/database.ts#L620 in that case.
```ts
async _improveErrorMessageForGetShardedDataDistribution(err: Error): Promise<void> {
try {
const serverVersion = await this.version();
if (serverVersion && +serverVersion.split('.')[0] < 6) {
err.message = `Your server version is ${serverVersion}, which does not support the …
```

chore(shell-api): update error message for getShardedDataDistribution MONGOSH-1301

---

config/webpack.base.config.js

This results in:
- A 2.5 % larger generated CLI JS bundle file
- A 15.7 % smaller generated CLI executable file
- A 3.5 % faster startup time overall (measured for `--version`)

chore(build): enable ascii_only terser flag MONGOSH-1345

---

scripts/prep-fle-addon.sh

The suggested change is for the case when someone wants to build libmongocrypt locally, instead of using prebuilt binaries, but the build fails, because "*-static*" libs cannot be found.
Depending on the system used for the build, libraries can be put into
"lib64" folder, instead of "lib", for example(oraclelinux 8):
[jenkins@464de3faf24f cmake-build]$ cmake -DCMAKE_INSTALL_PREFIX=./tmp/fle-buildroot -DCMAKE_PREFIX_PATH=./tmp/fle-buildroot -DDISABLE_NATIVE_CRYPTO=1 ..
...
[jenkins@464de3faf24f cmake-build]$ make -j8 install
...
[100%] Linking C executable test-mongocrypt
[100%] Built target test-mongocrypt
Install the project...
-- Install configuration: ""
-- Installing: /home/jenkins/libmongocrypt/cmake-build/tmp/fle-buildroot/**lib64**/libbson-static-for-libmongocrypt.a
-- Installing: …

Fix path for built libs

---

packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/aggregation-cursor.spec.ts
packages/shell-api/src/cursor.spec.ts

Here's a patch from the driver running against the changes in this branch: 
https://spruce.mongodb.com/version/63b7157961837d672d740cca/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

fix(shell-api): don't pass options into cursor.close() MONGOSH-1356

---

packages/service-provider-core/src/all-transport-types.ts
packages/service-provider-core/src/index.ts
packages/service-provider-core/src/map-reduce-options.ts

https://github.com/mongodb/node-mongodb-native/pull/3511 removes support for `MapReduce` in the Node driver. 
This PR moves `MapReduceOptions` and `FinalizeFunction` from the driver into mongosh.
Alternatively, we could replace `MapReduceOptions` with `Document` instead of moving the definition out of the driver but since it's only two small interfaces, I felt that it's not a huge burden to maintain.
Example CI run from the driver with no MapReduce and the changes in this PR: https://spruce.mongodb.com/version/63bc2438d6d80a31a0a43fb3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

fix(server-provider-core): don't import MapReduceOptions from Node driver

---

packages/cli-repl/test/e2e-auth.spec.ts

This makes this test pass locally on Ubuntu 22.04 for me.

chore(cli-repl): add ubuntu 22.04 kerberos error message

---

packages/service-provider-core/src/all-transport-types.ts

`BulkResult` is now marked as internal after https://github.com/mongodb/node-mongodb-native/pull/3515 is merged. This fixes the TS compilation error but has no other effect as it should never have been directly accessed.

fix(service-provider-core): bulk result now marked internal NODE-4034

---

packages/cli-repl/src/cli-repl.ts

Just documenting the loading order based on @addaleax comment

chore(cli-repl): add an explanation for the order of loading snippets

---

packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/helpers.spec.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/shard.spec.ts

MONGOSH-1157
This PR updates our `db.collection.stats()` shell api method to use the [aggregation stage `$collStats`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/collStats/) for fetching collection statistics instead of the [`db.runCommand({ collStats: collectionName })`](https://www.mongodb.com/docs/manual/reference/command/collStats/) form. The run command form is to be deprecated by 7.0 (PM-2362)
The [`$collStats`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/collStats/) stage returns a document for each individual shard's statistics. A lot of the code of this pr involves aggregating those documents into one document to be returned. I initially was trying to do this all in one aggregation pipeline, however I found it was going to be a bit …

feat(shell-api): use collStats aggregation stage instead of command for collection.stats() MONGOSH-1157

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts

MONGOSH-545
This PR introduces a public method `getURI` on Mongo which returns connection string of current active connection.

feat(shell-api): introduces public Mongo.getURI

---

packages/node-runtime-worker-thread/src/index.d.ts

This is currently not being used, and if we need it, there is always the builtin `Parameters` type in TS which has the same functionality.

chore(node-runtime-worker-thread): remove unused Params type

---

config/webpack.base.config.js
package-lock.json
package.json
scripts/dummy-browserslist.js
scripts/tr46-stub.js

Both of these packages add nontrivial amounts of code
to our bundles without providing additional value to mongosh.
Therefore, we stub these out and save about 50 % of our bundle
size and shave off about 10 % of startup duration.
MONGOSH-1335

chore: stub out browserslist an tr46 packages MONGOSH-1335

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

This PR updates the implementation of `db.currentOp` to make use of `$currentOp` aggregation stage instead of the command form. There is no change in the output format of the helper. The old arguments are also left intact and are appropriately mapped to relevant options for `$currentOp` stage (reference taken from the [old shell](https://github.com/10gen/mongo/blob/master/src/mongo/shell/db.js#L817-L835))
Closes:
- MONGOSH-1367
- MONGOSH-1157

feat(shell-api): use $currentOp agg. stage for db.currentOp

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
testing/fake-kms.ts

This PR is adjusting our dependencies, fixing our mock so that the updated libmongocrypt does not crash, and adds a new test for the Node.js bindings now being able to pick up AWS KMS credentials from environment variables if that is desired.
Also add `@aws-sdk/credential-prociders` as an explicit dependency.
The `mongodb-client-encryption` package can use this as an optional
peer dependency, and the `mongodb` package currently depends on this
as a peer dependency but will switch to making it an optional peer
dependency as well in the v5.0.0 release.
Installing it as an explicit dependency ensures its presence regardless
of optionality (instead of just relying on the package-lock.json file
for keeping it available).
The latest version of mongodb-client-encryption crashes when
receiving …

chore(deps): bump `mongodb-client-encryption` to 2.4.0 & related updates MONGOSH-1370

---

packages/cli-repl/src/mongosh-repl.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shell-api.ts

This PR adds an on-boot on invokable warning when connected to a fake mongodb deployment (DocumentDB for example).
Closes: MONGOSH-57

feat(shell-api, cli-repl): on-boot warnings for fake MongoDBs

---

config/eslintrc.base.js
package-lock.json
package.json
packages/build/src/packaging/download-crypt-library.ts
packages/cli-repl/test/e2e-fle.spec.ts
packages/i18n/src/locales/en_US.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts

Add `ClientEncryption.encryptExpression` as an analogue to `ClientEncryption.encrypt` and add e2e tests for QE range functionality.

feat: add support for QE range indexes MONGOSH-1371

---

scripts/docker/rocky9-fips-rpm.Dockerfile
scripts/docker/ubuntu22.04-fips-deb.Dockerfile

The Ubuntu 22.04 FIPS docker test recently started failing because something in the `unminimize` step overwrote the files installed from our built “FIPS-y” OpenSSL 3 copy.
Address this by building and installing OpenSSL immediately before installing mongosh itself.

fix(ci): install FIPS-y OpenSSL 3 later in docker tests

---

packages/shell-api/src/integration.spec.ts

See SERVER-43894, the server now returns no error when dropping non-existent collections.

fix(shell-api): adjust .drop() return value for server changes

---

packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts

This PR updates the below mentioned methods to start using helpers provided by [libmongocrypt](https://github.com/mongodb/libmongocrypt/blob/f38c549/bindings/node/lib/clientEncryption.js)
- KeyVault.getKeys
- KeyVault.deleteKey
- KeyVault.addKeyAlternateName
- KeyVault.removeKeyAlternateName
Closes: MONGOSH-1205

chore(shell-api): simplify key-mangement helpers by using driver helpers

---

packages/autocomplete/package-lock.json
packages/autocomplete/package.json

As a followup for tickets COMPASS-6489 and COMPASS-6490, this PR upgrades mongodb-constants in autocomplete.
New update brings autocomplete for
- missing database aggregation stages
- new `bit` operators introduced for aggregation pipeline in MongoDB 6.3

feat(autocomplete): upgrades mongodb-constants

---

packages/autocomplete/package-lock.json
packages/autocomplete/package.json
packages/autocomplete/src/index.spec.ts
packages/autocomplete/src/index.ts

This PR fixes the problem with autocomplete that was earlier not working for db level aggregate (`db.aggregate`)

fix(autocomplete): fixes autocomplete not working for db.aggregate

---

packages/cli-repl/test/e2e.spec.ts

This recently started failing in CI because of [SERVER-73872](https://jira.mongodb.org/browse/SERVER-73872).

chore(cli-repl): skip unique index creation test for apistrict

---

packages/autocomplete/src/index.spec.ts
packages/autocomplete/src/index.ts

I mistakenly assumed that bumping node version was enough to make our autocomplete case-insensitive. This patch changes `filterShellApi` to behave similar to Node.js autocomplete

chore(autocomplete): make autocomplete behavior match node MONGOSH-1087

---

packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

Otherwise:
```js
> db.getCollection('hasOwnProperty')
[Function: hasOwnProperty]
```

fix(shell-api): fix getCollections for Object.prototype keys

---

.evergreen/setup-env.sh
packages/java-shell/build.gradle
packages/java-shell/cli/build.gradle
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt

Hopefully this will fix sporadic NullPointerExceptions that rarely occure inside GraalJS call
This is a bug in GraalJS, people recommend updating:
https://github.com/oracle/graaljs/issues/448

Update GraalJS to 22.3.1

---

packages/shell-api/src/mongo.ts

Connection string options are case-insensitive, so we should widen this check here a bit.

fix(shell-api): fix connection string readPref check in mongo.ts

---

packages/shell-api/src/replica-set.spec.ts
packages/shell-api/src/replica-set.ts

This PR removes the retry behaviour from rs.reconfig method which instead has now been moved to ReplicaSet tests and only optionally used to reduce flakes during cleanup.
*[Original PR](https://github.com/mongodb-js/mongosh/pull/1421) was created with a wrong ticket number.*

fix(shell-api): removes the retry behaviour from rs.reconfig - MONGOSH-1304

---

.evergreen/evergreen.yml.in
scripts/docker/ubuntu18.04-xvfb.Dockerfile

These are currently failing because the VSCode testing integration requires at least Node.js 16.

chore: bump vscode integration tests to run on Node.js 16

---

packages/shell-api/src/helpers.spec.ts
packages/shell-api/src/helpers.ts

`tsToSeconds()` has not been working as intended since it was first written. BSON `Timestamp` objects never had direct `t` or `i` properties, so the `if` condition here would never be met. Instead, if the function received a `Timestamp` object, it would implicitly convert it to a number (via the `Long` class’s `.toString()` conversion method). This happens to work out because `x/(2**32)` corresponds roughly to the time part for a `Timestamp` object `t` when interpreted as a `Long`.
I am not sure why exactly this breaks in the way it does described in the ticket (where this function seems to return `NaN`), but making this function work as intended should address the issue.

fix(shell-api): fix broken tsToSeconds conversion MONGOSH-1428

---

.evergreen/install-node.sh

To counter the effects of the Node.js driver adding these entries (https://github.com/mongodb/node-mongodb-native/blob/4b5be2121fdcca0879447be24e8e935dfcd14764/.evergreen/install-dependencies.sh#L96-L98).

chore(ci): remove `prefix=` entry from `~/.npmrc` MONGOSH-1404

---

package-lock.json
package.json
packages/arg-parser/package.json
packages/logging/package.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package.json
packages/service-provider-server/package.json
packages/shell-api/src/result.ts
packages/snippet-manager/package.json
packages/types/package.json

Bump the driver, bson, and mongodb-client-encryption to their latest versions.

chore(deps): bump driver dependencies

---

package-lock.json
packages/browser-repl/config/webpack.config.base.js
packages/browser-repl/src/components/shell-output-line.tsx

As a drive-by, modify the webpack config so that `npm start` works with the current version of `babel` used by `async-rewriter` (same as in the `java-shell` webpack config).

fix(browser-repl): print contents of strings instead of inspected string MONGOSH-1323

---

package-lock.json
package.json

https://github.com/mongodb-js/mongosh/pull/1440 broke macOS CI further by bumping lerna to a version that has a native dependency that cannot be loaded.

chore(deps): revert lerna bump

---

packages/cli-repl/test/e2e-banners.spec.ts
packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/shard.spec.ts

- Skip FLE tests on 7.x until MONGOSH-1410
- Skip sharding auto-splitter tests entirely after the removal in 7.0
- Make the code in an `after` hook pass if the before hook never ran
- Fix the `collStats` compatibility code in the timeseries case (since now the agg pipeline variant works on timeseries collections in 7.1+)

fix(cli-repl,shell-api): skip/fix tests for latest server alpha

---

packages/browser-repl/src/components/shell-output-line.spec.tsx
packages/browser-repl/src/components/shell-output-line.tsx

d1278ecd5d7d attempted to address MONGOSH-1323 but failed to do so properly because node-runtime-worker-thread adjusts behavior so that most values result in reporting a `string` result back to the frontend.

fix(browser-repl): account for node-runtime-worker-thread-specific result rendering MONGOSH-1323

---

packages/browser-repl/src/components/shell-input.tsx
packages/browser-repl/src/components/shell-output-line.tsx
packages/browser-repl/src/components/utils/expandable.tsx
packages/browser-repl/src/components/utils/line-with-icon.tsx

When trying to update e2e tests in compass to expect new codemirror shell, I noticed that we currently rely on shell output being codemirror which is not true anymore (it's not true in 100% cases anyway, but works for what we are doing in e2e) and makes it hard to pick up expected shell output. This adds a few test ids so that it's easier to make this distinction

chore(browser-repl): add data-testid to lines in shell

---

.evergreen/setup-env.sh
testing/integration-testing-hooks.ts

This broke today because the build hosts were updated to a more recent Python version.
https://mongodb.slack.com/archives/C0V896UV8/p1682441001192679

fix(ci): update Python version for Windows CI

---

packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/e2e-banners.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shell-api.ts

There are currently related tests failing on 6.0.6 because free monitoring was disabled in it. We want to remove the support for this anyway, so let's just get rid of the code and its tests rather than adding an extra version check for the next two weeks.

feat: remove free monitoring banner and deprecate related methods MONGOSH-1415

---

packages/cli-repl/src/async-repl.spec.ts
packages/cli-repl/src/async-repl.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/fixtures/load/long-sleep.js

Fixes Ctrl+C behavior for mongosh running files by making sure that raw mode is disabled for the whole duration of the code evaluation inside `ayncRepl.eval`
TODO:

fix(cli-repl): keep the raw mode off for the whole duration of the eval MONGOSH-1433

---

packages/shell-api/src/mongo.ts

Recently, our serverless connectivity tests have been failing in CI because none of the approaches in the `convertShardKeyToHashed()` were working anymore.
However, our serverless test instance is now running MongoDB 6.3.1, which contains the fix for SERVER-63811; adding a new variant that runs the pipeline against a fake/empty database seems to work now, and is probably the most preferable approach anyway.

fix(shell-api): try running convertShardKeyToHashed agg against empty db

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/logging/src/analytics-helpers.spec.ts
packages/logging/src/analytics-helpers.ts
packages/logging/src/index.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts

This patch adds throttling to the telemetry tracking that is persisted across user sessions for the same userId. The implementation is ready and unit tests in logging are done, but a bunch of e2e tests seem to fail now because of the throttling, so I'm opening it as a draft to see what else is failing that I'm maybe not catching locally.

chore(logging): add throttling to the telemetry helper MONGOSH-1423

---

packages/cli-repl/src/build-info.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/run.ts

Loading the shared library on startup can crash mongosh when it is run on bare-bones x64 systems without additional CPU features, because the shared library uses advanced CPU set features like AVX while its global constructors run. (These features have been required by the server artifacts since 5.0:
https://www.mongodb.com/docs/manual/administration/production-notes/#x86_64)

fix(cli-repl): do not include crypt shared library version in buildInfo MONGOSH-1496

---

package-lock.json
packages/errors/package.json

This should fix the "update automatically generated files" action.

fix(errors): downgrade chalk because the latest versions are esm-only modules, hack old version out of package-lock.json

---

.evergreen/InstallNode.ps1

Not sure how this was working before but from the documentation of PowerShell, it seems `-OutputPath` has not been there since quite some time. It has always been `-DestinationPath`.
I spawned a host with the same distro (windows-vsCurrent-small) for which we had these tests failing and noticed that the version of Powershell over there is 5.1 which only has `-DestinationPath` as the valid argument.
Here are a few links for Powershell Expand-Archive docs for reference:
- [v5.x docs](https://learn.microsoft.com/en-gb/previous-versions/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-5.0)
- [v4.x docs](https://learn.microsoft.com/en-gb/previous-versions/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.1&viewFallbackFrom=powershell-4. …

chore: fix for node install failing on windows machines

---

.evergreen/install-node.sh
.evergreen/retry-with-backoff.sh
package-lock.json
packages/service-provider-server/package.json

Somehow in the [following commit](https://github.com/mongodb-js/mongosh/pull/1503/commits/74b4834086712754bbe08e276eccbfeb6e6c968e#diff-3f8569b068ef11ea8f1fc5b5682d8ba0c6f494982ca211e549ae2156805f3561R72-R75), mongodb-client-encryption as well as kerberos ended up being `devDependencies` in addition to being `optionalDependencies`.
I looked back in commits before this one and concluded that these have always been `optionalDependencies` so this might have been just a mistake. It can be seen from the [base build of this failed build](https://spruce.mongodb.com/version/64a41f0d5623435ea6d2a7b0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=linux_s390x_build) that we always had [the same failure](https://parsley.mongodb.com/evergreen/mongosh_linux_s390x_build_compile_artifact_817467053c …

chore: fixes build failures for s390x and ppc64le archs

---

package-lock.json
packages/service-provider-core/package.json
packages/service-provider-core/src/connect-info.spec.ts
packages/service-provider-core/src/connect-info.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts

A follow up of https://github.com/mongodb-js/mongodb-build-info/pull/22, which brings updated logic for fake deployment detection to mongosh.

chore: updates fake mongodb deployment detection using mongodb-build-info@1.6.2

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/test/e2e-oidc.spec.ts

Currently, if a username is specified but no password, mongosh will prompt for a password before connecting.
Kerberos/GSSAPI was made an exception, since it rarely makes use of a password. However, there are other mechanisms where a username can, and often will, be provided without a password (AWS, OIDC, and technically even X.509).
This commit prevents mongosh from prompting for a password for those mechanisms, and inverts the check to explicitly list the mechanisms that *do* require a password (the list of auth mechanisms is unlikely to change soon, but if it does, it likely wouldn’t include a new password-based auth mechanism, so avoiding false positive return values seems like a better choice than avoiding false negative return values).

fix(cli-repl): invert and fix passwordless-auth-mechanism check

---

package-lock.json
packages/service-provider-server/package.json

… until the driver package starts depending directly on it, rather than in an optional dependency.

chore(deps): use @mongodb-js/saslprep COMPASS-6996

---

packages/build/src/download-center/config.spec.ts
packages/build/src/download-center/config.ts

This PR updates our method of publishing download center config. Earlier we used to replace the download center config entirely with the to-be released version. With this change, we instead will be taking into account the already published config, if any, and will insert the version info for the to-be released version while keeping the other, earlier released major versions.
Pointing this to `main` only because it does not block us from releasing `main` as of now for 1.x.x
Earlier
-------
<table>
<tr>
<td>Existing Config</td>
<td>Current Release Version</td>
<td>Updated Config</td>
</tr>
<tr>
<td>
```
{
versions: [{
_id_: '1.2.2'
version: '1.2.2',
platform: [{ ... }]
}],
...
}
```
</td>
<td>1.2.3</td>
<td>
```
{
versions: [{
_id_: '1.2.3'
version: '1.2.3',
platform: [{ ... }]
}],
...
} …
```

chore(build): update download center config with new release info, instead of replacing it entirely when doing release - MONGOSH-1348

---

.evergreen.yml
.evergreen/evergreen.yml.in
config/release-package-matrix.js
package-lock.json
packages/cli-repl/test/e2e-auth.spec.ts
packages/cli-repl/test/e2e-oidc.spec.ts
packages/cli-repl/test/e2e-snippet.spec.ts
scripts/docker/debian12-deb.Dockerfile

Add docker-based smoke tests for Debian 12 and e2e tests for RHEL9 and Ubuntu 22.04.

chore(ci): expand test matrix MONGOSH-1140 MONGOSH-1142 MONGOSH-1146

---

.evergreen/install-node.sh
.evergreen/setup-env.sh

A few runners are reporting nvm already installed in HOME directory and that is breaking our installation scripts. This PR will change the install location to project directory.

fix: install nvm in task local directory instead of home

---

packages/shell-api/src/collection.ts

The server team has confirmed that they prefer for downstream teams to check error codeName values rather than (only) code numbers, as the latter may go away when code is being refactored.
(Opened COMPASS-7082 and MONGOSH-1554 to track the other instances of this.)

chore(shell-api): check StaleConfig error codeName in addition to code number

---

package-lock.json
packages/arg-parser/package.json
packages/logging/package.json
packages/service-provider-server/package.json
packages/types/package.json

Adopt DNS result order changes with Node v18 and VSCode 1.82.0-insider updates that affected the VSCode extension.

fix: adopt dns result order changes VSCODE-458

---

packages/build/src/download-center/config.ts
packages/build/src/index.ts

Account for `NoSuchKey` errors being thrown when downloading files from AWS.
(See the failure from https://spruce.mongodb.com/task/mongosh_draft_publish_release_release_publish_dry_run__v1.10.5_draft.0_23_08_11_15_28_19/logs?execution=0 in the 1.10.5-draft.0 build)

fix(build): more resilient S3 handling for JSON feed MONGOSH-1242

---

packages/build/src/packaging/download-crypt-library.ts

The server team just release 7.0.0, which does not provide a crypt_shared library for RHEL7 on s390x. To keep things as they are currently working, we continue to use the 6.0.x shared library instead. We may want to switch to the RHEL8 7.x-server library at some point in the future when there are new QE features that require an updated shared library.

fix(build): keep using 6.0.x RHEL7.2 crypt_shared library on s390x

---

.git-blame-ignore-revs

This makes it easier to run `git blame` across the recent bulk source code changes for linting/prettifying.
Enable with:
```
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
(The filename is convention, and e.g. also used by the MongoDB server source repository.)

chore: add .git-blame-ignore-revs file

---

.evergreen/install-node.sh
.evergreen/setup-env.sh
scripts/docker/rocky8-package.Dockerfile

Previously, our CI on Node.js 20 was failing silently (e.g. the bug fixed by https://github.com/mongodb-js/mongosh/pull/1591 did make mocha exit with a non-zero exit code, but not our CI).
This is being caused by an incompatibility between npm@8.x and Node.js 20 (which could reasonably be argued to be a Node.js bug, the same one that the PR mentioned above accounts for). Upgrading to npm@9.x should fix this because it includes a fix in npm as well (https://github.com/npm/cli/issues/6399).

fix(ci): use npm@9.x

---

packages/cli-repl/src/update-notification-manager.spec.ts
packages/cli-repl/src/update-notification-manager.ts

This should remove flakiness from a recently introduced test and should also just generally be the right thing to do.

fix(cli-repl): clear update notification cache when source URL changes

---

packages/shell-api/src/bulk.spec.ts
packages/shell-api/src/bulk.ts

This accounts for removal of these legacy getters in the 6.x driver.
The only catch here is that `.result.upserted` is of a different type than `.upsertedIds`, but since the type of the latter matches what our own `BulkWriteResult` class expects (and also matches `.insertedIds`), this is probably closer to a bug fix than proper breakage.

fix(shell-api): use public BulkWriteResult props MONGOSH-1507 COMPASS-7023

---

packages/shell-api/src/aggregate-or-find-cursor.ts
packages/shell-api/src/helpers.spec.ts
packages/shell-api/src/helpers.ts

These are the different ways of doing explain on a cursor or a query:
| Case | Code                                            | Provided Execution Stats | Verbosity         |
|------|-------------------------------------------------|--------------------------|-------------------|
| 1    | db.runCommand({…verbosity:’allPlansExecution’}) | yes                      | allPlansExecution |
| 2    | db.foo.explain(‘allPlansExecution’).agg(…)      | yes                      | allPlansExecution |
| 3    | db.foo.explain().agg(…)                         | no                       | queryPlanner      |
| 4    | db.foo.agg(…).explain()                         | no                       | allPlansExecution |
What are we doing in this PR is aligning case 4, so instead of using `allPlansExecution` by …

fix: use queryPlanner to keep conventions with other explain methods MONGOSH-1317

---

configs/eslint-config-mongosh/index.js
packages/autocomplete/src/index.spec.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/e2e-tests/test/e2e-auth.spec.ts
packages/e2e-tests/test/e2e.spec.ts
packages/editor/src/editor.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/help.spec.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/shell-bson.spec.ts
packages/shell-evaluator/src/shell-evaluator.spec.ts

The are good to reinstate as errors IMHO:
```
'mocha/no-identical-title': 1,
'mocha/no-nested-tests': 1,
```
So I fixed the lines they caught.
I think the following mocha-related overrides make sense to leave as warnings:
```
'mocha/no-exports': 1,
'mocha/max-top-level-suites': 1,
'mocha/no-sibling-hooks': 1,
```
But let me know if others feel differently. I don't feel too strongly about it.

chore: turn some mocha lint rules back into errors, fix the errors MONGOSH-1508

---

.evergreen.yml
.evergreen/evergreen.yml.in

- Add `type:` tags to commands to more easily distinguish between setup failures and actual test failures
- Use `env:` to supply environment variables rather than injecting them into bash scripts
- De-duplicate `e2e_tests_darwin_x64` which currently ran twice on macOS 11.00 x64, and add a `e2e_tests_darwin_arm64` task which seems to have been a very notable omission from our e2e test matrix so far

chore(ci): clean up evergreen config

---

packages/cli-repl/src/format-output.ts
packages/i18n/src/locales/en_US.ts
packages/service-provider-core/src/connect-info.spec.ts
packages/service-provider-core/src/connect-info.ts
packages/shell-api/src/index.ts
packages/shell-api/src/interruptor.spec.ts
packages/shell-api/src/interruptor.ts
packages/shell-api/src/shell-instance-state.spec.ts
packages/shell-api/src/shell-instance-state.ts
packages/shell-api/src/stream-processor.ts
packages/shell-api/src/streams.spec.ts
packages/shell-api/src/streams.ts

This PR adds Atlas Stream Processing support to the mongosh:
- adds a new flag `is_stream` to the `ConnectInfo` type
- changes default prompt to `AtlasStreamProcessing> ` when `is_stream` is `true`
- adds a new global object `sp` for doing streams related operations

feat: add atlas streams support MONGOSH-1514

---

package-lock.json
packages/service-provider-server/package.json

https://github.com/mongodb-js/kerberos/commit/abaf8d4e32692a889d53a35b05fcaa4df12c280b raised the ABI requirements for prebuilt kerberos binaries, breaking our connectivity tests. Since the 2.0.2 release does not contain critical bug fixes, we can downgrade until this issue is resolved on the Node.js driver side.

fix(service-provider-server): downgrade kerberos to 2.0.1

---

packages/async-rewriter2/benchmark/index.ts
packages/async-rewriter2/src/async-writer-babel.spec.ts
packages/async-rewriter2/src/stages/wrap-as-iife.ts

In the initial async rewriter step, we wrap the incoming script in an IIFE so that we can then perform all subsequent steps under the assumption that all code is run inside a function.
Part of this step is to look at the completion records of the code and using it as the return value of the generated function.
We use babel’s `path.getCompletionRecords()` method for this; that works nicely, except for fact that, despite its name, it has side effects, and in particular just removes `break;` statements from the AST.
(https://github.com/babel/babel/commit/b577e44d168ed6f38b48880a3d5f42c7079d430b)
I’ve considered a few approaches to this problem, like trying to clone the relevant AST before calling that method (problematic because then the return value of `path.getCompletionRecords()` does not …

fix(async-rewriter): implement custom completion record computation MONGOSH-1579

---

packages/e2e-tests/test/e2e-tls.spec.ts

We do not test against the 4.0 server anymore, so we can remove the tests for that server version from our e2e test suite.
Also, add `--tlsAllowConnectionsWithoutCertificates` to account for upcoming server changes that require this flag to be explicitly set when connecting without a client certificate.
(Diff best viewed with whitespace changes disabled :slightly_smiling_face:)

fix(e2e-tests): remove pre-4.2 tests, explicitly allow certless connections MONGOSH-1592

---

.evergreen.yml
.evergreen/evergreen.yml.in

Missed this in def7f1c5c9a0466269aa1546.

fix(ci): also skip java-shell tests on 4.2.x enterprise server

---

.gitignore
packages/build/src/npm-packages/list.spec.ts
packages/build/src/npm-packages/publish.ts

Before publishing to npm, lerna ensures that the working tree is in a clean state (no unchanged or uncommitted files).
Our logic to make `git` assume that files were unchanged was broken for a few files, in particular the top-level package.json and the `.nvm` directory that we now place under the `.evergreen/` folder in the repository rather than a temporary path.

fix(build): fix list of files expected to be unchanged for releases

---

package-lock.json
packages/build/src/npm-packages/publish.spec.ts
packages/build/src/npm-packages/publish.ts
packages/connectivity-tests/package.json
packages/e2e-tests/package.json

The publishing step would currently fail on the `e2e-tests` package because it defined a broken `prepublish` script.
We should not be trying to publish the package at all; mark it `private`.

fix: do not attempt to publish e2e-tests package

---

packages/logging/src/analytics-helpers.spec.ts

Because file system operations are not guaranteed to complete in the order in which they were started, this test was previously flaky.
It seems in line with the goals of the test to just allow either session to “win” the lock file, so do that instead.

fix(logging): relax ThrottledAnalytics two-session test

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

Currently, MongoDB version will be printed as part of the greeting message. We'd like to not show it when connecting to a streams processing instance as that info is not very relevant.

feat(cli-repl): do not show MDB version for SPI STREAMS-576

---

.evergreen/compile-artifact.sh
.evergreen/setup-env.sh

On x64 Linux, the v4 mongodbtoolchain gcc is configured with `--with-arch=sandybridge`, raising the minimum CPU requirements to that level. In particular, availability of the AVX CPU feature is made a prerequisite for the generated executables to run.
It is possible to override this default for the v4 mongodbtoolchain when compiling a specific executable. However, another quirk of this toolchain (and reason why we want to migrate away from it) is that it statically links in the C++ standard library, which has unfortunately been compiled using the compiler's defaults.
On the server side, 5.0+ uses AVX as a minimum hardware requirement, but since mongosh 2.x is intended to support both 4.2 and 4.4, we should stick to the requirements of these older versions.
So, for now, just switch back to …

fix(ci): do not use mongodbtoolchain v4 to compile mongosh MONGOSH-1604

---

packages/build/src/compile/signable-compiler.ts

See the comments in MONGOSH-1604/MONGOSH-1605. A proper solution involves at least updates to Node.js core, so just disabling it again should be a good workaround for now.

fix(build): disable startup snapshot support again for now MONGOSH-1605

---

config/release-package-matrix.js

This partially undoes the changes we made in f25ad643ebe1c3ee after more conversation with product.

fix(build): use deprecated minimum OS versions for DL center MONGOSH-1602

---

package-lock.json
package.json
packages/arg-parser/package.json
packages/e2e-tests/package.json
packages/service-provider-core/package.json
packages/service-provider-server/package.json
packages/shell-api/package.json
packages/types/package.json

https://jira.mongodb.org/browse/MONGOSH-1528 should be fixed by https://jira.mongodb.org/browse/NODE-5496 which is in 6.2.0.

chore: bump the driver to 6.2.0 MONGOSH-1528

---

packages/shell-api/src/integration.spec.ts

The latest alpha seems to have changed things:
```
[2023/11/06 15:51:29.306]   3) Shell API (integration)
[2023/11/06 15:51:29.306]        collection
[2023/11/06 15:51:29.306]          aggregate
[2023/11/06 15:51:29.306]            runs an explain with explain: queryPlanner:
[2023/11/06 15:51:29.306]       AssertionError: expected { explainVersion: '2', …(5), …(2) } to contain keys 'ok', and 'stages'
[2023/11/06 15:51:29.306]       + expected - actual
[2023/11/06 15:51:29.306]        [
[2023/11/06 15:51:29.306]       -  "command"
[2023/11/06 15:51:29.306]       -  "explainVersion"
[2023/11/06 15:51:29.306]          "ok"
[2023/11/06 15:51:29.306]       -  "queryPlanner"
[2023/11/06 15:51:29.306]       -  "serverInfo"
[2023/11/06 15:51:29.306]       -  "serverParameters"
[2023/11/06 …
```

chore: try and make the test aggregation more complicated so it doesn't drop 'stages' from the explain plan  MONGOSH-1635

---

package.json

Otherwise you need to run install before you run install making this command a bit unhelpful

chore: run cross-env with npx in bootstrap

---

packages/cli-repl/src/async-repl.ts
packages/cli-repl/src/mongosh-repl.spec.ts

This PR wraps the internals of the async repl `eval()` method in an async function and calls it making `eval` itself an async function.  This prevents warnings from being emitted in Node21+, when the method is promisified.

fix(cli-repl): prevent promisify promise-returning function warning in async repl

---

package-lock.json
packages/build/package.json
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/startup-timing.ts
packages/shell-evaluator/src/shell-evaluator.ts

```
$ time env MONGOSH_SHOW_TIMING_DATA=1 ./dist/mongosh --version
0.0.0-dev.0
┌─────────┬─────────────────────────────────────┬────────────┬─────────────┐
│ (index) │                  0                  │     1      │      2      │
├─────────┼─────────────────────────────────────┼────────────┼─────────────┤
│    0    │      'Process initialization'       │  '0.00ms'  │     ''      │
│    1    │        'Enter BoxednodeMain'        │  '0.09ms'  │  '+0.09ms'  │
│    2    │  'Start InitializeOncePerProcess'   │  '0.09ms'  │  '+0.00ms'  │
│    3    │ 'Finished InitializeOncePerProcess' │  '1.75ms'  │  '+1.67ms'  │
│    4    │          'Initialized V8'           │  '2.42ms'  │  '+0.67ms'  │
│    5    │         'Initialized Loop'          │  '2.51ms'  │  '+0.09ms'  │
│    6    │ …
```

chore(cli-repl): add startup timing measurement functionality

---

.evergreen.yml
.evergreen/evergreen.yml.in
.evergreen/run-e2e-tests.sh
config/build.conf.js
config/release-package-matrix.d.ts
config/release-package-matrix.js
package-lock.json
packages/build/src/compile/signable-compiler.ts
packages/connectivity-tests/test/all.sh
packages/connectivity-tests/test/atlas.sh
packages/connectivity-tests/test/kerberos.sh
packages/connectivity-tests/test/kerberos/Dockerfile.node20
packages/connectivity-tests/test/kerberos/Dockerfile.rocky8
packages/connectivity-tests/test/kerberos/Dockerfile.rocky9
packages/connectivity-tests/test/kerberos/Dockerfile.ubuntu2004
packages/connectivity-tests/test/kerberos/Dockerfile.ubuntu2204
packages/connectivity-tests/test/kerberos/docker-compose.kerberos.yaml
packages/connectivity-tests/test/kerberos/kerberos-run.sh
packages/connectivity-tests/test/kerberos/krb5.conf
packages/connectivity-tests/test/ldap.sh
packages/connectivity-tests/test/localhost.sh
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts
packaging/deb-template/DEBIAN/control

- Update the Kerberos addon to the latest version (2.1.0).
- Build the Kerberos addon using RTLD for Linux mongosh executables
(i.e. opening the system Kerberos libraries using `dlopen()` to avoid
the symbol conflict with OpenSSL 3 on RHEL8).
- Update the `.deb` definitions to account for the fact that the
Kerberos system libraries are no longer a strict dependency
of mongosh.
- Include the Kerberos version in the `--build-info` output.
- Make sure that if loading the Kerberos addon fails during a
connection attempt, a meaningful error message gets passed
to the user, instead of the driver’s default one (which
swallows all information about the root cause).
- As a drive-by, also do that for mongodb-client-encryption; we
occasionally receive bug reports about CSFLE/QE not working on …

fix(deps): build kerberos in RTLD mode for Linux executables MONGOSH-1628

---

.evergreen-nightly-driver.yml
.evergreen.yml
.evergreen/evergreen.yml.in
.evergreen/install-npm-deps.sh
scripts/replace-package.js

For use with https://spruce.mongodb.com/project/mongosh/settings/periodic-builds. Or any other way that you can specify an evergreen config file other than the default one.

chore: add a config for running CI against the nightly driver MONGOSH-1473

---

.evergreen.yml
.evergreen/evergreen.yml.in
.evergreen/install-npm-deps.sh

Replaces https://github.com/mongodb-js/mongosh/pull/1788, follow-up to https://github.com/mongodb-js/mongosh/pull/1780
See also https://spruce.mongodb.com/project/mongosh/settings/periodic-builds and https://spruce.mongodb.com/project/mongosh/settings/patch-aliases

chore: use patch aliases to run just some of the build variants for the nightly driver tests

---

.evergreen.yml
.evergreen/node-20-latest.json

Seems to work! This bumps Node.js to 20.11.0, but applies an additional dependency upgrade to c-ares, a DNS library used by Node.js, to fix compilation on Windows. 
(Patch created by cherry-picking nodejs/node@0090c107820 onto v20.11.0 tag, then `git diff HEAD~1 deps > ../mongosh/scripts/nodejs-patches/002-cares-1-25-commit-0090c107820.patch`)

chore: update node.js version to 20.11.0 MONGOSH-1648

---

packages/shell-api/src/integration.spec.ts

It turns out that actually testing that this option works on latest-alpha builds of the server is pretty tricky. Since we do not actually touch the options in any way in mongosh and just pass them through to the server, it should be okay to drop this test.

fix(shell-api): do not test `validate` command background option MONGOSH-1664

---

packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/mongo-errors.spec.ts
packages/shell-api/src/mongo-errors.ts

https://jira.mongodb.org/browse/MONGOSH-1679
Changes:
- `runCommand` in the `shell-api` catches `NotPrimaryNoSecondaryOk` and applies a custom message
- the custom `runCommand` message is ignored in the `mongo-errors` post-processing
Note: I used `codeName` instead of `code` in the new part for readability - I hope it's okay. Let me know if you think it's safe to switch the `mongo-errors` section to also use `codeName`.

fix(shell-api): improve error message on reading from secondary via runCommand MONGOSH-1679

---

packages/logging/src/setup-logger-and-telemetry.ts

https://jira.mongodb.org/browse/COMPASS-7607
The legacy anonymous `userId` shouldn't be send as `userId` to telemetry, because this expects only the AUID under such name. Here, we keep it as a direct fallback for the `anonymousId`.
I haven't added tests, because under current type definitions `anonymousId` isn't optional.

fix(logging): remove userId from identify and track COMPASS-7607

---

packages/async-rewriter2/bin/async-rewrite.js
packages/shell-evaluator/src/shell-evaluator.ts

No user-facing impact at this time, just two things that I noticed:
- We were consuming Buffers instead of strings in our example script
- We didn't actually run the async rewriter during startup snapshot building, so any lazy loading performed by babel was delayed until runtime; we can save ~75ms startup time by just doing this as part of the snapshot (this will only take effect once snapshots are enabled again, of course).

chore: small fixes from perf investigation

---

packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-auth.spec.ts

3f55e4c02563a696 did not add a test-ci-coverage task to the e2e-test package, but changed the definition of the unit test tasks in CI to run the test-ci-coverage task, so that e2e tests wouldn't run as part of the unit test suite.

fix(e2e-tests): run in unit test suite MONGOSH-1716

---

.evergreen.yml
.evergreen/evergreen.yml.in

cbaeef2879d4c4 recently refactored the evergreen configuration file. This subtly introduced some breakage, because the `env` and `silent` options are not command options, but rather need to be nested under the `params` key.
I've intentionally left the `silent:` option disabled as this would hide genuinely valuable debug output otherwise.
This might be a good point to reconsider fixing the evergreen validation warnings that are displayed in CI; `evergreen validate .evergreen.yml` did catch these issues, but since there are a large number of existing warnings (around dependencies between tasks), these specific warnings were drowned out/not visible in the evergreen UI.

fix(ci): fix `release_publish(_dry_run)` parameters

---

packages/e2e-tests/test/e2e-tls.spec.ts
packages/e2e-tests/test/test-shell.ts

The server will no longer start when TLS is enabled without a CA certificate argument. This does not affect our tests’ functionality, only how we start the server in them.

chore(e2e-tests): account for upstream server TLS option changes MONGOSH-1718

---

.evergreen/install-node.sh
.evergreen/setup-env.sh
scripts/docker/rocky8-package.Dockerfile

npm 9.9.3 was released yesterday and broke Windows CI because it was not installable from the previous npm version. In a spawn host, using npm 10.x worked instead, so let’s go with that.

chore(ci): use npm@10.x instead of npm@9.x

---

.evergreen/install-node.sh
packages/shell-api/src/integration.spec.ts

- Specifically choose the npm version to be one that matches the Node.js version we install; this is a better version of the fix in a459c995cc6b, which made Windows CI (almost) green but left the test_n16_snippet_manager task failing due to the specific combination of Node.js 16 and npm 10.x on Windows.
- Account for upstream server changes to the PlanCache functionality.

chore: make CI a bit greener MONGOSH-1726

---

packages/connectivity-tests/test/kerberos.sh
packages/connectivity-tests/test/ldap.sh
packages/connectivity-tests/test/localhost.sh

This should hopefully fix some CI breakage for us, same as in Compass.
Refs: https://github.com/mongodb-js/compass/commit/a322429f4a970695629242657427ce4ff8ecfa43

chore(ci): use `docker compose` over `docker-compose`

---

packages/arg-parser/src/cli-options.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/smoke-tests.ts
packages/e2e-tests/test/e2e.spec.ts
packages/e2e-tests/test/test-shell.ts
packages/logging/src/setup-logger-and-telemetry.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/types/src/index.ts

[Definitely recommend viewing the diff in whitespace-changes-disabled mode :)]
- Allow running `MongoshNodeRepl` instances either based on:
- The existing mechanism for running code, which is spinning up
a Node.js REPL and using it to evaluate code; or
- A more lightweight mechanism that only creates a `vm` context
and then run code using that context directly.
- Introduce a new command-line switch, `--jsContext`, that can be
used to explicitly select the desired behavior, with possible values
of `repl`, `plain-vm` and `auto`. The default behavior is to switch
depending on whether the CLI will enter interactive mode or not.
Running in `plain-vm` mode will significantly improve runtime
performance (a 6× reduction of script run time in local testing),
coming from the removal of async …

feat: replace Node.js REPL with plain vm context for script usage MONGOSH-1720

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/repl-helpers.ts

Avoid interaction between TTY raw mode toggling done by the prompt and TTY raw mode toggling done by our/the Node.js REPL implementation by ensuring that prompts always run in the fully asynchronous part of REPL evaluation.

fix(cli-repl): fix prompt TTY raw mode toggling MONGOSH-1667

---

licenses.json

This is no longer necessary since 20df659f9ae0 and made our vuln scan CI job and the GH actions runs for `main` commits fail since then.

fix(ci): remove unused licenses.json entry

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts

This can be disabled through `--no-quiet` or `--verbose` (although `--verbose` may gain other meanings in the future depending on the outcome of MONGOSH-970).

feat(cli-repl): make `--quiet` the default for non-interactive usage MONGOSH-1721

---

.evergreen.yml
.evergreen/evergreen.yml.in

- Do not label the VSCode integration test as required for `release_draft`
- *Do* label the vulnerability check task as required for it
- Do not download Chrome for browser testing in the release tasks to reduce run time a bit

chore(ci): small evergreen config cleanups

---

.evergreen.yml
.evergreen/evergreen.yml.in

This reverts commit 773eee6fd002aa020be37e43fc24f69159ecf3e2.
These are failures that we should keep being aware of, but the VSCode tests *are* still useful regardless of the failing OIDC tests.
I assume this was disabled for a release, but 97d8c2e966f029699356ed70efc9328b397f6887 already removed this task from the list of tasks required for releases.

Revert "chore(ci): disables test_vscode task (#1888)"

---

packages/cli-repl/webpack.config.js
packages/e2e-tests/test/e2e-oidc.spec.ts

This fixes OIDC for compiled executables, because class exports like the `Issuer` class from `openid-client` or `IncomingMessage` from `http` did not fully have properties on the function and/or its prototype forwarded, effectively breaking the feature.
This was not caught by our e2e tests because they were first written before the 7.x+ server was the default stable one, and therefore additional checks needed to be added to the test conditions for it.
It is now safe to remove those checks, which will make the OIDC e2e tests run as part of our regular e2e test suite for compiled executables (on systems that support 7.x+ servers).

fix(cli-repl): use JS Proxy for forwarding lazy-loaded webpack function exports

---

packages/service-provider-core/src/all-transport-types.ts

This type is unused and will be removed from the driver in the future.

chore(service-provider-core): remove `CloseOptions` COMPASS-7754

---

packages/cli-repl/src/mongosh-repl.ts
packages/e2e-tests/test/e2e.spec.ts

Looking at node's [repl history code](https://github.com/nodejs/node/blob/312ebd97c21dc94b8e6456fcf29799b3c5bf8f65/lib/internal/repl/history.js#L127) you can see that flushHistory does not always precede a write. ie. sometimes it would have already written the file before we had a chance to redact the line. The 'line' event seems to always be emitted on repl first, though. So that appears to be safer to use.
I added an e2e test for this as well.

fix(cli-repl): redact for all lines, add e2e test MONGOSH-1682

---

packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/cursor.spec.ts
packages/shell-api/src/database.spec.ts

- Delegate cursor iteration to the driver where possible
- Do not call the wrapped `.tryNext()` method from inside other shell API methods, and instead only call an internal unwrapped version of it (similar to `db.runCommand()` vs `db._runCommand()`
This results in a 60% improvement of runtime in local testing on the `db_cursor_iteration_plainvm` benchmark.

fix(shell-api): improve AbstractCursor iteration performance MONGOSH-1688

---

packages/cli-repl/src/smoke-tests.ts
packages/shell-evaluator/src/shell-evaluator.ts

Painfully obvious bug in 0491491ce96b :) Renamed the benchmark test and fixed it to account for the (now very) different performance measurements after the fix.

fix(shell-evaluator): fix exposed asyncRewrite fn for benchmarks

---

package-lock.json
packages/build/src/compile/signable-compiler.ts
packages/cli-repl/package.json
packages/cli-repl/src/build-info.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e-snapshot.spec.ts
packages/e2e-tests/test/e2e.spec.ts

Instead, use a native addon (https://github.com/mongodb-js/glibc-version) to get the glibc version number.

fix(cli-repl): do not use process.report() to get glibc version MONGOSH-1754

---

packages/build/src/download-center/config.spec.ts
packages/build/src/download-center/config.ts
packages/build/src/run-download-and-list-artifacts.ts

In 2da3c3159545e, we moved file hash computation for our produced artifacts from the JSON feed generation step to the newly introduced "download artifacts" step of the `release_publish` tasks (because we need to download artifacts before we can submit them to the papertrail service). We used the standard-ish SHASUMS format (output of `sha256sum`/input of `sha256sum -c`) for that, but failed to parse it properly when consuming it.
This fixes that and extends the download center config tests to also perform the full "download artifacts" step as part of the test setup, to ensure that the two parts work together properly.

fix(build): fix hash file parsing

---

packages/shell-api/src/integration.spec.ts

This field is gone from most recent server versions. It's probably safe to just ignore this field altogether at this point instead of performing server version detection and adjusting the list of expected keys to account for that.

chore(shell-api): remove dropped timeseries collStats field from test MONGOSH-1763

---

packages/autocomplete/src/index.ts
packages/browser-repl/src/sandbox.tsx
packages/browser-runtime-core/src/open-context-runtime.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/service-provider-core/src/admin.ts
packages/service-provider-core/src/connect-info.ts
packages/service-provider-core/src/index.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts
packages/shell-api/src/shell-instance-state.spec.ts
packages/shell-api/src/shell-instance-state.ts
packages/types/src/index.ts

Do not ~~call~~ wait for `fetchConnectionInfo()` and similar methods when they are not needed. This hopefully improves startup performance in real-world scenarios a bit further.
In order to achieve this:
- Implement a cache/lazy-loading ability for the connection info in the shell-api `ShellInstanceState` class. We now only fetch connection info here if requested, and only refresh it if the service provider instance changed (and not just the database itself).
- Adjust usage of the `fetchConnectionInfo()` method ~~to only be called if we believe it to be necessary~~, and for its result to be awaited only if we need it immediately.
This also adds type safety by removing the `any` typing for `connectionInfo` in `ShellInstanceState`. I admittedly thought that this would be a quick fix, but …

fix(cli-repl): do not wait for connectionInfo in quiet non-REPL mode MONGOSH-1765

---

packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/shell-api/src/shell-api.ts

Adding exceptions to these in 2306b9c1996 was a breaking change for programmatic usage of mongosh, so we should revert this behavior (and possibly reconsider in a major version) while keeping the message itself as introduced in that commit.

fix(shell-api): do not throw exceptions from enable/disableTelemetry() MONGOSH-1769

---

.evergreen.yml
.evergreen/compile-artifact.sh
.evergreen/download-crypt-shared-and-generate-sbom.sh
.evergreen/evergreen.yml.in
config/build.conf.js
package-lock.json
package.json
packages/build/package.json
packages/build/src/index.ts
packages/build/src/packaging/download-crypt-library.ts
packages/build/src/packaging/run-download-crypt-library.ts
packages/build/src/packaging/run-package.ts
packages/build/src/release.ts
scripts/create-purls.js
scripts/write-nodejs-dep.js
testing/integration-testing-hooks.ts

Add generation of [`purls.txt`](https://docs.devprod.prod.corp.mongodb.com/mms/python/src/sbom/silkbomb/docs/PURLS/) and [Silkbomb](https://docs.devprod.prod.corp.mongodb.com/mms/python/src/sbom/silkbomb/docs/SILK)-generated `sbom.json` files to our CI/release infrastructure.
Like the corresponding [Compass PR](https://github.com/mongodb-js/compass/pull/5770), this PR:
- Modifies our crypt_shared-library bundling/downloading step so that we store the version of the crypt_shared library we're bundling
- Generates a list of PURLs and then uses the SilkBomb tool to generate a SBOM file that we can share with DevProd 
(and later turn into its 'augmented' version with vulnerability information)
Unlike the Compass PR, this PR:
- Bundles the generated sbom.json file in existing release artifacts …

feat(ci): add SBOM file to release artifacts

---

packages/cli-repl/src/tls-certificate-selector.spec.ts
packages/e2e-tests/test/e2e-tls.spec.ts

The actual error message we encounter in CI changed recently (from May 6 to May 7), likely as the result of changes to build hosts. Allow the more specific error message here as well, since it covers the same semantics.

chore(cli-repl): relax macOS `--tlsCertificateSelector` test expectations

---

package-lock.json
packages/arg-parser/package.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/logging/package.json
packages/service-provider-server/package.json
packages/types/package.json

This is just an experiment, *not* a production-ready change with tests or documentation, with the goal being to verify that an implementation of this sort can satisfy specific customer needs.

feat(cli-repl): add experimental HTTP OIDC proxying capability MONGOSH-1779

---

packages/service-provider-core/src/cursors.ts
packages/service-provider-core/src/index.ts
packages/service-provider-core/src/readable.ts
packages/service-provider-core/src/writable.ts
packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/aggregate-or-find-cursor.ts
packages/shell-api/src/aggregation-cursor.ts
packages/shell-api/src/change-stream-cursor.ts
packages/shell-api/src/cursor.ts
packages/shell-api/src/run-command-cursor.ts

Instead of directly using driver types, only define the types required for the Shell API, and define them separately from the driver.
This addresses part of MONGOSH-915 and is likely to help pave the way for things like MONGOSH-1285.

chore(service-provider-core): explicitly define cursor types in service-provider-core

---

testing/integration-testing-hooks.ts

This fixes Windows CI, which has been buggy since 3851acb8efb6f4 (but not caught in the CI for that commit as it only took affect once GH actions automatically regenerated our evergreen config file).

fix(ci): strip special characters from mongodb-runner tmp directories

---

package-lock.json

https://jira.mongodb.org/browse/MONGOSH-1791
From the vulnerability description:
"An attacker can manipulate a system that uses `isLoopback()`, `isPrivate()` and `isPublic` functions to guard outgoing network requests to treat certain IP addresses as globally routable by supplying specially crafted IP addresses."
There is no fix for `ip`, but `pac-resolver` has a patch that removes the dependency on `ip` (implements it's own `isLoopback` method). Unfortunately this fix hasn't bubbled up our dependency tree yet, which is why I'm proposing an override for the sub dependency. I'm not too happy about overrides, because they tend to be forgotten later - so I'm curious if we have a process for dealing with such situations

fix(deps): bump pack-resolver version MONGOSH-1791

---

packages/autocomplete/src/index.spec.ts
packages/autocomplete/src/index.ts
packages/shell-api/src/shell-instance-state.ts

Recent server source changes put the `buildInfo` command behind authentication. We previously assumed that this information would always be available (and, as a corollary, that if the information from `buildInfo` was absent, topology information would also be absent), and should stop assuming this.
Long-term, it is probably desirable to rely on `buildInfo` as little as possible – for example, most of our version checks for autocompletion should probably be wire version checks instead of server release version checks.
This should address some failures occuring in the latest-alpha CI jobs.

fix(autocomplete): handle missing `buildInfo` well MONGOSH-1792

---

.evergreen/package-and-upload-artifact.sh

https://jira.mongodb.org/browse/MONGOSH-1644
Retry placements considered (ordered by scope):
1. retry the evergreen command
2. retry docker build
3. retry the individual package installs (either via bash script or package manager configuration)
Decided against 1. because evergreen only has a boolean `retry_on_failure`, so it doesn't look like we can control the number of retries.
2. was chosen over 3. because of complexity.
Note: I'm unsure how to test this change locally

chore: retry docker build MONGOSH-1644

---

config/release-package-matrix.js
packages/build/src/download-center/config.spec.ts

Our `build` package tests have been failing since 904162f5e89f8. This commit fixes:
- Ubuntu 24.04 is not known as part of the server distro list yet, but we can reliably infer its name tag based on the format used for existing Ubuntu distros
- Oracle Linux 9 is not known as a server distro and will likely never be.

fix(build): fix tests for new platforms MONGOSH-1806

---

packages/browser-repl/package.json
packages/browser-repl/src/components/shell-input.tsx
packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx
packages/browser-repl/src/sandbox.tsx

So that we can preserve the input in shell when it's in tab mode in multiple connections

feat(browser-repl): allow to set initial input

---

scripts/docker/centos7-epel-rpm.Dockerfile
scripts/docker/centos7-rpm.Dockerfile

Currently fails in CI with yum error because CentOS 7 is EoL since June 30th and seems like they completely removed original repos used by this version
```
[2024/07/04 13:20:12.395] #9 0.823 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
[2024/07/04 13:20:12.395] #9 0.823 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```
This patch fixes the issue by switching yum to use vault repos instead of base ones

fix(ci): use vault repos for yum on centos7

---

scripts/docker/suse12-rpm.Dockerfile
scripts/docker/suse15-rpm.Dockerfile

For some reason [somewhere around June 26th](https://spruce.mongodb.com/version/667c5725d78eb3000750f0c0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) suse tests started to fail because man page for `mongosh` was missing. I couldn't track it to the root cause or some issue I can link to, but seems like after a certain update `zypper` just stopped extracting all the files from the rpm package, like they are 100% there in the rpm, rpm can list them, but they are just not installed in those directories that are listed in rpm.
Switching to use `rpm` directy to install `mongosh` seems to work around this (at least locally, hopefully CI will confirm this too). I am not sure whether or not we specifically want to test that `zypper` installs `mongosh` correctly, but maybe even if that's the case …

fix(ci): use rpm instead of zypper to install mongosh in suse docker images

---

packages/browser-repl/src/components/shell.tsx

Stumbled on this when adding new "Open shell" buttons in Compas. Because we are evaling these initial values async, we need to store the initial value syncronously when component is first mounted, otherwise it can already update at the moment when we're reading it from the props object

fix(browser-repl): make sure we are actually using initial value of initialEvaluate

---

packages/browser-repl/src/components/password-prompt.tsx
packages/browser-repl/src/components/shell-loader.tsx
packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx
packages/browser-repl/src/sandbox.tsx

This patch removes the theme provider hardcoded to always show dark mode that we wrap around the shell so that we can render it in light mode if needed
|Dark|Light|
|---|---|
|<img width="374" alt="image" src="https://github.com/mongodb-js/mongosh/assets/5036933/57689f18-53cc-4b7e-971e-5d1334932cec"><img width="369" alt="image" src="https://github.com/mongodb-js/mongosh/assets/5036933/65ca74c3-5282-4065-8870-2621213303e3">|<img width="380" alt="image" src="https://github.com/mongodb-js/mongosh/assets/5036933/872a98d5-e071-4a7b-b52f-19a403a5c786"><img width="385" alt="image" src="https://github.com/mongodb-js/mongosh/assets/5036933/fc7c8901-d61d-4e21-9678-6d21b827b8b5">|

feat(browser-repl): allow to render browser-repl in light mode

---

packages/shell-api/src/explainable.spec.ts
packages/shell-api/src/explainable.ts
packages/shell-api/src/integration.spec.ts

The explain().find() should support options including collation. See [MONGOSH-1670](https://jira.mongodb.org/browse/MONGOSH-1670) for more details and examples.

fix(shell-api): the explainable cursor should reflect simple collation MONGOSH-1670

---

packages/browser-repl/src/components/shell.tsx
packages/browser-repl/src/index.spec.tsx

Totally skipped my mind that wrapping this into another component will break ref forwarding and so updating browser-repl to latest currently breaks Compass

fix(browser-repl): forward ref on the themed shell component

---

.evergreen.yml
.evergreen/evergreen.yml.in

No particular urgency attached to this, just got reminded that the server was looking into MacOS 14 support and figured there's no real reason for us not to test that platform, assuming that everything works out of the box. (If not, we'll see what to do about it, but it's probably a good time to learn about issues we might be running into)

chore(ci): add e2e and smoke tests for MacOS 14 MONGOSH-1834

---

package-lock.json
packages/cli-repl/package.json

Not necessarily required, but this is the min required version for electron / Compass, so we want mongosh to be on the same one

chore(deps): update win-export-cert-and-key to latest

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/replica-set.ts
packages/shell-api/src/shard.ts

This mirrors 949c2b5ee87, apart from applying corresponding changes to `_runAdminCommand()` instead of `_runCommand()`.

fix(shell-api): apply readPreference to admin read commands MONGOSH-1837

---

packages/shell-api/src/helpers.ts
packages/shell-api/src/shard.spec.ts

Show a full tag/chunk list when there are 20 or fewer items and cut a tag/chunk list when there are more than 20 items.

fix(shell-api): sh.status() should show full list of tag ranges in verbose mode only MONGOSH-1327

---

package-lock.json
packages/arg-parser/src/cli-options.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/constants.ts
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/i18n/src/locales/en_US.ts
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts

Depends on #2109, not logically but since there are a number of adjacent source locations being modified, there are quite a few conflicts otherwise, plus on https://github.com/mongodb-js/oidc-plugin/pull/194 for including the IdP server info

 feat: add debug flag for dumping OIDC tokens to output MONGOSH-1845 

---

package-lock.json
packages/arg-parser/package.json
packages/logging/package.json
packages/service-provider-server/package.json
packages/types/package.json

devtools-connect 3.2.8 uses mongodb-client-encryption v6.1.0

chore(deps): bump devtools-connect

---

packages/browser-repl/src/components/editor.spec.tsx
packages/browser-repl/src/components/editor.tsx
packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx

There is a slightly unexpected behavior in browser-repl right now where even though we don't allow user to type in shell input while operation is in progress, we don't disable the editor commands, and so it's still possible to run a command in parallel or choose a different input from history. Seems like this bug was there for awhile now, but we only noticed it now that we automatically run some commands in compass shell when opening a tab in certain contexts.

fix(browser-repl): ensure that input can't be modified or evaluated while operation is in progress COMPASS-8256

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

Adding a check on the connection info extra info to determine if the server is "local atlas" to conditionally skip calling the "startupWarnings" command when initializing the REPL.

chore(cli-repl): skip startup warnings for local atlas environments MONGOSH-1776

---

package-lock.json

This addressed a reported low-severity issue in `send`.

chore(deps): bump express to 4.21.0

---

packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-analytics.spec.ts
packages/e2e-tests/test/e2e-auth.spec.ts
packages/e2e-tests/test/e2e-aws.spec.ts
packages/e2e-tests/test/e2e-banners.spec.ts
packages/e2e-tests/test/e2e-bson.spec.ts
packages/e2e-tests/test/e2e-direct.spec.ts
packages/e2e-tests/test/e2e-editor.spec.ts
packages/e2e-tests/test/e2e-fle.spec.ts
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/e2e-tests/test/e2e-proxy.spec.ts
packages/e2e-tests/test/e2e-snapshot.spec.ts
packages/e2e-tests/test/e2e-snippet.spec.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/e2e-tests/test/e2e.spec.ts
packages/e2e-tests/test/test-shell-context.spec.ts
packages/e2e-tests/test/test-shell-context.ts
packages/e2e-tests/test/test-shell.spec.ts
packages/e2e-tests/test/test-shell.ts

I was experiencing the e2e tests hanging after exit, both when ran locally and on CI.
This refactor includes:
- A `startTestShell` method on the `Mocha.Context` to ensures a hook is setup to kill all open test shells. Instead of calling `TestShell.start` most hooks and tests can simply call `this.startTestShell` instead.
- A `ensureTestShellAfterHook` function exported from `test-shell-context.ts`, which tests can optionally call to register the "kill hook" to run before another hook they want to register (this is used only once in `e2e.spec.ts` to ensure a directory deletion handles after no shells are accessing it).
- A `TestShell.assertNoOpenShells` static method which will throw if there are any open test shells.
- Deletion of the existing `TestShell.runAndGetOutputWithoutErrors` …

chore(e2e-tests): refactor `TestShell` to ensure `killAll` gets called

---

scripts/docker/ubuntu24.04-deb.Dockerfile

The `unminimize` script is no longer part of Ubuntu 24.04 docker images, so we need to manually emulate its effects in order to be able to test the man page installation.

fix(scripts): account for `unminimize` being gone from ubuntu24.04 docker img

---

package-lock.json
package.json
packages/arg-parser/package.json
packages/cli-repl/package.json
packages/cli-repl/src/run.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/logging/package.json
packages/service-provider-server/package.json
packages/snippet-manager/package.json
packages/types/package.json
scripts/nodejs-patches/005-node-tls-allowpartialtrustchain-commit-1b3420274ea.patch

This should bring back startup performance to pre-2.3.1 levels.
Also pins kerberos to 2.1.0, since bumping it actually broke our Windows build.

fix(cli-repl): use tls allowPartialTrustChain flag MONGOSH-1878

---

package-lock.json
package.json

This is being reported as an issue by our vuln checker, although we are not affected by the vulnerability itself as mongosh does not use HTTP cookies in production code.

chore(deps): pin cookie to ^0.7.2

---

packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/shard.spec.ts

When the getShardDistribution command is invoked on a sharded time series collection, the output says that the collection is not actually sharded. If the user invokes the same command on the related bucket collection, it produces an incorrect output.
This PR fixes both.

fix(shell-api): Fix support for sharded time series collections with getShardDistribution MONGOSH-1447

---

packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/e2e-tests/test/test-shell.ts

When using TLS enabled with a Certificate that requires a password, the mongosh does not prompt for a passphrase automatically, failing with an error. This adds a password prompt for that case.

feat(cli-repl): Ask for tlsCertificateKeyFilePassword when it is needed MONGOSH-1730

---

package-lock.json

MONGOSH-1883
We already have an override for `cookie` in the package-json, but we still had one older cookie version in the package-lock which was making the vuln tickets keep creating. Bumping `express` brings in the new cookie minor so no more tickets created.

chore(deps): update express for cookie dep version MONGOSH-1883

---

packages/i18n/src/locales/en_US.ts

`db.collection.find.help()` or `db.collection.findOne.help()` will now return the following parameters: `query, projection, options`. `options` was missing before.

fix(i18n): Add missing options parameter for find and findOne MONGOSH-1697

---

packages/cli-repl/src/smoke-tests.ts

I just did what Maurizio suggested in a comment on the ticket.

chore(cli-repl): add a smoke test for require in non-repl mode MONGOSH-1741

---

packages/cli-repl/src/cli-repl.ts

After https://github.com/mongodb-js/mongosh/pull/2222, the https://github.com/mongodb-js/mongosh/pull/2219 workaround is no longer necessary.

fix(cli-repl): Revert workaround for depcheck for searchParams type

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

Running aggregate() on a database with a non-array pipeline will now run a single stage aggregation. This will make it consistent with `db.{collection}aggregate`  behavior so
```
db.aggregate({$listLocalSessions: {}}
```
is same as 
```
db.aggregate([{$listLocalSessions: {}}])
```

fix(shell-api): Add support for running aggregate database with a single stage MONGOSH-1868

---

packages/cli-repl/AUTHORS
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts

```
test> response = db.test.dropIndex({"a": 1});
MongoshInternalError: can't find index with key: { a: 1 }
test> console.info(response);
{
ok: 0,
errmsg: "can't find index with key: { a: 1 }",
code: 27,
codeName: 'IndexNotFound'
}
```
mongosh seems to throw the error here instead of the dropIndex request going to the server. Hence `response` variable doesn't end up being set.

fix(shell-api): mongosh should throw an error when trying to drop a non-primary index MONGOSH-1608

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

Looking into the documentation for both database and collection functions made me realize it'd be a lot clearer to align them completely. Instead of https://github.com/mongodb-js/mongosh/pull/2218 which would allow
```ts
db.aggregate({ $stage: 1 }, { options: true }) 
// => db.aggregate([{ $stage: 1 }], { options: true })
```
It'd be better to align with how `db.{collection}.aggregate` works i.e.
```ts
db.aggregate({ $stage: 1 }, { $stage2: true }) 
// => db.aggregate([{ $stage: 1 }, { $stage2: true })]);
```
This does mean if not using array, one cannot pass options but this is already the behavior of collection `aggregate` so it'd be best (and most intuitive) to keep it consistent.

fix(shell-api): Align database and collection aggregate functions MONGOSH-1868

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/stream-processor.ts
packages/shell-api/src/streams.spec.ts

This PR adds a stream processor `modify` method. It can be used to modify the definition of a stream processor.

feat(shell-api): add stream processor modify MONGOSH-1864

---

.github/workflows/homebrew.yml

Adds a homebrew smoke test to ensure we catch issues, such as the one reported in MONGOSH-1895 early.

chore(ci): add homebrew smoke test MONGOSH-1895

---

.evergreen/compile-artifact.sh

No change in semantics, but the environment variable is generally replacing the `-mmacosx-version-min` compiler flag, so let's specify both.
(We could raise the minimum as well at some point, but unless there's an actual reason to do so other than "we can" I'd just leave it as-is.)

chore(ci): set `MACOSX_DEPLOYMENT_TARGET`

---

.github/workflows/cron-tasks.yml
README.md
package-lock.json
packages/arg-parser/src/arg-mapper.spec.ts
packages/arg-parser/src/arg-mapper.ts
packages/arg-parser/src/cli-options.ts
packages/cli-repl/README.md
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/constants.ts
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/i18n/src/locales/en_US.ts
packages/mongosh/README.md
packages/service-provider-node-driver/package.json

Pulls in latest `oidc-plugin` and adds an `--oidcNoNonce` argument to the cli that allows users to return to the old behavior in case their auth provider doesn't handle requests with a nonce.

fix: include nonce in oidc request by default MONGOSH-1905

---

packages/shell-api/src/stream-processor.ts
packages/shell-api/src/streams.spec.ts

* Add an options parameter to the stream processor start, stop, and drop methods. We already do this for sample and stats methods.
* This allows Atlas Stream Processing to support features like STREAMS-872.

feat(shell-api): add options in stream processor start, stop, and drop MONGOSH-1920

---

.github/workflows/cron-tasks.yml
.github/workflows/update-node-js.yaml

Changes the workflow to update auto-generated files to directly push to main. This should eliminate the extra PR we open after every merge. The devtoolsbot user has been exempted from the PR requirement, so should be able to push directly to main. While this is not ideal, it's not less secure than what we previously had where the github actions bot would open a PR and then immediately merge it with no checks/approvals required.
If this works well, I'll copy it over to the other repos we manage.

chore: push auto-generated files directly instead of using PRs

---

.github/workflows/cron-tasks.yml
.github/workflows/update-node-js.yaml
package-lock.json

Realized the `npm ci` step was taking too long, so added the magic env variable. Additionally, does some minor clean up of the `update-node-js` workflow and bumps get-uri to 6.0.3 to remove some duplicated dependencies.

chore(ci): don't download chrome for cron tasks

---

.github/workflows/cron-tasks.yml

Follow up on https://github.com/mongodb-js/mongosh/pull/2280
- removes the `workflow_dispatch` trigger
- fixes the token persistence issue that would prevent the push from going through
- adds `[skip actions]` to the commit message to avoid running the workflow recursively

chore(ci): cleanup auto generated file workflow MONGOSH-1927

---

packages/e2e-tests/test/e2e-aws.spec.ts
packages/e2e-tests/test/test-shell.ts

This should hopefully address AWS auth test flakiness on s390x, where DNS queries can take multiple seconds each due to the host CI setup.
Example strace that indicates a 5 second delay for a DNS query: https://docs.google.com/document/d/1jWxKTZWma5nN5I3a9iTANnulzm_9GlLanEUbf9q9vh0/edit?tab=t.0

fix(e2e-tests): increase timeouts for AWS tests MONGOSH-1924

---

package-lock.json
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-oidc.spec.ts

Now that the driver has support for the Kubernetes OIDC workload integration, it's quite easy to add a test for OIDC workload usage with mongosh.

chore(e2e-tests): add workload OIDC test MONGOSH-1832

---

packages/e2e-tests/test/e2e.spec.ts

This test has been particularly flaky on macOS, so let's do the same thing that the preceding test does and account for the fact that the log file might not be flushed immediately before the output of the command is printed.

chore(e2e-tests): account for race condition in driver version log file test MONGOSH-1934

---

package-lock.json
packages/build/package.json

This commit updates the signing-utils package to the latest version because our Authenticode certificate has nearly expired and we need the latest package version in order to use the new one.

chore(deps): update signing-utils to latest DEVPROD-13200

---

.evergreen.yml
.evergreen/evergreen.yml.in

Introduces a test which always fails so we can be sure a Foliage ticket opens with this.

chore(ci): add an always failing test to check Foliage integration

---

.evergreen.yml
.evergreen/compile-artifact.sh
.evergreen/evergreen.yml.in
.evergreen/package-and-upload-artifact.sh
.evergreen/run-evergreen-release.sh
.evergreen/setup-env.sh

This turns out to be just unnecessary, at least according to trying this out in a patch build.

chore(ci): never download chromium in CI MONGOSH-1942

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

These errors have historically been very hard to debug, so adding stack traces unconditionally will hopefully improve this situation in the long term.

fix(cli-repl): improve debuggability of `mongosh not initialized yet`errors MONGOSH-1943

---

packages/cli-repl/src/cli-repl.ts

This is mostly just making code a bit more resilient against cases in which we would unintentionally call `.close()` twice.

chore(cli-repl): return a cached promise from `.close()` MONGOSH-1943

---

.evergreen.yml
.evergreen/evergreen.yml.in

We added an always failing test to cause Foliage to open tickets; we can remove this now.

chore(ci): remove the temporary always failing Foliage test

---

packages/cli-repl/src/run.ts

When running under `nyc` for coverage generation, the process's `process.exit()` internals get monkey-patched to give `nyc` the opportunity to write coverage data as part of that operation. However, for processes running under changed working directories, `nyc` may try to write to an incorrect directory, making the `fs.writeFile()` call fail with an exception, and so `process.exit()` may not actually stop the process.
This commit adds a `process.abort()` call to make that accounts for this situation, as well as improved debugging for it.

fix(cli-repl): account for possibility of `process.exit()` throwing under coverage MONGOSH-1943

---

packages/cli-repl/src/mongosh-repl.ts

(Depends on #2299 as the first commit here and on #2298 logically – without #2298, this just fails consistently now instead of flakily)
Previously, a task in our CI was flaky because it was running `exit\n` as literal input to the shell, expecting it to reliably make the shell exit.
`exit` as a command leads to the `MongoshRepl.onExit` function called, which then calls a) `.close()` and, indirectly, `repl.close()` on the Node.js REPL instance as well b) the `CliRepl.exit` function (and through that, indirectly, `process.exit()`).
However, closing the Node.js REPL instance makes it flush the history file to disk as a typically fast but asynchronous operation, and, after that, emit `exit` on the REPL; that in turn called `MongoshRepl.onExit` again (i.e. calling `MongoshRepl.onExit` leads to …

fix(cli-repl): only ever run MongoshRepl.onExit once MONGOSH-1943

---

.evergreen.yml
.evergreen/evergreen.yml.in

This just reduces operating costs by a bit, and the change is fairly straightforward.

chore(ci): move macos packaging tasks to arm runners MONGOSH-1915

---

packages/browser-repl/src/components/shell-output-line.tsx
packages/browser-repl/src/components/types/error-output.tsx

These changes are requested by design:
1. The light red background should remain the darker background.
2. The initial error declaration should be light red not dark red.
3. The first line of the error, and the initial text, should be white.
4. There should be a light red indent bar (in css, a left border) to the left of the stack.

fix(browser-repl): use an error background color that makes syntax highlighting legible COMPASS-8308

---

.evergreen.yml
.evergreen/evergreen.yml.in

Without this, CI loses information about prior runs of this task (including performance comparison information), so let's rename this back to the name it had before b0f8e403546a83702f.

chore(ci): rename `perf_tests` task back to `perf_tests_linux_x64`

---

.evergreen.yml
.evergreen/compile-artifact.sh
.evergreen/evergreen.yml.in
.evergreen/package-and-upload-artifact.sh
.evergreen/run-evergreen-release.sh
.evergreen/setup-env.sh

This reverts commit 5f5ea259b5d1dd086aaf6f0383e46bd3ee8def3f. (Clean revert without conflicts)
We do actually need this in macOS CI, this just happened to work a lot of the time because macOS hosts are static hosts and apparently an already-installed chromium persists on those.
In order to keep things simple and keep CI green, let's just revert this for now.

Revert "chore(ci): never download chromium in CI MONGOSH-1942 (#2295)"

---

.evergreen.yml
.evergreen/evergreen.yml.in

I just missed this in MONGOSH-1915 / 7c26c7a516bd3a4448.

chore(ci): move macos signature verification to arm64 MONGOSH-1915

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/publish-auxiliary-packages.yml

The attempt to do workspace-based installs already seemed to have led to some trickier than expected issues... So let's stick with the usual for now.

chore(release): use root npm install

---

packages/build/src/npm-packages/index.ts
packages/build/src/npm-packages/publish.spec.ts
packages/build/src/npm-packages/publish.ts
packages/build/src/publish-auxiliary.ts
packages/build/src/publish-mongosh.spec.ts
packages/build/src/publish-mongosh.ts
packages/build/src/release.ts

Some refactoring to make it different scenarios clearer and use a different function when just publishing auxiliary packages.
We should just be publishing to npm in this case (and let lerna push tags).

chore(release): use a different release process when publishing auxiliary packages

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/shell-api/src/shell-instance-state.ts

Best viewed as a whitespace-diff-disabled change, doesn't include
any functional work.
Our current autocomplete logic does not always wait for the collection
or database name caches to be filled, in case it takes longer than 200ms
to do so. By ensuring that the caches are filled before we run the test,
we get consistent results.
Collection and database names, as well as other completion items, can
mostly contain arbitrary characters with only a few exceptions.
Since some characters may mess with our REPL input, we should filter
those autocompletions out.

chore(cli-repl): clean up autocomplete implementation and fix flaky test MONGOSH-1908 MONGOSH-1960

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/check-pr-title.yml
.github/workflows/codeql.yml
.github/workflows/cron-tasks.yml
.github/workflows/homebrew.yml
.github/workflows/publish-auxiliary-packages.yml
.github/workflows/smoke-tests.yml
.github/workflows/update-node-js.yaml

Cleans up the CodeQL workflow and updates actions to latest

chore(ci): update CodeQL workflow MONGOSH-1994

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/cron-tasks.yml
.github/workflows/publish-auxiliary-packages.yml
.github/workflows/temp-push-auxiliary-tags.yml
.github/workflows/update-node-js.yaml
package.json
packages/build/package.json
packages/build/src/index.ts
packages/build/src/npm-packages/index.ts
packages/build/src/npm-packages/publish.spec.ts
packages/build/src/npm-packages/publish.ts
packages/build/src/npm-packages/push-tags.spec.ts
packages/build/src/npm-packages/push-tags.ts
packages/build/src/publish-auxiliary.ts
packages/build/src/publish-mongosh.spec.ts
packages/build/src/publish-mongosh.ts
packages/build/src/release.ts

lerna publish [doesn't automatically push tags](https://github.com/lerna/lerna/issues/2085) when using from-package so we have to create and push the tags manually.
This is different from releasing mongosh as it does its own tag push already (without `mongosh@` prefix): https://github.com/mongodb-js/mongosh/blob/e0a051c30f3198fccd6257c77d4bf243a0cd173f/packages/build/src/npm-packages/publish.ts#L59-L73

fix(ci): add publishing tags step when publishing auxiliary packages MONGOSH-1871

---

packages/cli-repl/src/format-output.spec.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/src/mongosh-repl.ts

Escape control characters in output strings if there's a reasonable chance that their are (partially) coming from the server side, instead of printing them directly. We keep printing them directly when it's reasonably possible that they are being used intentionally for output control, e.g. when coming from `print()` or `console.log()` statements.

fix(cli-repl): improve explicit display of special characters in output MONGOSH-1910

---

packages/build/src/npm-packages/bump.ts

bump-packages from monorepo-tools is looking for `chore(ci): bump packages` as the start of the commit to calculate the semver bump. The problem is that our commit message doesn't start with this - instead it's `chore(release): bump auxiliary packages`. This means that the next time we run it, we go back to the start of time and sure enough, we find some breaking: ... commit message and decide we need to bump major. Luckily there's a `LAST_BUMP_COMMIT_MESSAGE` we can use to set this, so this does that.

fix(ci): use the correct commit message when bumping packages MONGOSH-1871

---

packages/i18n/src/locales/en_US.ts

`full` is not an available value for this option.

fix(i18n): fix help text for `oidcDumpTokens`

---

.evergreen/setup-env.sh
package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/async-repl.spec.ts
packages/cli-repl/src/async-repl.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/line-by-line-input.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/repl-paste-support.spec.ts
packages/cli-repl/src/repl-paste-support.ts
packages/e2e-tests/test/e2e.spec.ts
packages/e2e-tests/test/test-shell.ts

Bracketed paste allows us to receive a copy-pasted piece of mongosh as a single block, rather than interpreting it line-by-line. For now, this requires some monkey-patching of Node.js internals, so a follow-up ticket will include work to upstream support for this into Node.js core.

feat(cli-repl): add support for bracketed paste in REPL MONGOSH-1909

---

packages/cli-repl/src/run.ts
scripts/nodejs-patches/006-windows-virtual-terminal-input-libuv-4688.patch

Split out into a separate piece because this adds a patch to libuv that has non-trivial downsides, as explained in the referenced PR. I'd assume that mitigating this through a `process.on('exit')` handler is sufficient and that we don't need to plan specifically for e.g. hard crashes of mongosh here, but I didn't want to merge this together with the original work in 4232a9847cd5d2486 but rather have it stand on its own (including for the simple reason that it's easier to revert if we decide that we have to).
Refs: https://github.com/libuv/libuv/pull/4688

fix(cli-repl): support bracketed paste on Windows MONGOSH-1999

---

packages/build/src/npm-packages/bump.spec.ts
packages/build/src/npm-packages/bump.ts
packages/build/src/npm-packages/index.ts
packages/build/src/publish-mongosh.spec.ts
packages/build/src/publish-mongosh.ts
packages/build/src/release.ts
packages/build/src/run-draft.spec.ts
packages/build/src/run-draft.ts

Draft release will bump mongosh + other packages and build a release but not persist
Publish release will also bump mongosh + other packages (there's an assumption that nothing happened between the draft => publish stage) and "persist" that in sense that it'll push a tag, and then we can make a PR to merge the tags' content into main.

fix(release): add a bump step to draft and publish stages

---

.evergreen.yml
.evergreen/compile-artifact.sh
.evergreen/evergreen.yml.in
packages/build/src/npm-packages/bump.spec.ts
packages/build/src/npm-packages/bump.ts

Beyond making sure the directory is bumped  when releasing, we also want to be sure we have our versions bumped when compiling artifacts.

fix(ci): add bump step to compile_ts and compile_artifact

---

packages/e2e-tests/test/e2e.spec.ts

`--version`, `version()` and `--build-info` all source their version information differently. It should be sufficient to include a test to verify that they all match, without having to rely on the specific dependency from the e2e-test package.json file (which is in line with the general idea that e2e tests should not actually depend on the specific shell implementation and only test externally visible behavior of that implementation).

fix(e2e-tests): make version test independent of package.json files

---

packages/build/src/npm-packages/push-tags.spec.ts
packages/build/src/npm-packages/push-tags.ts
packages/build/src/publish-auxiliary.ts
packages/build/src/publish-mongosh.ts

Noticed this will happen in dry mode and another bug with tags that will happen and should be prevented.

fix(ci): skip pushing tags on a dry run and push all tags on release

---

packages/build/src/npm-packages/publish.spec.ts
packages/build/src/npm-packages/push-tags.spec.ts

--follow-tags was replaced with --tags but the corresponding tests were not fully updated.

fix(ci): fix build tests for pushing tags

---

scripts/sort-workspaces.js

Packages that are otherwise missing are now included, since lerna treats `--no-since` differently from not specifying `--since` at all.

fix(scripts): drop `--no-since` from `lerna ls`

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts

When cleaning up the old log files, we won’t wait for those processes to finish to unblock the main process. We will log errors if MongoLogManager throws any.

feat(cli-repl): do not wait for log clean-up MONGOSH-1990

---

package-lock.json
packages/snippet-manager/package.json
packages/snippet-manager/src/snippet-manager.spec.ts
packages/snippet-manager/src/snippet-manager.ts

This aligns us with the validators we've standardized on in Compass, improves TypeScript integration, and reduces executable size by 564 kB and startup time by 1.5% (locally on an M3).

chore(snippet-manager): migrate from joi to zod MONGOSH-2010

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/types/src/index.ts

Adds ability to configure log location.

feat(cli-repl): add configuration to set log location MONGOSH-1983

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/types/src/index.spec.ts
packages/types/src/index.ts

Would be best to first review: https://github.com/mongodb-js/mongosh/pull/2326
Adds `logRetentionDays` configuration and related tests.

feat(cli-repl): add configuration to set log retention days MONGOSH-1984

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/types/src/index.spec.ts
packages/types/src/index.ts

Would be best to first review: https://github.com/mongodb-js/mongosh/pull/2349
Adds the configuration and related tests.

feat(cli-repl): add configuration to set max file count MONGOSH-1987

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/types/src/index.spec.ts
packages/types/src/index.ts

Adds `logCompressionEnabled` option and tests.

feat(cli-repl): add configuration to enable log compression MONGOSH-1986

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/decorators.ts
packages/shell-api/src/shell-api.ts
packages/shell-api/src/shell-instance-state.ts

When running the ShellApi `help` command, print the description for the ShellLog methods.

feat(logging): print help for the global log property MONGOSH-1995

---

package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e.spec.ts
packages/logging/package.json
packages/types/src/index.spec.ts
packages/types/src/index.ts

Requires https://github.com/mongodb-js/devtools-shared/pull/504 to be released.
Builds on top of https://github.com/mongodb-js/mongosh/pull/2354

feat(cli-repl): add configuration to set max log files size MONGOSH-1985

---

package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e.spec.ts
packages/logging/package.json

This helps differentiate mongosh logs from others in case those files get shared.

feat(cli-repl): use mongosh_ prefix for logs in custom locations MONGOSH-2012

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/e2e-tests/test/e2e.spec.ts
packages/i18n/src/locales/en_US.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts
packages/node-runtime-worker-thread/src/worker-thread-evaluation-listener.ts
packages/shell-api/src/shell-api.ts
packages/shell-api/src/shell-instance-state.ts
packages/shell-api/src/shell-log.ts
packages/types/src/index.ts

Implement the `log.getPath()` repl function that returns the log name that includes the current log location and log id.

feat: create mechanism to expose log path within the repl MONGOSH-1090

---

packages/e2e-tests/test/e2e.spec.ts
packages/shell-api/src/cursor.spec.ts
packages/shell-api/src/cursor.ts

Throw a custom exception when a user attempts to serialize a cursor, pointing them to the fact that they likely want to call `.toArray()` first.

feat(shell-api): throw for EJSON.serialize(cursor) MONGOSH-2002

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

feat(cli-repl): add history() command MONGOSH-2013

---

packages/e2e-tests/test/e2e.spec.ts

There seems to be flakiness in some of the recently introduced disableLogging tests, likely because the needed log doesn't appear in the file quick enough for us to capture it. This adds a `eventually` to the tests where we check for a new log entry after inputting a command so we can retry at a later time and minimize flakiness. This makes it consistent with other log file tests.

fix(tests): minimize flakiness of the disableLogging tests

---

.github/workflows/merge-release-tag.yml
packages/build/README.md

The new system requires us to manually merge into main. This automates it through a workflow.
It can also be triggered manually with a workflow dispatch.

chore(ci): add automatic merging of the release tag MONGOSH-2018

---

.evergreen.yml
.evergreen/download-crypt-shared-and-generate-sbom.sh

Silkbomb 2.0 introduces the augment command which will allow you to upload your sbom to be scanned by OSV and have an augmented SBOM returned with any vulnerabilities in a single step.
Let me know if I'm missing anything or if there is anything else that can be cleaned up or improved. Thanks!

chore(ci): update to silkbomb 2.0

---

packages/browser-repl/src/components/shell-output-line.tsx
packages/browser-repl/src/components/shell-output.tsx
packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx
packages/browser-repl/src/sandbox.tsx

By default we have maxOutputLines == 1000. Once you get to 1000 elements it starts to splice the output to only keep the last 1000. But then the same array index maps to a different output entry component. Which means all of them get re-rendered at once.
By adding a persistent key to each shell output entry react won't lose track of or think that the components completely changed.
As a reminder, sync-to-compass is your friend for testing this locally:
```
~/mongo/mongosh/packages/browser-repl/scripts % export COMPASS_HOME=/Users/leroux.bodenstein/mongo/compass
~/mongo/mongosh/packages/browser-repl/scripts % node sync-to-compass.js
```

fix: set a consistent key for output elements rather than using the array index MONGOSH-2021

---

packages/build/src/npm-packages/publish.ts

There seems to be a bug where lerna does not run prepublish topologically during the publish step, causing build errors. This ensures all packages are topologically compiled beforehand.
I tried different ways of forcing on `lerna`, including updating it, and could not come up with a better solution.
1. Get a clean repository of `mongosh` or cleanup the builds of i.e. `rm -rf packages/errors/lib`
2. Run `npm_config_dry_run=true npx lerna publish from-package --no-private --no-changelog --exact --yes --sort`
3. Some packages which depend on `@mongosh/errors` i.e. `@mongosh/service-provider-core` fail as their prepublish gets called before the `errors`. The `--sort` tag doesn't help.

fix(ci): run prepublish topologically to fix auxiliary publishing

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/publish-auxiliary-packages.yml
packages/build/src/npm-packages/bump.ts
packages/build/src/publish-mongosh.ts

Currently we bump packages with 2 different commit messages: 
`"chore(release): bump auxiliary packages"` during an auxiliary and
`"chore(release): bump packages"` during a mongosh release. 
The problem is the mono repo tools' bump looks for commits messages starting with `"..bump auxiliary packages"` and thus ignores already released changes if they were made during a mongosh release. 
To align this while also differentiating them for the purpose of the auxiliary publishing workflow, these commits will now both starts with `"chore(release): bump packages"` and instead have different ending "for mongosh release" or "for auxiliary release"

chore(ci): align package bump commits

---

.evergreen.yml
.evergreen/evergreen.yml.in

aba4ba16ae83b84 included the correct changes but in the wrong file (evergreen.yml instead of the template file), so 89762a550e9eb30f8cb1 undid those changes partially and our CI has been failing since then.
Applying these changes to the correct file should fix that.

fix(ci): apply Kondukto changes to evergreen template file

---

.evergreen/install-node-source.sh
.evergreen/setup-env.sh

gcc is not officially supported on macOS (per [Build Platform Support Tiers]( https://docs.google.com/document/d/1G7JioblpjLdi8WiJP2A7OaZfNBF7yZ6-yXSCEarU2Sg/edit?tab=t.0#heading=h.4itnffmo0xv8)) and would typically not be installed, which is why the scripts have worked previously. It appears that there was a rogue task that installed the linux toolchain on those macs and is currently being removed. Still, I think the changes in this PR make sense as a way to protect us against future incidents.

chore(ci): don't use gcc on macOS MONGOSH-2029

---

package-lock.json
packages/e2e-tests/package.json
packages/service-provider-node-driver/package.json

Pulls in the duplicate address fix, which we'll need to then release as part of the `service-provider-node-driver` package that vscode uses.

chore(deps): bump oidc-plugin package MONGOSH-2027

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/publish-auxiliary-packages.yml

This is a minor change that sets the `PUPPETEER_SKIP_DOWNLOAD` environment variable in `bump-auxiliary-packages.yml` as we don't really need chrome there. Additionally, it adds a description for the workflow and removes some redundant committing.

chore(ci): don't download chrome in bump-auxiliary-packages

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

Adds a `sh.moveRange` helper modeled after `sh.moveChunk`.

feat: add sh.moveRange helper MONGOSH-1926

---

packages/build/src/npm-packages/publish.spec.ts
packages/build/src/npm-packages/publish.ts

When releasing we try to push a tag to `vx.x.x`. This does not fit in our current flow where this is actually the tag which triggered the release job in the first place, so this tag will always already exist and always gets skipped. This removes this step completely as we instead rely on `mongosh@x.x.x` as the tag reference for the published update.

chore(ci): remove redundant version tag push

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

This adds the `sh.isConfigShardEnabled` helper for server versions 8.0 and above. It uses `listShards` and then looks for a shard with `_id: 'config'`.
Additionally, it adds the `sh.listShards` helper that calls the `listShards` admin command.

feat(shell-api): add sh.isConfigShardEnabled and listShards helpers MONGOSH-1919

---

.evergreen/verify-packaged-artifact.sh
packages/build/src/homebrew/publish-to-homebrew.spec.ts
packages/build/src/homebrew/publish-to-homebrew.ts
packages/build/src/homebrew/utils.spec.ts
packages/build/src/homebrew/utils.ts

This is related to MONGOSH-2059 where we published a homebrew formula with the incorrect sha. There doesn't seem to be anything wrong with the way we're doing these sha updates, so my best guess is that it's a case of incomplete/corrupted download from npm that caused us to compute the wrong sha256. This PR changes it so we use the `shasum` field from the npm API to validate the tarball integrity before publishing the formula to homebrew, as well as adds a retry mechanism to attempt to recover in case we download the wrong thing.

chore(releasing): validate tarball sha1 before publishing to homebrew MONGOSH-2059

---

package-lock.json

```
mongosh@ /Users/leroux.bodenstein/mongo/mongosh
├─┬ @mongosh/browser-repl@3.6.0 -> ./packages/browser-repl
│ └─┬ puppeteer@21.0.3
│   └─┬ @puppeteer/browsers@1.6.0
│     └── tar-fs@3.0.4
├─┬ @mongosh/build@3.3.1 -> ./packages/build
│ └── tar-fs@2.1.1
├─┬ @mongosh/service-provider-core@3.1.0 -> ./packages/service-provider-core
│ └─┬ mongodb-client-encryption@6.3.0
│   └─┬ prebuild-install@7.1.3
│     └── tar-fs@2.1.1 deduped
└─┬ @mongosh/service-provider-node-driver@3.6.0 -> ./packages/service-provider-node-driver
└─┬ kerberos@2.1.0
└─┬ prebuild-install@7.1.1
└── tar-fs@2.1.1 deduped
```

chore: bump tar-fs 2.1.1 to 2.1.2 MONGOSH-2126

---

packages/browser-repl/src/components/utils/inspect.ts
packages/service-provider-core/src/printable-bson.spec.ts
packages/service-provider-core/src/printable-bson.ts

Add friendlier support for displaying BSON binary vector types in mongosh by displaying them as reproducable Binary constructor calls.

feat(service-provider-core): support new BSON vector types in mongosh MONGOSH-1873

---

package-lock.json
packages/service-provider-node-driver/package.json

Bumping the missed dependency with latest `mongodb-client-encryption`.

chore(deps): bump mongodb-client-encryption COMPASS-8816

---

.evergreen.yml
.evergreen/compile-artifact.sh
.evergreen/evergreen.yml.in
.evergreen/package-and-upload-artifact.sh
.evergreen/run-evergreen-release.sh
.evergreen/tasks/unit-tests.js
packages/browser-repl/package.json
packages/build/src/npm-packages/bump.ts

Out of experiencing the pain of seeing what seemed to be potentially a 10 minute download and install of puppeteer each time during release, I became curious whether we're actually skipping things correctly. 
`PUPPETEER_SKIP_DOWNLOAD` only applies at a post-install script but in many places we set it after all dependencies have already been installed. This sets it at the install stage instead. Not sure whatever the issues were with https://github.com/mongodb-js/mongosh/pull/2311/ would come up here, seems all good so far.
Not super scientific but this leads to quicker execution on hosts which tend to not have the Chromium in their cache like RHEL:

chore(ci): skip chromium download for most tasks

---

packages/e2e-tests/test/e2e.spec.ts

Our logging retention e2e tests are flaky, most likely because we do not wait for the shell process to finish cleaning up files before checking their existence. This wraps them in eventually, allowing us to retry accordingly.

fix(e2e-tests): handle flakiness of logging retention tests MONGOSH-2050

---

.github/workflows/codeql.yml

This is needed for a bandaid fix for https://github.com/mongodb-js/mongosh/commit/eb9376b475937a7e7b16683a1028299aab75ff7e not having the CodeQL runs.

chore: add optional for manual CodeQL dispatch

---

.github/workflows/codeql.yml

Follow up from #2441 since an old branch cannot run it otherwise.

chore: add manual SHA setting to CodeQL action

---

packages/build/src/download-center/artifacts.ts
packages/build/src/download-center/config.ts

This commit adjusts our uploads to the new bucket to be private. Access to these buckets will come via CDN only, so it is unnecessarily to set ACLs.

feat(release): set acls to private for new uploads MONGOSH-2124

---

.evergreen.yml
.evergreen/evergreen.yml.in

This commit adjusts our Evergreen template to restore the functionality that was originally committed in 5af1c40bb9ed887f873fe19ce274fb96a6512e39 and reverted in 10a20d24491ff863ff7290e1ed4c4b4a7c545f07. Going forward, we should only sign Mac builds on PRs

chore(ci): only sign macnotary during PRs MONGOSH-2163

---

package-lock.json

Due to a [bug in npm](https://github.com/npm/cli/issues/6301) the integrity fields of some dependencies are missing when regenerating package-lock.json in presence of an existing node_modules

chore: fix missing fields in package-lock.json

---

README.md
packages/cli-repl/README.md
packages/cli-repl/src/constants.ts
packages/cli-repl/src/format-output.spec.ts
packages/i18n/src/locales/en_US.ts
packages/mongosh/README.md
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/field-level-encryption.ts
packages/shell-api/src/helpers.ts
packaging/LICENSE-crypt-library

While any links with the old URL structure will be redirected indefinitely, it would be good to update the links for consistency.

chore(docs): update docs URLs to use the new endpoint MONGOSH-1349

---

package-lock.json
packages/browser-runtime-core/src/open-context-runtime.ts
packages/cli-repl/package.json
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/repl-helpers.ts
packages/e2e-tests/test/e2e-snippet.spec.ts
packages/shell-api/package.json
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shell-instance-state.ts
packages/types/src/index.ts

This reverts commit 493993ec5ddb634a5d17095acff7212bd9a92a96. Startup performance appears to have regressed around ~15 percent.

Revert "feat: initial feature-flagged, new autocompleter MONGOSH-2036"

---

packages/logging/src/analytics-helpers.spec.ts
packages/logging/src/analytics-helpers.ts
packages/logging/src/logging-and-telemetry.spec.ts
packages/logging/src/logging-and-telemetry.ts

Our track function was misleadingly typed with regards to Segment SDK.
For device_id to actually be used by Segment we'd need it to be in `traits.device_id` in the identify function.
This ties our types closer to the Segment SDK and moves the device ID to traits instead.

chore(logging): move device_id into Segment identity traits MONGOSH-2234

---

package-lock.json
packages/logging/package.json
packages/logging/src/logging-and-telemetry.spec.ts
packages/logging/src/logging-and-telemetry.ts

This package is meant to minimize code replication and to make sure the approach we're taking with hashing is consistent and timeouts are automatically handled.
See https://github.com/mongodb-js/devtools-shared/pull/532

chore: switch to `@mongodb-js/device-id`

---

licenses.json

This package has a license file but no `license` specified in its package.json file.
Broken since c8941c12a9457e8029.

fix: provide license override for cli-table package MONGOSH-2248

---

packages/e2e-tests/test/e2e-auth.spec.ts

This recently started popping up in our macOS e2e tests.

fix(e2e-tests): add another kerberos error message MONGOSH-2252

---

packages/browser-repl/src/components/shell.tsx

COMPASS-9417
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#block
Previously it would scroll to the top of the input, which would be cumbersome when doing multi-line editing. With these changes we make sure it's in view, but won't scroll to the top if they're already in it.

fix(browser-repl): use block: nearest for scrollIntoView vertical alignment behavior COMPASS-9417

---

.github/workflows/merge-release-tag.yml

One of my guesses here is that `-rc...` pattern somehow messes with how GitHub does matching because of their usage of glob matching instead of actual regex. I'm not fully convinced by this but I can't find any other discrepancy here at the moment.
Using a wildcard after is [used in some GitHub projects](https://github.com/search?q=+%40%5B0-9%5D%2B.%5B0-9%5D%2B.%5B0-9%5D%2B*&type=code) so hopefully that will do the trick.

chore: automatic release tag merging

---

packages/shell-api/src/bulk.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/explainable.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/mql-types.ts
packages/shell-api/src/plan-cache.ts
packages/shell-api/src/shard.ts
packages/shell-api/src/stream-processor.ts
packages/shell-api/src/streams.ts

The idea is that these would be easy to find/replace in the autocompleter while being semantically better than what we have and not adding any complexity for TypeScript.

feat: use placeholder mql types MONGOSH-2333

---

packages/shell-api/api-extractor.json

This came up once I bundled `@mongodb-js/mongodb-ts-autocomplete`

chore: also bundle mongodb-schema and json-schema

---

.github/workflows/merge-release-tag.yml

Seems like regex matching syntax doesn't exist in conditions like this... So we have to keep it simple

chore(ci): use startsWith instead of regex match

---

packages/async-rewriter2/package.json
packages/autocomplete/package.json
packages/browser-repl/package.json
packages/browser-runtime-core/package.json
packages/browser-runtime-electron/package.json
packages/build/package.json
packages/cli-repl/package.json
packages/e2e-tests/package.json
packages/editor/package.json
packages/errors/package.json
packages/history/package.json
packages/i18n/package.json
packages/js-multiline-to-singleline/package.json
packages/logging/package.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package.json
packages/service-provider-node-driver/package.json
packages/shell-api/package.json
packages/shell-evaluator/package.json
packages/snippet-manager/package.json
packages/types/package.json

Noticed that we're not passing the `--fix` option to eslint correctly.

chore: pass --fix to the eslint command rather than npm

---

packages/build/src/homebrew/publish-to-homebrew.spec.ts
packages/build/src/homebrew/publish-to-homebrew.ts

Refs: https://github.com/Homebrew/homebrew-core/pull/228993

fix(build): create homebrew PRs against `main`

---

README.md
packages/arg-parser/src/cli-options.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

Added a flag (`skipStartupWarning`) to skip the server's startup warnings

feat: add skipStartupWarnings flag to skip warnings on demand MONGOSH-2371

---

packages/autocomplete/src/index.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/repl-helpers.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shell-api.spec.ts
packages/shell-api/src/shell-instance-state.ts
packages/types/src/index.ts

This is only relevant for the new autocompleter which is currently feature-flagged and only accessible if you run mongosh with the environment variable USE_NEW_AUTOCOMPLETE=true
Without it set we'll still read database and collection names like we've always done. With this set we'll just assume an empty collection/schema, so you won't see field names autocomplete.

feat: allow opting out of schema sampling with config disableSchemaSampling=true MONGOSH-2370

---

packages/build/src/npm-packages/publish.ts

Since GitHub Actions only runs create tag workflows when no more than 3 tags are created (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create), we will push the mongosh tag separately to ensure it triggers the merge tag workflow

chore(ci): push mongosh tag separately during release

---

.evergreen.yml
.evergreen/evergreen.yml.in

The perf.send command is no longer being maintained and will be decommissioned soon. Users can now submit performance data using the "raw_perf_results" end point provided by the performance-monitoring-api. This PR migrates the mongosh evergreen project over to that API.

fix(ci): replace perf.send command with new API end point for performance data submission DEVPROD-19866

---

packages/service-provider-core/src/writable.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts

Followed up from the driver update, tests to ensure the new sort option works.

chore(shell-api): add test and type updates for sort

---

packages/build/src/packaging/download-crypt-library.ts
packages/shell-api/src/integration.spec.ts

chore(tests): skip sort update and replace tests on API strict 

---

testing/test-vscode.sh

Right now, the VSCode test is failing in CI because the versions of `@mongodb-js/devtools-connect` mismatch. We can align them the same way we aligned the driver versions.
This does not turn the task green yet, but it is a necessary step (the next one would be adjusting the VSCode source code for the removal of the argument to `serviceProvider.close()` from c8e2697e).

chore(ci): partially fix vscode test

---

packages/i18n/src/locales/en_US.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

This resolves MONGOSH-2139 by adding an extra field - `allowMigrations` for each collection in `sh.status()`. Additionally, adds two helpers - `sh.enableMigrations(ns)` and `sh.disableMigrations(ns)` that internally call the `setAllowMigrations` admin command.

feat: add sharded migration helpers MONGOSH-2139
