packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx

Adds scroll to bottom when output is appended

MONGOSH-68: scroll to bottom when output is appended

---

packages/browser-repl/README.md
packages/browser-repl/src/components/shell.tsx

Add public interface info to the README

MONGOSH-73: [browser-repl]: Better docs and README

---

packages/cli-repl/src/format-output.ts
packages/i18n/src/locales/de_DE.js
packages/i18n/src/locales/en_US.js
packages/shell-api/src/shell-api.js
packages/shell-api/yaml/AggregationCursor.yaml
packages/shell-api/yaml/Collection.yaml
packages/shell-api/yaml/Cursor.yaml
packages/shell-api/yaml/Database.yaml
packages/shell-api/yaml/ReplicaSet.yaml
packages/shell-api/yaml/Shard.yaml
packages/shell-api/yaml/ShellApi.yaml

Formats method/command descriptions to inner help menus. 
Adds local for `shell-api.help` as top-level API translations.
It also sets up methods that a class can have in the top-level menu, so all of them are available and compiled and can be parsed by writer.

(Help!) I need some method descriptions

---

azure-pipelines.yml
packages/mapper/src/mapper.spec.ts
packages/mapper/src/mapper.ts

Fix `it` throwing with closed cursors

Fix mapper.it() throwing with closed cursors

---

package.json

Run precommit only on changed packages

chore: run precommit only on changed packages

---

package-lock.json
packages/mapper/package.json

add missing dep `"mongosh-async-rewriter": "file:../async-rewriter"` to mapper.

fix(mapper): add missing dep

---

package-lock.json
packages/i18n/src/locales/de_DE.js
packages/i18n/src/locales/en_US.js
packages/mapper/src/mapper.integration.spec.ts
packages/mapper/src/mapper.spec.ts
packages/mapper/src/mapper.ts
packages/service-provider-browser/src/stitch-service-provider-browser.ts
packages/service-provider-core/src/writable.ts
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/shell-api.js
packages/shell-api/src/shell-types.js
packages/shell-api/yaml/Collection.yaml

Implements collection.convertToCapped
- Add convertToCapped method to service-provider
- Add convertToCapped method to mapper
- Add convertToCapped method shell api
- Add help

feat: add collection.convertToCapped

---

packages/browser-runtime-electron/package.json
packages/browser-runtime-electron/src/electron-runtime.spec.ts

Add some tests to make sure commands can be run by the runtime

test(electron-runtime): test running commands

---

.evergreen.yml

MONGOSH-49: Move Build to Evergreen

---

packages/browser-runtime-core/package-lock.json
packages/browser-runtime-core/package.json

Packaging in vscode which pulls in the `browser-runtime-core` package was causing an error due to a missing dependency. I'm not quite sure if this is how dependencies are set up with the lerna set up - let me know if I should put them in a different way. But adding these 2 babel dependencies,  `@babel/generator` and `@babel/parser` seemed to fix the issue for us.
The code that requires the dependencies is here:
https://github.com/mongodb-js/mongosh/blob/master/packages/browser-runtime-core/src/interpreter/preprocessor/preprocessor.ts#L1
Here's the stack trace we saw:
```
[2020-03-26 10:56:05.435] [exthost] [error] Activating extension mongodb.mongodb-vscode failed due to an error:
[2020-03-26 10:56:05.436] [exthost] [error] Error: Cannot find module '@babel/generator'
Require stack:
- …
```

(fix): Add missing babel dependencies for browser-runtime-core preprocessor

---

packages/cli-repl/src/logger.ts
packages/i18n/src/locales/en_US.js
packages/mapper/src/mapper.integration.spec.ts
packages/mapper/src/mapper.spec.ts
packages/mapper/src/mapper.ts
packages/service-provider-browser/src/stitch-service-provider-browser.ts
packages/service-provider-core/src/writable.ts
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/service-provider-server/src/cli-service-provider.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/shell-api.js
packages/shell-api/src/shell-types.js
packages/shell-api/yaml/Collection.yaml

Changes:
- add dropIndexes to service provider
- add dropIndexes and dropIndex to mapper 
- add dropIndexes and dropIndex to shellApi 
- emit events in mapper

Collection drop index

---

packages/shell-api/src/shell-api-signatures.js
packages/shell-api/src/shell-api.js
packages/shell-api/yaml/AggregationCursor.yaml

Add `returnsPromise`, `__fluent` and returnType where appropriate for AggregationCursor.

AggregationCursor signatures

---

packages/mapper/src/mapper.spec.ts
packages/mapper/src/mapper.ts

feat: add show tables

---

package-lock.json
packages/async-rewriter/package-lock.json
packages/async-rewriter/package.json
packages/async-rewriter/src/async-writer-babel.spec.ts
packages/async-rewriter/src/async-writer-babel.ts
packages/async-rewriter/src/symbol-table.spec.ts
packages/async-rewriter/src/symbol-table.ts
packages/browser-repl/package-lock.json
packages/compass-shell/package-lock.json
packages/mapper/package-lock.json

Also includes fixes for assignment, destructured assignments

Add babel type annotations

---

packages/cli-repl/src/cli-repl.ts

Disables Telemetry greeting message after the first run.

MONGOSH-176: disable greeting message after the first run

---

config/karma.conf.base.js
packages/browser-repl/config/webpack.config.base.js
packages/browser-repl/package-lock.json
packages/browser-repl/package.json
packages/browser-repl/src/components/shell-output-line.tsx
packages/browser-repl/src/components/types/show-dbs-output.tsx
packages/browser-repl/testing/enzyme.ts
packages/browser-repl/tsconfig.json
packages/compass-shell/config/webpack.base.config.js
packages/service-provider-browser/package.json

Testing for Windows build errors.

Switch to TS loader instead of Babel [DNM]

---

config/eslintrc.base.js
packages/cli-repl/.eslintignore
packages/cli-repl/.eslintrc.js
packages/cli-repl/bin/mongosh.js
packages/cli-repl/package.json
packages/cli-repl/src/arg-mapper.ts
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/cli-options.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/clr.ts
packages/cli-repl/src/completer.spec.ts
packages/cli-repl/src/completer.ts
packages/cli-repl/src/connect-info.spec.ts
packages/cli-repl/src/connect-info.ts
packages/cli-repl/src/constants.ts
packages/cli-repl/src/format-output.spec.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/src/index.ts
packages/cli-repl/src/logger.ts
packages/cli-repl/src/uri-generator.spec.ts
packages/cli-repl/src/uri-generator.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/helpers.ts

Because lrlna keeps forgetting semi-colons.

add eslint to cli-repl

---

packages/mapper/src/mapper.integration.spec.ts
packages/mapper/src/mapper.spec.ts
packages/mapper/src/mapper.ts
packages/shell-api/src/shell-api.js
packages/shell-api/yaml/BulkWriteResult.yaml

Rename `ackowledged` to `acknowledged`.

fix: acknowledged typo in BulkWriteResult

---

packages/async-rewriter/src/async-writer-babel.ts

- fix for: https://github.com/mongodb-js/vscode/issues/91

fix: ignore babelrc and babel.config.js

---

packages/compass-shell/src/components/info-modal/info-modal.jsx

https://docs.mongodb.com/compass/beta/embedded-shell/

Update compass link for shell docs

---

packages/i18n/src/locales/en_US.js
packages/shell-api/src/aggregation-cursor.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/cursor.spec.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/decorators.ts
packages/shell-api/src/explainable-cursor.spec.ts
packages/shell-api/src/explainable.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/replica-set.spec.ts
packages/shell-api/src/result.spec.ts
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shell-api.spec.ts

- Adds help descriptions for results classes
- Adds tests for each shell API type help

help and help()

---

packages/cli-repl/src/completer.spec.ts
packages/cli-repl/src/completer.ts

Fixes autocomplete with --nodb version

if version is undefined, autocomplete everything

---

packages/i18n/src/locales/en_US.js
packages/i18n/src/missing-help.spec.ts
packages/i18n/tsconfig.json
packages/shell-api/src/cursor.ts

Adds a test reporting missing help.

test(i18n): add test for missing help

---

packages/i18n/src/locales/en_US.js
packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/enums.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/shell-api.ts

No integration tests because these commands cannot be verified simply by inspecting the DB.

MONGOSH-307 - Support remaining admin commands

---

package-lock.json
package.json
packages/java-shell/package-lock.json

Stores mongosh binary in /usr/bin when packaging for debian

fix(build): pkg-deb@1.1.1 store deb binary in /usr/bin

---

packages/service-provider-core/src/cursor.ts
packages/shell-api/src/cursor.spec.ts
packages/shell-api/src/cursor.ts

COMPASS-181 (2) - Remaining cursor methods

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts
packages/shell-api/src/helpers.ts

Some MongoDB newbies (cough cough) might not know what keys are
required or not, and just knowing that something is missing
might not be enough to figure out what’s required and what’s not. :)

chore: print name of missing key for required object keys

---

scripts/generate-homebrew-formula.js
scripts/publish-npm.js
scripts/utils.js

Create a PR in our homebrew tap automatically after the release publish succeeded.

Homebrew after successful publish

---

scripts/docker/ubuntu-homebrew.Dockerfile

Adds a dockerfile to help checking the homebrew formula.

homebrew dockerfile

---

packages/build/src/signable-compiler.ts

- Build Node.js in parallel
- Do not drop the nexe cache
- Target the latest Node.js 12 version
- Create a working executable.
Note that this is still pretty slow on the first run,
and creates rather large binaries.

fix: fix and speed up nexe build

---

packages/build/README.md
packages/build/examples/input.js
packages/build/package.json
packages/build/src/analytics.spec.ts
packages/build/src/analytics.ts
packages/build/src/barque.spec.ts
packages/build/src/barque.ts
packages/build/src/build-and-upload.spec.ts
packages/build/src/build-and-upload.ts
packages/build/src/compile-and-zip-executable.ts
packages/build/src/compile-exec.ts
packages/build/src/download-center.ts
packages/build/src/evergreen.ts
packages/build/src/execute-once.ts
packages/build/src/generate-input.ts
packages/build/src/macos-sign.ts
packages/build/src/publish.ts
packages/build/src/signable-compiler.ts
packages/build/src/tarball.spec.ts
packages/build/src/tarball.ts
packages/build/src/upload-to-download-center.ts

Add the build package to `npm run check` and fixes errors.

chore(build): add to check and fix errors

---

packages/shell-api/src/helpers.ts

I forgot this was in progress before merging the last pr, so making a new one.
I see there are a few other places in this method where we could parallelize, but I wanted to keep the changes minimal here since the code is mostly from the old shell and since we weren't also able to port the tests, I'm hesitant to change too much of the code without introducing new tests.

First go at parallelizing sh.status

---

packages/shell-api/src/aggregation-cursor.spec.ts
packages/shell-api/src/cursor.spec.ts

Set ReplPlatform for cursor tests

---

packages/i18n/src/locales/en_US.js
packages/shell-api/src/shard.spec.ts
packages/shell-api/src/shard.ts

Sometimes it's easier to make a new branch than rebasing

MONGOSH-367 - Chunk management methods [rebased]

---

packages/browser-repl/package.json
scripts/run-if-platform.js

See https://github.com/mongodb-js/mongosh/pull/385#discussion_r507564376

chore: try to run browser-repl tests in CI

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
packages/java-shell/src/test/kotlin/com/mongodb/mongosh/CursorTest.kt
packages/java-shell/src/test/kotlin/com/mongodb/mongosh/util.kt
packages/java-shell/src/test/resources/cursor/print.expected.txt
packages/java-shell/src/test/resources/cursor/print.js

All Java tests pass
None of ts code was touched

[java-shell] Implement console.log

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/AdminServiceProvider.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/ReadableServiceProvider.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt

All Java tests pass, no core code was touched

[java-shell] sync java service provider interfaces with shell-api

---

packages/compass-shell/.npmignore
packages/compass-shell/scripts/download-akzidenz.js

Updates the script added in https://github.com/mongodb-js/mongosh/pull/407
We tweak now how we publish with this script.

fix(compass-shell): update font download script

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts

Refactor `setup-logger-and-telemetry.ts` towards more dependency
inversion so that it’s testable and then test it.

chore(cli-repl): test setup-logger-and-telemetry.ts MONGOSH-437

---

packages/cli-repl/src/cli-repl.ts

This basically 1:1 duplicates the functionality in [shell-internal-state.ts#L168-L172](https://github.com/mongodb-js/mongosh/blob/5093dc50a1528e1b5fde11ff16f18625beec2953/packages/shell-api/src/shell-internal-state.ts#L168-L172).

chore(cli-repl): remove duplicate code

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts
packages/cli-repl/src/types.ts
packages/cli-repl/test/repl-helpers.ts
packages/history/src/index.ts
packages/history/src/redact-pwd.ts
packages/shell-api/src/index.ts
packages/shell-api/src/mongo.ts
packages/shell-api/src/shell-internal-state.ts

Split the CliRepl class into one part that is not concerned with
external I/O and one part that is. Add unit tests to cover them both.

chore(cli-repl): split CliRepl and test it MONGOSH-441

---

packages/i18n/src/locales/en_US.ts
packages/i18n/src/missing-help.spec.ts
packages/shell-api/src/bulk.ts

Making the locale files into typescript broke the tests, which meant that we added a few API methods without descriptions.

Fix Help tests and add missing descriptions

---

packages/cli-repl/test/e2e.spec.ts
packages/java-shell/src/test/resources/collection/uniqueIndex.expected.1.txt
packages/java-shell/src/test/resources/collection/updateManyPipeline.expected.1.txt
packages/java-shell/src/test/resources/collection/updateOnePipeline.expected.1.txt
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/replica-set.spec.ts
packages/shell-api/src/replica-set.ts
packages/shell-api/src/shard.spec.ts
testing/download-mongodb.ts
testing/integration-testing-hooks.ts

Make tests pass for all of the target server versions.

fix(test): allow running tests with mongod 4.0, 4.2, 4.4 MONGOSH-312

---

packages/cli-repl/test/e2e-auth.spec.ts
packages/cli-repl/test/e2e-bson.spec.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/test-shell.ts

This replaces the `~/.mongodb/mongosh` section of the manual
testing matrix.

chore(test): add home dir e2e tests MONGOSH-413

---

packages/cli-repl/src/line-by-line-input.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/fixtures/exampleplayground.js

Handle the `'end'` event correctly by adding it to the queue of pending
characters if appropriate. Otherwise, the stream would have ended too
early, with potentially pending characters still in the `charQueue`.

fix(cli-repl): fix piping into mongosh (really) MONGOSH-401

---

packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/repl-helpers.ts
packages/cli-repl/test/test-shell.ts

This replaces the REPL/Eval sections of the manual testing matrix.
Resolves:
- MONGOSH-414
- MONGOSH-415

chore(test): add more REPL/evaluation tests MONGOSH-414

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts
packages/shell-api/src/mongo.ts

add topology to watch metadata

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts
packages/cli-repl/test/e2e.spec.ts
packages/service-provider-server/src/cli-service-provider.ts

This was suggested in Slack and is straightforward enough to add.

chore(cli-repl): include driver metadata in logfile

---

packages/autocomplete/index.spec.ts
packages/autocomplete/index.ts
packages/browser-runtime-core/src/autocompleter/shell-api-autocompleter.spec.ts
packages/browser-runtime-core/src/autocompleter/shell-api-autocompleter.ts
packages/browser-runtime-core/src/open-context-runtime.ts
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/service-provider-core/src/all-transport-types.ts
packages/service-provider-core/src/connect-info.ts
packages/service-provider-core/src/index.ts
packages/shell-api/src/shell-internal-state.ts

Include topology and server features in autocompletion criteria.

feat(autocomplete): make completion connection-type-aware MONGOSH-148

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

Adds the behavior of the old shell back again that printed any server startup warnings that can be retrieved using `db.adminCommand({ getLog: 'startupWarnings' })`.
No logs are tried to be retrieved or printed when `--nodb` is specified.
Implement resiliently to not crash if any unexpected results come back or getting the logs fails. These cases will be logged to the mongosh log file, however.

fix(cli-repl): print server startup warnings when starting shell MONGOSH-460

---

packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

This is for feature parity with the old shell,
see https://docs.mongodb.com/manual/release-notes/4.4/#db-auth-can-prompt-for-password
Part of MONGOSH-463 (mongodb 4.4 features).

fix(shell-api): allow db.auth with implicit prompt

---

packages/service-provider-server/src/cli-service-provider.ts

See https://jira.mongodb.org/browse/NODE-2931

chore(service-provider-server) remove returnNonCachedInstance option

---

packages/service-provider-core/src/all-transport-types.ts
packages/shell-api/src/bulk.spec.ts
packages/shell-api/src/bulk.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/integration.spec.ts

See https://jira.mongodb.org/browse/NODE-2768.

chore(shell-api): remove dependency on bulk op driver internals

---

package-lock.json
package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/shell-api/src/aggregation-cursor.ts
packages/shell-api/src/change-stream-cursor.spec.ts
packages/shell-api/src/change-stream-cursor.ts
packages/shell-api/src/cursor.ts
packages/shell-api/src/helpers.ts

See https://github.com/mongodb/node-mongodb-native/compare/2c03b782...634ae4f9.

chore(deps): bump mongodb to 634ae4f9

---

packages/shell-api/src/session.spec.ts

Didn't put a big amount of thoughts here since deleting the tests is also a possible solution.
Anyway .. I've skipped them on windows, where it seems to fail most of the times (4.0 server in windows), from a 'client' perspective that should be fine, since there is no platform specific behaviour in the shell+driver stack, while there could be a significant difference for the server.
Also I'm now running each test case with a different client and a different database, to make sure one execution is not influencing the other (for example conflicting on a lock acquired on the previous execution and still unreleased).
I think we can give this a try and if it doesn't help we delete everything.

chore: stabilize flaky integration tests with transactions MONGOSH-480

---

package-lock.json
package.json
packages/cli-repl/package-lock.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json

This should unblock MONGOSH-322 and MONGOSH-452.
See https://github.com/mongodb/node-mongodb-native/compare/634ae4f9...16c15749.

chore(deps): bump mongodb to 16c15749

---

packages/cli-repl/test/e2e-bson.spec.ts
packages/i18n/src/locales/en_US.ts
packages/service-provider-core/src/admin.ts
packages/service-provider-core/src/printable-bson.ts
packages/service-provider-core/src/service-provider.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/shell-bson.ts

`any` strikes again :)
Make sure that the necessary method used by `bsonsize` is
always available.

fix(service-provider-server): fix bsonsize MONGOSH-517

---

packages/cli-repl/src/async-repl.spec.ts
packages/cli-repl/src/async-repl.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

For multi-line input, rewrite the REPL history so that only one entry
is present per evaluated code. This commit merges the item into a
single-line by joining the individual lines with spaces, because
the REPL history file uses newlines as separators between entries.
Collapsing into a single line also matches the old shell’s behavior.
In order to achieve this, the async-repl module starts exposing hooks
that allow observing the success/failure of evaluations, and in
particular whether failures are recoverable (i.e. lead to multiline
input prompts).

feat(cli-repl): merge multiline input into one history item MONGOSH-336

---

packages/java-shell/src/test/resources/collection/aggregateWithNegativeBatchSize.expected.2.txt

Example failure:
https://evergreen.mongodb.com/task_log_raw/mongosh_linux_test_mlatest_n14_patch_bd68988e6eee153b965b9660d333ac2c8247b6ac_5ff822797742ae57f3742c30_21_01_08_09_14_35/0?type=T

fix(java-shell): make sure tests pass against latest server version

---

packages/node-runtime-worker-thread/package.json
packages/node-runtime-worker-thread/src/child-process-proxy.ts
packages/node-runtime-worker-thread/src/index.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts

Some regression issues came up after merging #533 to master

fix(node-runtime-worker-thread): Update package versions and add getShellPrompt method

---

package-lock.json
package.json
packages/cli-repl/src/arg-mapper.spec.ts
packages/cli-repl/src/arg-mapper.ts
packages/cli-repl/test/e2e-analytics.spec.ts
packages/cli-repl/test/e2e-auth.spec.ts
packages/cli-repl/test/e2e-bson.spec.ts
packages/cli-repl/test/e2e-direct.spec.ts
packages/cli-repl/test/e2e-tls.spec.ts
packages/cli-repl/test/e2e.spec.ts
packages/compass-shell/electron/renderer/index.js
packages/java-shell/.gitignore
packages/java-shell/package-lock.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-core/src/connection-string.spec.ts
packages/service-provider-core/src/connection-string.ts
packages/service-provider-core/src/index.ts
packages/service-provider-core/src/uri-generator.spec.ts
packages/service-provider-core/src/uri-generator.ts
packages/service-provider-core/src/whatwg-url.spec.ts
packages/service-provider-core/src/whatwg-url.ts
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/service-provider-server/src/index.ts
packages/shell-api/src/integration.spec.ts
testing/integration-testing-hooks.ts

Fixes MONGOSH-418.
See https://github.com/mongodb/node-mongodb-native/compare/16c15749...b1bdb06c.
---
feat(service-provider-core): add ConnectionString class MONGOSH-528
Add a ConnectionString class for easier URI manipulation.

chore(deps): bump mongodb to b1bdb06c

---

package-lock.json
package.json
packages/node-runtime-worker-thread/package-lock.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/shell-api/src/aggregation-cursor.ts

See https://github.com/mongodb/node-mongodb-native/compare/b1bdb06c...85d8d097.

chore(deps): bump mongodb to 85d8d097

---

package-lock.json
package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts

See https://github.com/mongodb/node-mongodb-native/compare/85d8d097...62717a1d

chore(deps): bump mongodb to 62717a1d

---

.evergreen-tags.yml

Just to see if the restructuring would work at all...

Restructure evergreen config MONGOSH-505

---

packages/shell-api/src/field-level-encryption.ts

This is the tiny 2-liner to throw an error if FLE is not available but someone tries to use `ClientEncryption`.
I cannot add a test for that since the `stubInterface<ServiceProvider>()` proxy will ignore `null | undefined` as values and just return a function stub......

chore(shell-api): throw error if FLE is not available MONGOSH-514

---

packages/build/package-lock.json
packages/build/package.json
packages/build/src/npm-packages.ts

The windows build fails as it cannot run `lerna` (does not find the executable file).

chore(build): use cross-spawn for lerna MONGOSH-505

---

.evergreen.yml
.evergreen/test-package-win32.sh
packages/cli-repl/src/arg-parser.ts
packages/cli-repl/src/index.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/smoke-tests.spec.ts
packages/cli-repl/src/smoke-tests.ts

We can use this to expand the test suite more easily in the future.

chore(cli-repl): add --smokeTests option MONGOSH-506

---

.evergreen/.install_node
.evergreen/InstallNode.ps1

Refs: https://twitter.com/addaleax/status/1347909082829750273

fix(ci): use npm@6

---

packages/build/src/npm-packages.spec.ts
packages/build/src/npm-packages.ts

fix(build): ignore errors from assume-unchanged MONGOSH-521

---

packages/service-provider-server/src/cli-service-provider.ts

`buildInfo` cannot be sent over a connection where automatic encryption
is enabled. Fall back to an unencrypted connection in that case.
This can be reverted once
https://jira.mongodb.org/browse/MONGOCRYPT-308 is done.

fix(service-provider-server): fix getConnectionInfo for FLE connection

---

.evergreen.yml

This is a follow-up to #612 where I forgot to trigger the release tasks.

chore(build): actually run release tasks MONGOSH-554

---

packages/compass-shell/package.json
packages/compass-shell/src/modules/adapt-driver-v36-connection-params.js
packages/compass-shell/src/modules/adapt-driver-v36-connection-params.spec.js
packages/compass-shell/src/modules/runtime.js

I hope we will be dropping these hacks really soon.

fix: allow kerberos connections in embedded shell COMPASS-4613

---

packages/shell-api/src/shell-api.spec.ts

This gives us a teeny tiny bit more coverage.

chore(shell-api): add test for shell API aliases

---

packages/cli-repl/src/arg-mapper.ts
packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/field-level-encryption.spec.ts
testing/fake-kms.ts

Also add a test that this works in the Shell API.
(Draft because this includes #647 until that’s merged)

feat(cli-repl): add awsSessionToken support MONGOSH-524

---

packages/build/src/github-repo.spec.ts
packages/build/src/github-repo.ts

Easier than thought - getting a release by tag already returns the uploaded assets with it (see https://docs.github.com/en/rest/reference/repos#get-a-release-by-tag-name - default response example).

fix(build): update github release assets properly MONGOSH-606

---

packages/build/src/github-repo.spec.ts
packages/build/src/github-repo.ts

Updating an asset does not work with a PATCH call - only the
name of an asset and other properties can be updated that
way, not the binary itself.

chore(build): ensure to remove a GitHub asset before re-uploading

---

packages/compass-shell/src/components/info-modal/info-model.spec.js

We don't run them on CI so when I broke this one in one of the previous PRs I completely missed it 😅

fix: Update assertion to match info modal

---

packages/cli-repl/test/e2e-auth.spec.ts

This deviates slightly from the tech design in that it doesn’t
spin up new servers, but instead specifies the required auth
mechanism when creating the users (and adding consistency checks
that verify that those auth mechanisms are actually required by
the server), in order to avoid the relatively costly spawning
of server instances and re-use more of the existing auth test code.

chore(cli-repl): add SCRAM-SHA-1/256 integration tests

---

packages/shell-api/src/mongo.ts

https://jira.mongodb.org/browse/MONGOSH-568

chore(shell-api): Show matching deprecation messages for deprecated read pref methods MONGOSH-568

---

packages/service-provider-core/src/writable.ts
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts

Following up to the changes from b098674ea74 as suggested by @gribnoysup in https://github.com/mongodb-js/mongosh/pull/720#pullrequestreview-614289439

fix(shell-api): follow-up findAndModify changes

---

packages/shell-api/src/collection.spec.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts

feat(shell-api): make dropIndexes() argument optional MONGOSH-580

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts
packages/shell-api/src/shell-api.spec.ts
packages/shell-api/src/shell-api.ts
packages/types/src/index.ts

chore(cli-repl): add telemetry for loading JS files MONGOSH-627

---

package-lock.json
package.json
packages/build/package-lock.json
packages/build/package.json
packages/service-provider-server/package-lock.json
packages/shell-api/src/collection.ts
packages/shell-api/src/integration.spec.ts
testing/integration-testing-hooks.ts

The legacy shell does not modify the object being inserted and does not add _id to this object. Keep the mongosh behavior compatible with the legacy shell behavior.

MONGOSH-607: insert should not add id to users object

---

.evergreen.yml
packages/cli-repl/test/e2e-auth.spec.ts
packages/cli-repl/test/e2e-aws.spec.ts
packages/cli-repl/test/e2e-tls.spec.ts
packages/cli-repl/test/helpers.ts
packages/cli-repl/test/test-shell.ts

WIP due to the blocked AWS setup required for testing and specifying the required environment variables.

chore(cli-repl): add E2E tests for AWS authentication MONGOSH-578

---

packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts

It's just a nit but I noticed it and tipped me... :D 
**Before**
**After**

chore(cli-repl): align initial messages

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts

Add a KeyVault integration test, and a hopefully temporary
workaround for NODE-3118.

chore(cli-repl): add KeyVault integration test

---

packages/connectivity-tests/test/atlas.sh

chore(connectivity-tests): adjust log file name check MONGOSH-714

---

packages/browser-repl/src/components/types/error-output.tsx
packages/cli-repl/src/format-output.spec.ts
packages/cli-repl/src/format-output.ts
packages/cli-repl/test/e2e.spec.ts
packages/i18n/src/locales/en_US.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts

feat(cli-repl,browser-repl): display err.errInfo/err.result if present MONGOSH-584

---

packages/browser-repl/src/components/shell.spec.tsx
packages/browser-repl/src/components/shell.tsx
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts

feat(cli-repl,browser-repl): support custom prompts MONGOSH-516

---

.evergreen.yml

chore(ci): use temporary Windows distro to help build team debug

---

.evergreen/package-and-upload-artifact.sh
config/build.conf.js
packages/build/src/config/config.ts
packages/build/src/packaging/msi-sign.spec.ts
packages/build/src/packaging/msi-sign.ts
packages/build/src/packaging/run-package.ts

This requires the secrets for the notary service to be set up in Evergreen to fully work.

chore(build): add signing of MSI installer MONGOSH-567

---

package-lock.json
package.json
packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/mongosh-repl.spec.ts

Fixes MONGOSH-691 and MONGOSH-734.

fix(cli-repl): bump pretty-repl to 3.0.0

---

packages/build/src/download-center/config.spec.ts
packages/build/src/download-center/config.ts
packages/build/src/packaging/package/get-package-file.spec.ts

We should wait with merging this until #793 has been merged.

chore(build): publish MSI to download center MONGOSH-566

---

package-lock.json
packages/cli-repl/package-lock.json
packages/cli-repl/package.json

Bumps `pretty-repl` to https://github.com/mongodb-js/pretty-repl/releases/tag/v3.0.2

fix(cli-repl): improve syntax highlighting on input MONGOSH-726

---

packages/cli-repl/src/mongosh-repl.spec.ts
packages/cli-repl/src/mongosh-repl.ts
packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
packages/node-runtime-worker-thread/src/child-process-proxy.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts
packages/shell-api/src/shell-api.spec.ts
packages/shell-api/src/shell-api.ts
packages/types/package.json
packages/types/src/index.spec.ts
packages/types/src/index.ts

Created together with @rose-m :)

feat: add stricter type validation for config settings MONGOSH-758

---

packages/cli-repl/README.md
packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
packages/cli-repl/src/setup-logger-and-telemetry.ts
packages/types/src/index.ts

A bunch of other test failures seem to correlate on connectivity issues of the underlying host machines / environment...

test(cli-repl): fix flaky test and improve event documentation MONGOSH-761

---

.github/workflows/cron-tasks.yml
packages/async-rewriter2/src/error-codes.ts
packages/errors/package.json
packages/errors/scripts/error-overview.tmpl.rst
packages/errors/scripts/extract-errors.ts

~Waiting for final generated structure approval by Jeff...~

chore: automatically generate errors documentation MONGOSH-787

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/service-provider-server/src/cli-service-provider.ts

Whitespace-adjusted diff for your (re)viewing pleasure: https://github.com/mongodb-js/mongosh/pull/901/files?w=1

fix(service-provider-server): allow FLE with --apiStrict MONGOSH-789

---

packages/shell-api/src/collection.ts
packages/shell-api/src/explainable.spec.ts
packages/shell-api/src/explainable.ts
packages/shell-api/src/integration.spec.ts

This PR includes some additional typing fixes.

fix(shell-api): allow Explainable.aggregate to take individual stages MONGOSH-790

---

packages/shell-api/src/integration.spec.ts

… and a DBQuery getter test for which I could not be bothered to create a new commit + PR

chore(shell-api): add interrupt/resume integration test

---

packages/browser-repl/src/components/shell-output-line.spec.tsx
packages/browser-repl/src/components/types/show-collections-output.less
packages/browser-repl/src/components/types/show-collections-output.spec.tsx
packages/browser-repl/src/components/types/show-collections-output.tsx
packages/browser-repl/src/index.stories.tsx
packages/cli-repl/src/format-output.ts
packages/shell-api/src/database.spec.ts
packages/shell-api/src/database.ts

fix(cli-repl,browser-repl): sort collection names and mark system collections MONGOSH-782

---

packages/build/src/homebrew/generate-formula.spec.ts
packages/build/src/homebrew/generate-formula.ts
packages/build/src/homebrew/publish-to-homebrew.spec.ts
packages/build/src/homebrew/publish-to-homebrew.ts
packages/build/src/homebrew/update-homebrew-fork.spec.ts
packages/build/src/homebrew/update-homebrew-fork.ts
packages/build/src/release.ts
packages/build/src/run-publish.spec.ts
packages/build/src/run-publish.ts

The fork is also already created so we can create PRs to `homebrew/homebrew-core`.

chore(build): publish new mongosh versions to homebrew/homebrew-core MONGOSH-807

---

packages/cli-repl/src/cli-repl.ts

chore(cli-repl): improve error message for mongocryptd failure MONGOSH-799

---

packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.ts

Mention that `tls=` needs to be explicitly specified when passed
to `new Mongo()`/`connect()`, because unlike in the legacy shell,
that setting is not inherited. This is only printed for connection
attempts from a shell that was started with TLS enabled using
connection strings that do not contain a TLS flag which encounter
ServerSelectionTimeout errors.

chore(shell-api): mention --tls for connect errors MONGOSH-814

---

packages/cli-repl/test/e2e-direct.spec.ts

Wasn’t quite sure where to put the test, but this doesn’t feel too
wrong at least.

chore(cli-repl): test `$merge` + `readPreference=secondary` MONGOSH-812

---

packages/shell-api/src/database.ts

fix(shell-api): fix rotateCertificates implementation

---

packages/cli-repl/test/e2e-auth.spec.ts

See https://evergreen.mongodb.com/task/mongosh_darwin_test_m50xe_n12_d201e37cbe4f627a07a4754d56d6a63f83fd9fb7_21_06_15_21_06_57

fix(test): handle another potential kerberos message

---

.evergreen.yml
.evergreen/test-package-win32.sh
packages/build/src/packaging/package/tarball.spec.ts

See also Evergreen Patch: https://spruce.mongodb.com/version/60cb50243e8e862718eedaff/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

test(build): fix test failure introduced on windows

---

package-lock.json
package.json

Did another pass of `npm audit fix` in the root directory. Also upgrades `lerna` to v4.

chore: fix npm audit issues

---

.evergreen.yml

chore(ci): add debug command to macos pkg tests

---

.evergreen.yml
package-lock.json
package.json
packages/cli-repl/test/e2e-auth.spec.ts
packages/cli-repl/test/e2e-direct.spec.ts
packages/cli-repl/test/e2e.spec.ts
packages/cli-repl/test/test-shell.ts
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.integration.spec.ts
packages/shell-api/src/collection.spec.ts
packages/shell-api/src/explainable.spec.ts
packages/shell-api/src/field-level-encryption.spec.ts
packages/shell-api/src/field-level-encryption.ts
packages/shell-api/src/helpers.ts
packages/shell-api/src/integration.spec.ts
packages/shell-api/src/mongo.spec.ts
packages/shell-api/src/shard.spec.ts

chore: bump driver to -beta.6/fle addon to 1.2.6 + follow-up changes

---

packages/connectivity-tests/test/all.sh
packages/connectivity-tests/test/kerberos.sh
packages/connectivity-tests/test/kerberos/Dockerfile
packages/connectivity-tests/test/kerberos/docker-compose.kerberos.yaml
packages/connectivity-tests/test/kerberos/kerberos-run.sh
packages/connectivity-tests/test/kerberos/krb5.conf

This should have https://github.com/mongodb-js/devtools-docker-test-envs/pull/9 merged before and the commit hash should then be updated.

chore(test): add E2E connectivity tests for Kerberos MONGOSH-837

---

packages/shell-api/src/shell-internal-state.spec.ts
packages/shell-api/src/shell-internal-state.ts

chore(shell-api): display Atlas in default prompt when connected to Atlas MONGOSH-879

---

.evergreen.yml
package-lock.json
package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts

Add a driver version that supports LB mode, and a hack to work around
existing known issues.

feat: add minimum changes for LB support

---

packages/async-rewriter2/src/stages/transform-maybe-await.ts

There might be more to improve here, but these seemed like two
instances of low-hanging fruit where we could improve performance
a bit by skipping full subtrees instead of re-visiting them again.

chore(async-rewriter2): skip subtrees where possible

---

packages/cli-repl/src/cli-repl.ts

Also verified to test with Kerberos on Windows.

fix(cli-repl): do not require password for GSSAPI authentication MONGOSH-899

---

packages/shell-api/src/database.ts

Return both actual and configured log size and scale their
values properly.
As a drive-by fix, this also makes some unrelated cosmetic/performance
improvements to `getReplicationInfo()`.

fix(shell-api): return replset oplog sizes properly MONGOSH-968

---

package-lock.json
package.json
packages/java-shell/src/main/js/all.js
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/snippet-manager/package-lock.json
packages/snippet-manager/package.json

- mongodb@4.1.2
- mongodb-client-encryption@1.2.7
- kerberos@1.1.7
- bson@4.5.2

chore: bump various driver dependencies

---

packages/browser-runtime-core/src/open-context-runtime.ts

fix(browser-runtime-core): do not call fetchConnectionInfo excessively

---

packages/cli-repl/test/e2e-editor.spec.ts
packages/editor/src/editor.spec.ts

Bring the unit test coverage for the editor package up.

test(editor): bring test coverage up MONGOSH-1014

---

package-lock.json
package.json
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/snippet-manager/package-lock.json
packages/snippet-manager/package.json

Bump the driver to 4.1.4 and bson to 4.5.4.

chore: bump driver and bson versions MONGOSH-1048

---

packages/cli-repl/src/cli-repl.ts
packages/snippet-manager/src/snippet-manager.ts

chore: skip fetching snippet index if not entering interactive mode 

---

package-lock.json
package.json

This hopefully resolves flakiness on the Win32 compile task.

chore(deps): bump boxednode to 1.10.3 MONGOSH-1039

---

packages/build/src/packaging/index.ts
packages/build/src/packaging/notary-service.spec.ts
packages/build/src/packaging/notary-service.ts
packages/build/src/packaging/run-package.ts
packages/build/src/run-draft.spec.ts
packages/build/src/run-draft.ts
packages/build/test/helpers.ts

chore(build): create and upload .sig files for download artifacts 

---

package-lock.json
package.json
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/snippet-manager/package-lock.json
packages/snippet-manager/package.json

chore(deps): bump driver to 4.3.0

---

packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json

This also resolves MONGOSH-1059.

chore(deps): bump kerberos to 2.0.0

---

packages/java-shell/build.gradle
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellEvaluator.kt

GraalJS library 22.0.0.2 + two fixes so the code works with the new library version

Update GraalJS library

---

packages/java-shell/build.gradle
packages/java-shell/cli/build.gradle
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellEvaluator.kt

feat(java-shell): allow passing Engine to MongoShell to enable code caching

---

packages/java-shell/src/test/kotlin/com/mongodb/mongosh/CollectionTest.kt
packages/java-shell/src/test/resources/collection/findAndModifyWithNew.expected.txt
packages/java-shell/src/test/resources/collection/findAndModifyWithNew.js
packages/shell-api/src/helpers.ts

https://youtrack.jetbrains.com/issue/DBE-15415

feat(java-shell): fix findAndModify with `new` option

---

packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/optionConverters.kt
packages/java-shell/src/test/kotlin/com/mongodb/mongosh/DbTest.kt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.1.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.2.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.expected.txt
packages/java-shell/src/test/resources/db/createCollectionWithTimeseries.js

https://youtrack.jetbrains.com/issue/DBE-14915

feat(java-shell): support create timeseries collection

---

.evergreen.yml
.evergreen/evergreen.yml.in

fix(ci): run e2e tests on suse12-sp5-small rather than suse12-small

---

packages/shell-api/src/integration.spec.ts

I was sloppy in d535086deecf9d80 and should have reduced this further
so that the tests actually pass.

fix(shell-api): further relax PlanCache integration test MONGOSH-1192

---

package-lock.json
package.json
packages/arg-parser/package-lock.json
packages/cli-repl/test/e2e-fle.spec.ts
packages/logging/package-lock.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/collection.ts
packages/shell-api/src/helpers.ts
packages/types/package-lock.json

This also means dropping the FLE2 feature flag.

chore(deps): bump driver to 4.6.0 MONGOSH-1217

---

packages/build/src/barque.spec.ts
packages/build/src/barque.ts

Curator cannot yet upload artifacts for Debian 11.

fix(build): temporarily remove debian11 publishing

---

packages/cli-repl/test/e2e-fle.spec.ts

Was writing a (very similar) script as a bug repro anyway,
so I figured I might as well add it as an e2e test. :)

chore(cli-repl): add explicit QE e2e test

---

packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
packages/node-runtime-worker-thread/src/rpc.ts
packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
packages/node-runtime-worker-thread/src/worker-runtime.ts

in mongosh:
```
npx lerna run prepublish
```
in compass:
```
cp -r ../mongosh/packages/node-runtime-worker-thread/dist/**/* ./node_modules/@mongosh/node-runtime-worker-thread/dist
```
then start compass:

fix: serialize onPrint params before sending over RPC COMPASS-5767

---

package-lock.json
package.json
packages/arg-parser/package-lock.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/shell-api/src/field-level-encryption.spec.ts
packages/types/package-lock.json

(and mongodb-client-encryption to 2.2.0-alpha.5)

chore(deps): bump driver to 4.8.1

---

.evergreen.yml
.evergreen/evergreen.yml.in
.evergreen/package-and-upload-artifact.sh
.evergreen/setup-env.sh

[Context](https://jira.mongodb.org/browse/BUILD-12985)

chore(ci): switch Windows unit tests to windows-vsCurrent-small

---

package-lock.json
package.json
packages/arg-parser/package-lock.json
packages/arg-parser/package.json
packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/history/package-lock.json
packages/history/package.json
packages/logging/package-lock.json
packages/logging/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/types/package-lock.json
packages/types/package.json

Also bump mongodb-connection-string-url to include COMPASS-5958.

chore(deps): bump driver to 4.10.0 MONGOSH-1299

---

packages/cli-repl/test/e2e-fle.spec.ts
packages/shell-api/src/database.ts

This was [suggested on Slack](https://mongodb.slack.com/archives/CDM9QEGUT/p1670337966031059) and seemed easy enough to implement.

chore(shell-api): improve error message for QE createCollection on old server MONGOSH-1337

---

package-lock.json
package.json
packages/arg-parser/package-lock.json
packages/arg-parser/package.json
packages/cli-repl/package-lock.json
packages/cli-repl/package.json
packages/history/package-lock.json
packages/history/package.json
packages/logging/package-lock.json
packages/logging/package.json
packages/node-runtime-worker-thread/package-lock.json
packages/node-runtime-worker-thread/package.json
packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json
packages/service-provider-server/package-lock.json
packages/service-provider-server/package.json
packages/snippet-manager/package-lock.json
packages/snippet-manager/package.json
packages/types/package-lock.json
packages/types/package.json

- `mongodb` to 4.13.0
- `mongodb-connection-string-url` to 2.6.0
- `bson` to 4.7.1
- `mongodb-client-encryption` to 2.3.0

chore(deps): bump driver dependencies MONGOSH-1355

---

packages/service-provider-core/package-lock.json
packages/service-provider-core/package.json

chore(telemetry): bump mongodb-build-info for expanded isLocalhost check COMPASS-5420

---

.evergreen/test-node-driver.sh
package.json

This PR updates the node driver CI related package.json scripts.  
https://github.com/mongodb/node-mongodb-native/pull/3546 is a companion PR in the driver.

chore: adjust node driver npm scripts NODE-5012

---

.evergreen.yml
.evergreen/evergreen.yml.in
packages/cli-repl/src/run.ts
packages/connectivity-tests/test/localhost.sh

See the ticket, this is necessary to avoid connectivity issues when using Node.js 17+, which homebrew is doing for us.

fix(cli-repl): call net.setDefaultAutoSelectFamily(true) MONGOSH-1378

---

.evergreen.yml
.evergreen/evergreen.yml.in

https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/

chore: bump node.js versions to latest 14.x/16.x

---

packages/browser-repl/src/components/password-prompt.tsx
packages/browser-repl/src/components/shell.tsx

fix(browser-repl): changes background color of shell to dark4

---

.evergreen.yml
.evergreen/evergreen.yml.in
.github/workflows/cron-tasks.yml
.gitignore
THIRD_PARTY_NOTICES.md
licenses.json
package-lock.json
package.json
packages/cli-repl/package.json
packages/cli-repl/webpack.config.js

Integrate tasks to generate vulnerability reports and 3rd party licenses

chore: integrate sbom-tools MONGOSH-1450, MONGOSH-1451

---

.evergreen.yml
.evergreen/evergreen.yml.in

update node from 16.19.1 to 16.20.0

chore: update node from 16.19.1 to 16.20.0 MONGOSH-1454

---

.github/workflows/cron-tasks.yml

chore: move Github Actions cron tasks to merge pr MONGOSH-1525

---

.github/workflows/cron-tasks.yml

aligns this with Compass, seems that the open PR step doesn't like to work on a detached head

chore: align file generation task with compass

---

config/mongosh-versions.json
packages/build/src/download-center/config.ts
scripts/gather-existing-releases.mjs

Should finally be all good then. :)

fix(build): fix sharedOpenssl tag for downloads MONGOSH-1242

---

packages/cli-repl/src/cli-repl.spec.ts
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/mongosh-repl.ts
packages/cli-repl/src/update-notification-manager.spec.ts
packages/cli-repl/src/update-notification-manager.ts
packages/cli-repl/test/e2e.spec.ts
packages/logging/src/setup-logger-and-telemetry.ts
packages/types/src/index.ts

[Should be ready as far as everything is concerned, but leaving as draft so that we can first release mongosh with the JSON feed]

feat(cli-repl): show update notification banner in mongosh CLI MONGOSH-1533

---

config/release-package-matrix.d.ts
config/release-package-matrix.js
package-lock.json
packages/build/package.json
packages/build/src/config/build-variant.ts
packages/build/src/download-center/config.spec.ts
packages/build/src/download-center/config.ts
packages/build/src/packaging/package/get-package-file.ts

Reverts mongodb-js/mongosh#1609
We need to wait for the web-team to confirm that these changes are correct.

Revert "chore: group download center packages by platform MONGOSH-1346"

---

package-lock.json
package.json
packages/cli-repl/src/mongosh-repl.ts
packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
packages/types/src/index.ts

A leftover from the typescript/eslint/prettier config changes.

chore: attempt at better typescript MONGOSH-1506

---

.evergreen.yml
.evergreen/evergreen.yml.in
packages/e2e-tests/test/e2e-oidc.spec.ts

This is probably something I missed in 684002ce003a.

fix(ci): properly test against enterprise servers

---

package-lock.json
packages/errors/package.json

Noticed these were included in the `nodeModules` of VSCode.

chore(errors): move deps to dev deps

---

packages/async-rewriter2/src/async-writer-babel.spec.ts
packages/async-rewriter2/src/error-codes.ts
packages/async-rewriter2/src/stages/transform-maybe-await.ts
packages/e2e-tests/test/e2e.spec.ts
packages/shell-api/src/abstract-cursor.ts
packages/shell-api/src/change-stream-cursor.ts

feat(async-rewriter): allow cursor iteration with for-of MONGOSH-1527

---

.snyk

Same as https://github.com/mongodb-js/compass/commit/5e0f57dd302ef5eabbd37620486555acb6882e34

chore: ignore SNYK-JS-AXIOS-6032459 MONGOSH-1626

---

scripts/docker/suse12-rpm.Dockerfile

This has been failing in CI a lot recently

fix(ci): attempt to fix suse12 package smoke test MONGOSH-1645

---

.gitignore
config/webpack.base.config.js
package-lock.json
package.json
packages/build/package.json
packages/build/src/compile/signable-compiler.ts
packages/cli-repl/package.json
packages/cli-repl/src/run.ts
packages/cli-repl/src/startup-timing.ts
packages/cli-repl/webpack.config.js
scripts/nodejs-patches/003-nodejs-node-pr-50453-e54ddf898f6c.patch

This involves adding nodejs/node@e54ddf898f6c as a (cleanly applying) patch but otherwise seems to work just fine.

chore: re-enable startup snapshot support MONGOSH-1605

---

package-lock.json
packages/arg-parser/package.json
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/e2e-tests/test/fixtures/curl.mjs
packages/e2e-tests/test/repl-helpers.ts
packages/logging/package.json
packages/service-provider-server/package.json
packages/types/package.json

Requires https://github.com/mongodb-js/devtools-shared/pull/261

feat(deps): allow applying `useSystemCA` to OIDC IdP MONGOSH-1712

---

.evergreen.yml
.evergreen/evergreen.yml.in

Disabling this task until we get this fixed with MONGOSH-1740

chore(ci): disables test_vscode task

---

package-lock.json

`npm i tar@latest && git checkout -- package.json && npm i`

chore(deps): bump tar to latest MONGOSH-1744

---

package-lock.json

`npm i express@4.x && git checkout -- package.json && npm i`

chore(deps): bump express to 4.19.2 MONGOSH-1749

---

package-lock.json
packages/editor/package.json

Bump `js-beautify` that is used by the mongosh editor in production.

fix(editor): SNYK-JS-INFLIGHT-6095116 inflight MONGOSH-1732

---

packages/build/src/run-download-and-list-artifacts.ts

Obvious bug in 2da3c3159545e348f411d77e321f6ada7d170b85 :)

fix(build): ensure output directory exists before downloading files into it

---

packages/shell-api/src/collection.ts
packages/shell-api/src/database.ts

chore(shell-api): fix linting errors on main

---

package-lock.json
packages/history/package.json
packages/logging/package.json
packages/shell-api/package.json

Bump mongodb-redact with regexes improvements.

fix(deps): mongodb-redact contains slow regexes MONGOSH-1392

---

README.md
config/webpack.base.config.js
package-lock.json
packages/arg-parser/package.json
packages/arg-parser/src/arg-mapper.ts
packages/arg-parser/src/cli-options.ts
packages/cli-repl/README.md
packages/cli-repl/package.json
packages/cli-repl/src/constants.ts
packages/cli-repl/src/run.ts
packages/cli-repl/src/tls-certificate-selector.spec.ts
packages/cli-repl/src/tls-certificate-selector.ts
packages/cli-repl/webpack.config.js
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/e2e-tests/test/e2e-snapshot.spec.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/i18n/src/locales/en_US.ts
packages/logging/package.json
packages/mongosh/README.md
packages/node-runtime-worker-thread/package.json
packages/service-provider-server/package.json
packages/service-provider-server/src/cli-service-provider.ts
packages/shell-api/src/mongo.ts
packages/types/package.json

Enable tlsUseSystemCA by default.

feat: enable tlsUseSystemCA by default MONGOSH-1852

---

README.md
config/build.conf.js
docs/index.md
packages/i18n/src/locales/en_US.ts

https://jira.mongodb.org/browse/MONGOSH-1593

chore(docs, i18n): update docs link MONGOSH-1593

---

package-lock.json
packages/arg-parser/package.json
packages/cli-repl/.depcheckrc
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.ts
packages/cli-repl/src/run.ts
packages/e2e-tests/package.json
packages/e2e-tests/test/e2e-oidc.spec.ts
packages/e2e-tests/test/e2e-proxy.spec.ts
packages/e2e-tests/test/e2e-snapshot.spec.ts
packages/e2e-tests/test/e2e-tls.spec.ts
packages/e2e-tests/test/oidc-helpers.ts
packages/e2e-tests/test/repl-helpers.ts
packages/e2e-tests/test/test-shell.ts
packages/logging/package.json
packages/service-provider-server/package.json
packages/types/package.json

This PR mostly just adds tests on top of the work done in devtools-shared.
https://github.com/mongodb-js/devtools-shared/pull/451 is required for this to pass

feat: add proxy support MONGOSH-1827

---

packages/cli-repl/.depcheckrc
packages/cli-repl/src/pac-proxy-s390x-patch.ts
packages/cli-repl/src/run.ts
packages/e2e-tests/test/e2e-snapshot.spec.ts

Work around https://github.com/justjake/quickjs-emscripten/issues/123.

fix(cli-repl): patch WASM wrapper for pac-proxy-agent on s390x MONGOSH-1858

---

packages/i18n/src/locales/en_US.ts

db.createView.help() was returning createCollection instead of createView

fix(i18n): Fix incorrect createView.help MONGOSH-1867

---

packages/browser-repl/src/components/types/error-output.tsx

Missed in 0919d39412e32d1710c5423efa62e4da606c49cf.

fix(browser-repl): fix linting error

---

.github/workflows/bump-auxiliary-packages.yml
.github/workflows/publish-auxiliary-packages.yml
package-lock.json
packages/build/package.json

Fixes some uncaught issues from before and some quick quality of life improvements.

chore(ci): fix issues with bumping and publishing workflows

---

package-lock.json
packages/cli-repl/package.json
packages/cli-repl/src/cli-repl.ts
packages/logging/package.json

Includes a version bump and adjustments for the breaking change from the latest major release.
Related to https://github.com/mongodb-js/devtools-shared/pull/498

chore(deps): bump mongodb-log-writer MONGOSH-1992

---

.evergreen.yml
.evergreen/evergreen.yml.in

Bump was only added to `check` step originally.

fix(ci): correct bumping in compile_ts

---

.evergreen.yml
.evergreen/evergreen.yml.in

#2345 does not work on Windows

fix(ci): include bumped package.json in compile-ts tarball

---

package-lock.json
packages/build/package.json

Refs: https://github.com/mongodb-js/devtools-github-repo/pull/8

chore(deps): bump devtools-github-repo to 1.4.2

---

scripts/nodejs-patches/006-windows-virtual-terminal-input-libuv-4688.patch

Update the patch to the commit merged into libuv and add a small Node.js source modification that will need to go into an upcoming Node.js release in order for the patch to take effect.
Refs: https://github.com/libuv/libuv/commit/843b64faf5fbbd19c04475bafa38c0c91514efb8

chore(deps): update patch for bracketed paste on Windows MONGOSH-1999

---

packages/build/src/homebrew/utils.ts

chore(build): run reformat MONGOSH-2122

---

packages/connectivity-tests/test/all.sh

https://github.com/mongodb-js/devtools-docker-test-envs/pull/35
This should fix the connectivity tests.

chore: use newer docker test envs

---

packages/shell-api/src/field-level-encryption.spec.ts

chore(shell-api): fix linter MONGOSH-2426
