- packages/cli-repl/src/cli-repl.ts
Adds a repl function to add a history file to save command history. **Does not** include omitting sensitive info just yet -- stay tuned for next PR.
> COMPASS-52: use repl.setupHistory given a mongosh_repl_history file

- packages/browser-repl/src/lib/interpreter/interpreter.spec.ts
- packages/browser-repl/src/lib/interpreter/preprocessor/preprocessor.ts
- packages/browser-repl/src/lib/interpreter/preprocessor/transform-command-invocation.spec.ts
- packages/browser-repl/src/lib/interpreter/preprocessor/transform-command-invocation.ts
- packages/browser-repl/src/lib/runtime-helpers/setup-evaluation-context.ts
Allows to run commands like 'use', 'it', 'show' and 'help'.
NOTES:
- the `show` command does not seem to be available in shell api.
- Would be nice to have a more robust parsing for commands.
- The output of the commands is currently rendered as "stringified" string with quotes. We need the object model for commands in order to fix that.
> MONGOSH-72: implement commands

- packages/cli-repl/package.json
- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/cli-options.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/history.spec.ts
- packages/cli-repl/src/history.ts
- packages/cli-repl/src/index.ts
This PR adds a flag to redact information in user's command history using [mongodb-redact](https://github.com/mongodb-js/redact) module. This is based on a flag(`--redactInfo`) when user starts the shell. The default for this flag is `false` to keep it compatible with the current shell. 
This PR also automatically removes user management commands from history (entirely). 
Example of starting shell without `--redactInfo`:
Example of starting shell with `--redactInfo`:
Any other commands I should be omitting? I just copied the ones from [this line in current mongodb shell](https://github.com/mongodb/mongo/blob/master/src/mongo/shell/dbshell.cpp#L308).
Thanks! ✨
> shell can redact and omit sensitive info, as a treat

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/constants.ts
- packages/cli-repl/src/format-output.ts
Callback on `this.evaluate` was catching and printing recoverable errors that happen when you type in multiline input. This PR removes the catch, and lets original node eval deal with multiline, and just pass on the result over to `writer` and then `formatOutput`.
> fix multiline input

- packages/cli-repl/bin/mongosh.js
```
2020-03-02T16:17:52.684+0000 I  NETWORK  [conn438] received client metadata from 172.17.0.1:45714 conn438: { driver: { name: "nodejs", version: "3.5.4" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "18.7.0" }, platform: "'Node.js v12.14.1, LE (unified)", application: { name: "mongosh 0.0.0" } }
```
> feat(cli-repl): add name and version to metadata

- packages/transport-server/src/node-cursor.spec.ts
- packages/transport-server/src/node-cursor.ts
fixes isExhausted as cursor.hasNext returns a promise.
> fix(transport-server): async cursor.hasNext

- package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/completer.spec.ts
- packages/cli-repl/src/completer.ts
Preloads autocompletions from `[ace-autocompleter](https://github.com/mongodb-js/ace-autocompleter)` for all collection and aggergation queries. 
I am feeling this module is getting a bit unruly, and getting quite hacky with all the `.pop()`s, `.split()`s and `.trim()`s.
I think in the future (maybe after mongodb world), we can consider writing a parser to have a PT with a bit of context to give the necessary information for more accurate suggestions. This would also allow for queries that look like this, that are currently not possible to autocomplete:
```js
var cat = "Nori"; db.cats.aggregate([ {$mat
```
> MONGOSH-105: add autocompletions for find and aggregation queries

- packages/async-rewriter/local-test.js
- packages/async-rewriter/src/async-writer-babel.ts
- packages/async-rewriter/src/index.ts
- packages/async-rewriter/src/symbol-table.ts
- packages/cli-repl/src/cli-repl.ts
- packages/mapper/src/mapper.ts
NOTE: this doesn't include any implementation changes, only changing the packge to return a class instead of a function.
This is my suggestion for what the async writer API should look like. The major change is that the mapper doesn't have to construct the SymbolTable separately, it's initialized and stored within the AsyncWriter class. So to use from the mapper:
```
import { types } from 'shell-api'; // this will be an argument when the context object PR is merged
const globalScope = { db: types.Database };
const writer = new AsyncWriter(globalScope, types); // initialize
const rewrittenCode = writer.compile('code'); // use
```
The `globalScope` argument is the set of global variables (like `db`) and their types. The `types` argument is the ShellApi types from `shell-api-types` and is …
> Fix up async-writer api

- azure-pipelines.yml
Temporary fix for missing tarball in CDN.
For now we run tests against mongo 4.2.3. The latest version will be used in evergreen.
```
curl -I https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-4.2.4.tgz
HTTP/2 403 
content-type: application/xml
date: Tue, 17 Mar 2020 13:16:54 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 b46ec6462593127fefb6ecac53956825.cloudfront.net (CloudFront)
x-amz-cf-pop: TXL52-C1
x-amz-cf-id: Ox-wXEgEUPp3-VAaSjFUa1fgxNEaj0kwT898aEkAaHVjy8GlvX1ryA==
```
> chore: fix missing mongodb tarball for test runner

- package-lock.json
- packages/mapper/package.json
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/bulk-write-result.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/BulkWriteResult.yaml
Implement `BulkWriteResult` and fixes typing issues encountered while doing so.
Changes:
- fix a typo in shell api yaml for `BulkWriteResult`
- add `BulkWriteResult` to `service-provider-core` to establish the `bulkWrite` interface the implementations has to conform to (is the node.js driver one)
- map `BulkWriteResult` in the mapper to the expected result for shell bulkWrite
- add missing typings for `listDatabases`, `isCapped`, `remove` so it compiles
> feat: BulkWriteResult

- packages/browser-runtime-core/src/open-context-runtime.ts
- packages/cli-repl/src/cli-repl.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
Moves the code that assign the ShellApi methods and attributes to the global context to the `setCtx` method of `Mapper`.
The code was present in 2 forms in both `browser-repl` and `cli-repl`.
Is that the right place to factor it?
NOTES:
1. `new ShellApi()` is moved in the `setCtx` of mapper too.
2. We run the commands directly from the context, is that ok?
3. If we keep this do we have to expose shell api? like `mapper.shellApi`?
> refactor: unify set ctx code and move to mapper

- packages/i18n/src/locales/de_DE.js
- packages/i18n/src/locales/en_US.js
- packages/mapper/package-lock.json
- packages/mapper/package.json
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/src/shell-types.js
- packages/shell-api/yaml/Collection.yaml
Implements `db.coll.createIndex` and `db.coll.createIndexes`.
Changes:
- service provider: Implement `createIndexes` and `getIndexes` (used in mapper for tests)
- mapper: Implement `createIndexes` and `createIndex` as wrapper of `createIndexes` (as is currenly).  
- shell api: Add  `createIndexes` and `createIndex` specs and help
Chores:
- Use `ts-sinon` in mapper tests to mock the `ServiceProvider` interface.
> feat: add createIndex and createIndexes

- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/src/shell-types.js
- packages/shell-api/yaml/Collection.yaml
NOTE:
The previous implementation wraps `createIndex` and changes the output:
When `writeMode` is `legacy` it returns: nothing in case of success, and `getLastErrorObj()` if  there was an error.
Since the documentation does not mention anything about that, I just did an alias to `createIndex`. Added a note in jira about that.
This is the old code:
```
> db.coll.ensureIndex
function(keys, options) {
var result = this.createIndex(keys, options);
if (this.getMongo().writeMode() != "legacy") {
return result;
}
err = this.getDB().getLastErrorObj();
if (err.err) {
return err;
}
// nothing returned on success
}
```
> feat: ensureIndex

- config/karma.conf.base.js
- packages/async-rewriter/package.json
- packages/browser-repl/config/karma.conf.js
- packages/browser-runtime-core/package.json
- packages/browser-runtime-electron/package.json
- packages/cli-repl/package.json
- packages/compass-shell/karma.conf.js
- packages/history/package.json
- packages/i18n/package.json
- packages/mapper/package.json
- packages/service-provider-server/package.json
- packages/shell-api/package.json
Use longer timeout for mocha to prevent tests with slow setup from failing.
> chore: add timeout to mocha

- packages/cli-repl/package.json
we were using an older version of minimist that has a bit of a bug with
prototype pollution, it [was fixed in](https://github.com/substack/minimist/commit/4cf1354839cb972e38496d35e12f806eea92c11f) and we should update.
> update minimist to latest - 1.2.5

- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/src/shell-types.js
- packages/shell-api/yaml/Collection.yaml
- Implement collection.getIndexes,
- Implement collection.getIndexSpecs (alias to getIndexes)
- Implement collection.getIndexKeys
- Implement collection.getIndices (alias to getIndexes)
```
$ mongosh > db.coll1.getIndexes()
[
{ v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.coll1' },
{ v: 2, key: { y: 1 }, name: 'y_1', ns: 'test.coll1' },
{ v: 2, key: { z: 1 }, name: 'bla', ns: 'test.coll1' },
{ v: 2, key: { k: 1 }, name: 'k_1', ns: 'test.coll1' }
]
$ mongosh > db.coll1.getIndices()
[
{ v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.coll1' },
{ v: 2, key: { y: 1 }, name: 'y_1', ns: 'test.coll1' },
{ v: 2, key: { z: 1 }, name: 'bla', ns: 'test.coll1' },
{ v: 2, key: { k: 1 }, name: 'k_1', ns: 'test.coll1' }
]
$ mongosh > db.coll1.getIndexSpecs()
[
{ v: 2, key: { _id: 1 }, name: '_id_', ns: …
```
> feat: getIndexes, getIndexSpecs, getIndexKeys, getIndices

- packages/mapper/src/mapper.ts
Fixes a bug in mapper: some methods of service provider where called with inverted collection and database arguments.
> fix(mapper): fix inverted db and collection args

- package-lock.json
- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/logger.ts
This PR adds a directory (if doesn't exist) `~/.mongodb/mongosh` to use to store history, logs, and soon to be config files.
Logs are now stored per session. So if multiple sessions are running, they will be written to separate files. Log file names are based on a timestamp `Date.now()`. I've tried `performance.now` which is quite a bit more precise, but the timestamps are not as easy to read and a tad more complicated to format. If we prefer that, happy to do some formatting though!
sessionID is created from `uuidv4` and is written on `'connect'` event of each individual log file. Once telemetry is hooked up, it will be written to every telemetry event we will be sending and will be consistent to a local log file.
> MONGOSH-108: log file for individual sessions

- packages/cli-repl/src/completer.spec.ts
- packages/cli-repl/src/completer.ts
When writing a query, while providing no initial prefix, make sure all
completion suggestions get returned.
Before:
After:
> (fix): show autocomplete suggestions for empty queries

- packages/cli-repl/src/logger.ts
- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/src/shell-types.js
- packages/shell-api/yaml/Database.yaml
Implements `show collections`.
- Implements `show collections` in mapper
- Implements `getCollectionInfos` and `getCollectionNames` in mapper
- Add `db.getCollectionInfos` and `db.getCollectionNames` in shell-api
- Add `serviceProvider.listCollections`
```
$ mongosh > db.getCollectionInfos()
[
{
name: 'fitbit_max',
type: 'collection',
options: {},
info: { readOnly: false, uuid: [Binary] },
idIndex: { v: 2, key: [Object], name: '_id_', ns: 'test.fitbit_max' }
},
{
name: 'coll2',
type: 'collection',
options: { capped: true, size: 1024 },
info: { readOnly: false, uuid: [Binary] },
idIndex: { v: 2, key: [Object], name: '_id_', ns: 'test.coll2' }
},
{
name: 'coll1',
type: 'collection',
options: { capped: true, size: 10240 },
info: { readOnly: false, uuid: [Binary] },
idIndex: { v: 2, key: …
```
> Show collection and related api methods

- packages/cli-repl/package.json
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/helpers.ts
Integration / e2e tests for cli-repl.
Adds sanity check to `cli-repl` to test that the shell starts, connects and can run commands.
The test suite spawns the shell in a new process and interacts with it by writing and reading stdio.
Example:
```
[2020/03/31 16:45:56.637]        with connection string
[2020/03/31 16:45:56.637]          runs help command:
[2020/03/31 16:45:56.637]      expected 'events.js:177\n      throw er; // Unhandled \'error\' event\n      ^\n\nError: ENOENT: no such file or directory, open \'/Users/mci/.mongodb/mongosh/1585673146226_log\'\nEmitted \'error\' event at:\n    at SonicBoom.filterBrokenPipe (/data/mci/d5a663fc272f77a73ee587c57e9050be/src/packages/cli-repl/node_modules/pino/lib/tools.js:271:12)\n    at SonicBoom.emit (events.js:200:13)\n    at …
```
> Cli repl tests

- packages/async-rewriter/package-lock.json
- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/constants.ts
- packages/cli-repl/src/index.ts
- packages/cli-repl/src/logger.ts
- packages/i18n/src/locales/de_DE.js
- packages/i18n/src/locales/en_US.js
This PR creates a config file where currently two things are stored:
- userId
- telemetry opt-in.
For example:
When user initial logs in, we write the file, setup `userId`, and toggle `enableTelemetry` to false. User also receives a message to opt in. They can subsequently opt in with `enableTelemetry` command or opt out with `disableTelemetry`.
For example: 
This is not yet hooked up to Segment, so next thing would be to do that, as well as hook up the logger to be notified when user opts in and opts out. That way it can take into consideration when to write to Segment.
> MONGOSH-106, MONGOSH-107: add telemetry opt-in command, add userid

- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/service-provider.ts
- packages/service-provider-server/src/cli-service-provider.ts
> fix: close should return a promise

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/index.ts
- packages/cli-repl/src/logger.ts
- packages/cli-repl/src/redact-pwd.spec.ts
- packages/cli-repl/src/redact-pwd.ts
Removes sensitive information from logs if exists. Uses `mongodb-redact` module just like in `@mongosh/history`. To remove credentials in `driverURI` currently a separate regex to replace information with `<credentials>`.
Examples:
And in logs:
> MONGOSH-103: redact information from logs and connection dialogue

- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/yaml/AggregationCursor.yaml
- packages/shell-api/yaml/Cursor.yaml
Checking for un-inferrable code is done via a property of API classes called `__hasAsyncChild` (we could manually check for all children that have a `returnsPromise: true` attribute but that could get very slow).
> Add hasAsyncChild to Cursors

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/constants.ts
- packages/cli-repl/src/logger.ts
- packages/i18n/src/locales/en_US.js
- packages/shell-evaluator/src/shell-evaluator.ts
As discussed after a previous demo, set up mongosh CLI config to have telemetry
enabled by default (opt-out).
This PR additonal standardises sessionID to be the same as the log file for
easier access when debugging. SessionID is the logged for user's convenience.,
> telemetry config: enable telemetry by default

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
This is in preparation for adding the babel types as annotations in AsyncRewriter. In order for the PR to be easy to follow, I'm making the syntax changes first so that when the real changes come in a sparate PR (preview here: #123) it'll be easy to follow. This PR includes 2 types of changes:
1. Replace dot notation with index notation for decorations on instances of `Node` to avoid TypeScript errors. `Node` is a babel-defined type that I add type decorations to in order to do type inference. I'm not sure this is the best way to satisfy the ts compiler, but also the `Node` type is nested within other babel types so I'm not sure how I can inform the ts compiler that I need two extra attributes on some `Node` instances.
2. Apparently `this` and `state` are interchangable for babel visitor …
> Clean up AsyncRewriter

- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
Allows commands to be invoked with a trailing semi-colon: `use db1;`, `show dbs;`.
> feat: allows commands with trailing semicolon

- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/bin/compile-shell-api.js
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Collection.yaml
- packages/shell-api/yaml/Database.yaml
This is another way to avoid clashes between db and collection methods in mapper, even less invasive than splitting it into classes.
Prefix database methods with `database_` and collection methods with `collection_`. The prefix is configurable in the shell api yaml.
> Mapper methods prefix

- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
Implements `findAndModify` which was commented out till now.
Sorry for the changes in `mapper.spec.js` i fixed the brackets, there were collection methods tests inside the commands section and other weirdly skewed stuff. The only real change related to this PR in that file is this one: 
https://github.com/mongodb-js/mongosh/pull/134/files#diff-104d5062b24948c6ee6a9d6d0dd5c314R538
> feat: implement findAndModify

- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/closable.ts
- packages/service-provider-core/src/command-options.ts
- packages/service-provider-core/src/database-options.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-core/src/read-concern.ts
- packages/service-provider-core/src/read-preference.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-core/src/service-provider.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-core/src/write-concern.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
Preparatory work for `getWriteConcern`, `setWriteConcern`:
1. Add `DatabaseOptions`, `CommandOptions` and related types to `service-provider-core`.
2. Make sure all the methods accepts a `dbOptions` parameter and that `dbOptions` is always passed down to `client.db`.
3. Make sure we set `returnNonCachedInstance: true` as dbOption always
> Always pass dbOptions

- packages/browser-repl/src/index.stories.tsx
- packages/browser-runtime-core/src/open-context-runtime.ts
- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/connect-info.spec.ts
- packages/cli-repl/src/connect-info.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
Adds more detailed information about the current connection:
```
{
isAtlas: true,
isLocalhost: false,
serverVersion: '4.2.6',
isEnterprise: true,
authType: 'scram-sha-1',
isDataLake: false,
dlVersion: null,
isGenuine: true,
serverName: 'mongodb'
}
```
Uses [mongodb-build-info](https://github.com/mongodb-js/mongodb-build-info) to determine whether a connection is `DataLake` or a `GenuineMongoDB`. (there is also [a ticket](https://jira.mongodb.org/browse/COMPASS-4260) to use this module in compass)
Adds three more methods to service-provider-server:
- __buildInfo:__ replacement for `getServerVersion`. Returns the whole of `buildInfo` that we then use to extract connection information from.
- __getTopology:__ returns current topology property on CliServiceProvider's `mongoClient`.
- …
> MONGOSH-104: log connection information

- packages/i18n/src/locales/en_US.js
- packages/mapper/package.json
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/explainable.spec.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Collection.yaml
- packages/shell-api/yaml/Explainable.yaml
Implements `db.coll.explain()` so that it returns an explainable.
Initial explainable implementation with just 3 methods:
- `getCollection`
- `get/setVerbosity`
Also use custom errors.
> feat: initial explainable

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
pretty-repl now checks whether process.stdout is TTY before colouring the input.
> pretty-repl@2.3.0: check for isTTY before colouring

- package.json
- packages/shell-api/bin/report-missing-help.ts
- packages/shell-api/bin/report-supported-api.ts
- packages/shell-api/package.json
Adds two scripts:
- `npm run report-supported-api`: outputs all the supported api types and methods in a `diff` friendly way.
- `npm run report-missing-help`: outputs all the types and methods for which help is missing.
> report missing help and supported api scripts

- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-server/src/node/node-cursor.spec.ts
- packages/service-provider-server/src/node/node-cursor.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/AggregationCursor.yaml
- packages/shell-api/yaml/Explainable.yaml
Implements `explainable.find()` and `explainable.aggregate()`.
The way the cursor is reused is not super pretty: we just rewrite the `toReplString` and `shellApiType`, perhaps 2 types proxying the cursor methods would be better.
> implements `explainable.find` and `.aggregate`

- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Database.yaml
Implements `db.adminCommand`.
Also:
- tests `db.runCommand`
- moves all db methods in the same section of the mapper
- refactor messageBus.emit('api-call') for db methods in `_emitDatabaseApiCall`;
> Implement db.adminCommand

- packages/cli-repl/src/format-output.ts
Set default inspect depth to 6.
So that the following output would be visible:
```
{
stages: [
{ '$cursor': [Object] },
{ '$group': [Object] },
{ '$project': [Object] }
],
ok: 1
}
```
```
{
stages: [
{
'$cursor': {
query: {},
queryPlanner: {
plannerVersion: 1,
namespace: 'test.coll7',
indexFilterSet: false,
parsedQuery: {},
queryHash: '8B3D4AB8',
planCacheKey: '8B3D4AB8',
winningPlan: { stage: 'COLLSCAN', direction: 'forward' },
rejectedPlans: []
}
}
},
{
'$group': { _id: { '$const': null }, count: { '$sum': { '$const': 1 } } }
},
{ '$project': { _id: false, count: true } }
],
ok: 1
}
```
> feat: increase inspect depth

- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/service-provider-browser/src/unsupported-cursor.ts
- packages/service-provider-core/src/cursor.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Database.yaml
- Implements `db.aggregate` and add support for `{explain: true}` in `db.coll.aggregate`.
Changes:
- Implements `db.aggregate`
- Add tests for `db.coll.aggregate`
- Refactor the common code of  `mapper.database_aggregate` and `mapper.collection_aggregate` in a private method.
- Refactor the code to make a cursor explainable into a private method.
- Add all the methods to the `Cursor` interface so it can be stubbed properly with `stubInterface`.
**NOTE**:  `Explainable.aggregate`, `Collection.aggregate([...], {explain: true})` and `Database.aggregate([...], {explain: true})` are currently returning an `AggregationCursor` that turns into an explain once evaluated. That is not what happens in the old shell, but i'd keep it for a follow up PR as this one is quite large already.
> db.aggregate and aggregate with explain

- .evergreen.yml
- packages/cli-repl/README.md
- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/connect-info.spec.ts
- packages/cli-repl/src/connect-info.ts
- packages/cli-repl/src/logger.ts
- packages/java-shell/package-lock.json
- packages/mapper/src/mapper.ts
- packages/shell-api/package-lock.json
- packages/shell-evaluator/src/shell-evaluator.ts
- scripts/release.js
Sends information to segment if user opted-in. 
API_KEY from segment is to be read from `./config.js` file that evergreen writes when releasing the binary. This PR adds a task to `release.js` to populate that file. Evergreen already has the appropriate key to be written.
This PR also adds a few more events: `mongosh:new-user`, `mongosh-update-user`
and `mongosh:toggle-telemetry`.
Information sent to segment is stripped of possible sensitive information that
could come in queries via `mongodb-redact` module.
Adds documentation on events we listen to in `logger.ts`
~@durran what's the best possible way for me to get this API key into an
Evergreen build?~
> MONGOSH-110: send telemetry events to segment if opted-in

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/constants.ts
- packages/cli-repl/src/format-output.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/cli-repl/src/index.ts
- packages/i18n/src/locales/en_US.js
This PR adds a few touch ups to the CLI UI:
- an extra message about the wiki on startup
- extra highlighting to the currently connected url
- changes prompt to `msh >` since `$` is not usually assigned to REPLs and `mongosh` takes up a lot of valuable space.
There is also a fix for `undefined` result. If `result.value` is of type undefined, we will return a new line.
> touch up mongosh greeting

- packages/browser-repl/src/components/shell-output-line.spec.tsx
- packages/browser-repl/src/components/shell-output-line.tsx
- packages/browser-repl/src/components/types/show-collections-output.spec.tsx
- packages/browser-repl/src/components/types/show-collections-output.tsx
- packages/cli-repl/src/format-output.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
`show collections` should be formatted in implementors instead of the mapper.
This PR removes `.join('\n')` out of the mapper.
> MONGOSH-186: move show collections formatting to implementors

- packages/cli-repl/src/cli-repl.ts
As discussed in #161, let's make the prompt just `>`.
> Made the prompt just '>'

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
- packages/async-rewriter/src/symbol-table.spec.ts
- packages/async-rewriter/src/symbol-table.ts
When writing the wiki I found a bug where the 'unknown' "enum" was getting modified, causing a circular reference JSON error. Fixed via using object literals instead of the enum, plus trying JSON.stringify and wrapping any error with an `MongoshInternalError` in case something else comes up.
> Circular JSON error bugfix

- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Collection.yaml
- packages/shell-api/yaml/Database.yaml
- packages/shell-api/yaml/Explainable.yaml
Replicate the behaviour of the old shell in regards to aggregate with explain.
This is a bit odd, but when calling `db.coll.aggregate(pipeline, {explain: undefined or false})`, an `AggregationCursor` is returned. With `db.coll.aggregate(pipeline, {explain: true})` instead a plain object gets returned and the same can be assigned to a variable.
So this PR basically allows for this:
```
explainResult = db.coll.aggregate(pipeline, {explain: true});
explainResult.stages
```
that was not possible before.
Note that `db.coll.explain().aggregate()` behaves in the same way (does not return a cursor), whereas `db.coll.explain().find()` does return a cursor.
> fix: align aggregate + explain with old shell

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/format-output.ts
There are certain asynchronous functions where we don't properly handle promise rejections. These are mainly done on startup: `connect` and `buildInfo`. This PR wraps them all in a `try`/`catch` to display the error to the user properly, and terminate the process when necessary. 
__Before:__
__After:__
I've tried to get errors with a whole bunch of our other service-provider-* methods, and it seems like everything else gets handled well. This is due to the fact that our API methods are part of the mapper, and the result from the mapper gets handled in the writer, which explicitly checks for `result.message && result.stack`. This allows us to always format the incoming error and return it gracefully. 
I might not have seen all the unhandled `await`s. If you spotted something before that …
> MONGOSH-177: handle unhandled rejections

- packages/i18n/src/locales/en_US.js
- packages/java-shell/package-lock.json
- packages/mapper/src/mapper.spec.ts
- packages/mapper/src/mapper.ts
- packages/shell-api/bin/compile-shell-api.js
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/shell-api-signatures.js
- packages/shell-api/src/shell-api.js
- packages/shell-api/yaml/Database.yaml
Implements `db.getSiblingDB()` and `db.getCollection()`.
- For `getSiblingDB` also factor the code with `use`
- For `getCollection` also changes the shell-api compilation for `Database` putting the collections in a separate property `_collections`, in such way  using `getCollection` we can have collection names that would normally conflict with property names in the database instance.
> Implements `db. getSiblingDB()` and `db.getCollection()`

- packages/cli-repl/src/completer.spec.ts
- packages/cli-repl/src/completer.ts
Reads from `ShellAPI` and autocompletes the `db` objects. This _does not_ include collection completions. Those will be done later on.
> add 'db. ' autocompletes

- packages/browser-runtime-core/src/open-context-runtime.ts
- packages/browser-runtime-electron/package-lock.json
- packages/browser-runtime-electron/package.json
- packages/browser-runtime-electron/src/electron-runtime.spec.ts
- packages/browser-runtime-electron/src/electron-runtime.ts
Allow to pass a message bus to the runtime so we can use it for telemetry and logging in compass:
```
new ElectronRuntime(serviceProvider, messageBus)
```
> Allow message bus in runtime

- .evergreen/.install_node
- package.json
- Fixes the bootstrap concurrency to 1 so to avoid cache lock issues. 
- Uses `npm ci` and `lerna bootstrap --ci` in evergreen to prevent unexpected version bump with dependencies.
> chore: fix bootstrap concurrency and use npm ci

- packages/mapper/src/mapper.integration.spec.ts
- packages/mapper/src/mapper.ts
Use `provider.updateOne` to implement `coll.updateOne`.
NOTE: the `insertedId` field in the update result is not an `ObjectId` as in the old shell. 
```
> db.coll1.updateOne({x: 1}, {$set: {y: 2}})
{
acknowleged: 1,
matchedCount: 1,
modifiedCount: 1,
upsertedCount: 0,
insertedId: null
}
> db.coll1.updateOne({x: 112312323}, {$set: {y: 2}}, {upsert: true})
{
acknowleged: 1,
matchedCount: 0,
modifiedCount: 0,
upsertedCount: 1,
insertedId: { index: 0, _id: '5ebbfb6d836db564d1bbb588' }
}
```
> fix: use provider.updateOne for coll.updateOne

- packages/cli-repl/.eslintignore
- packages/cli-repl/bin/mongosh.js
- packages/cli-repl/test/e2e.spec.ts
- packages/java-shell/package-lock.json
This got accidentally removed when adding eslint to cli-repl package. Adding it
back in.
> add back node --experimental-repl-await to mongosh bin file

- packages/cli-repl/src/cli-repl.ts
When requiring password, make sure we:
1. use `setupRepl()` instead of `connect()` function
2. catch and log the errors when setting up the REPL and when reading password
options.
> fix: use setupRepl when connecting with username/password

- packages/i18n/src/locales/en_US.js
- packages/mapper/src/mapper.ts
Adds the currently missing help documentation for `link`, `description`,
`example` to most commands from running `npm run report-missing-help`
> add aggregation, explainable, and collection help i18n documentation

- packages/compass-shell/.babelrc
- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
Fixes `ReferenceError: regeneratorRuntime is not defined` error when running `compass-shell` tests.
> fix: add babel transform regenerator runtime

- packages/async-rewriter/package-lock.json
- packages/async-rewriter/package.json
- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
- packages/async-rewriter/src/await.js
- packages/cli-repl/bin/mongosh.js
- packages/cli-repl/package-lock.json
- packages/shell-evaluator/package-lock.json
- packages/shell-evaluator/src/shell-evaluator.ts
To package up our executables with built in top-level await support, we will now
process all input with [node's internal await
wrap](https://github.com/nodejs/node/blob/master/lib/internal/repl/await.j://github.com/nodejs/node/blob/master/lib/internal/repl/await.js).
This wrapper puts `async()` in front of an awaited function.
Because we are rewriting our own functions with `await`, this is done after our
internal rewrite.
> fix: bring in node repl's top-level await

- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
- packages/compass-shell/scripts/run-in-compass.js
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.less
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
- packages/compass-shell/src/components/resize-handle/index.js
- packages/compass-shell/src/components/resize-handle/resize-handle.jsx
- packages/compass-shell/src/components/resize-handle/resize-handle.less
- packages/compass-shell/src/components/shell-header/index.js
- packages/compass-shell/src/components/shell-header/shell-header.jsx
- packages/compass-shell/src/components/shell-header/shell-header.less
- packages/compass-shell/src/components/shell-header/shell-header.spec.js
- packages/compass-shell/src/index.js
https://jira.mongodb.org/browse/MONGOSH-89
Mocks for reference: https://mongodb.invisionapp.com/share/RZVV94NAY6B#/screens/403867881
This PR updates the shell plugin to register as a global component for use in `compass-home`.
It also configures the styling of the component so that it can be clicked to toggle open and clicked to toggle closed. It is resize-able by dragging the triple bar in the middle as a handler, as well as the bar that separates it from the rest of the page. It has a max height of 800px, and a min height of 24px. We use this package for resizing: https://github.com/bokuweb/re-resizable I found it did the job nicely and haven't gotten into too many issues, the dependencies on it seem slim too. One thing we could improve is when compass is zoomed in a lot (ctrl + '+') …
> MONGOSH-89: Shell as global compass role

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/connect-info.spec.ts
- packages/cli-repl/src/connect-info.ts
- packages/cli-repl/src/logger.ts
As per @mmarcon's request, changing telemetry events to be snake_cased instead
of camelCased.
This PR also adds `server_os` and `server_arch` information to `Connect` event.
> adjust telemetry names for connect event

- LICENSE
According to the previous version of this file, this is how to apply Apache 2.0 to a project:
APPENDIX: How to apply the Apache License to your work.	
To apply the Apache License to your work, attach the following	
boilerplate notice, with the fields enclosed by brackets "[]"	
replaced with your own identifying information. (Don't include	
the brackets!)  The text should be enclosed in the appropriate	
comment syntax for the file format. We also recommend that a	
file or class name and description of purpose be included on the	
same "printed page" as the copyright notice for easier	
identification within third-party archives.
> apply licence to MongoDB Inc.

- packages/browser-runtime-electron/src/electron-runtime.spec.ts
- packages/browser-runtime-electron/src/electron-runtime.ts
A fix that allows to use `require` in playgrounds and compass.
**NOTE:** 
Webpack will replace `require` with its own implementation, and that would not necessarily have access to the node modules available in node (depends on the target configuration).
As a workaround we alias `require` to [`__non_webpack_require__`](https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific) when available.
> Allow `require` in vscode and compass shell

- packages/browser-repl/src/components/ace-theme.js
- packages/browser-repl/src/components/editor.spec.tsx
- packages/browser-repl/src/components/editor.tsx
- packages/browser-repl/src/components/shell-input.tsx
- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
https://jira.mongodb.org/browse/COMPASS-4294
This PR has 2 small improvements for the shell plugin interaction (changes are in browser-repl):
- Background coloring of cursor selection - I went with gray dark 1 from https://mongodb.github.io/leafygreen-ui/?path=/story/palette--ui open to any suggestions.
- Click to focus input anywhere on a blank input instance (it used to only focus when clicking on the textfield line).
*Screenshots*
___
> COMPASS-4294: Improve shell plugin interaction

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/connect-info.spec.ts
- packages/cli-repl/src/connect-info.ts
- packages/cli-repl/src/logger.ts
- packages/java-shell/package-lock.json
Updates a few things in regards to telemetry:
- always call `toString()` when initially creating ObjectIds for sessions and
userID
- Use `fast-json-parse` when parsing config file. Return and log if an error is
present.
- run analytics.identify when updating user data if telemetry is present.
- remove warn log for analytics key
- log out node version as part of connection log event
> fixes to telemetry, objectid, and local config file

- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
Looks like I added this unneeded dependency: `mongodb-client-encryption` https://github.com/mongodb-js/mongosh/commit/bd24511cf556077f864bdb4740d26b6047a8d9c5
It's causing compass build failure https://evergreen.mongodb.com/task/10gen_compass_master_rhel_package_and_publish_compass_6699cdf4718a6cc9027adaba498cef6349c6362b_20_06_03_19_03_04 and we should probably remove it anyway so let's remove it.
> Remove mongodb-client-encryption dependency

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/logger.ts
Adds a note to the greeting about the current mongosh version.
> add current mongosh version to greeting message

- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
- packages/compass-shell/src/components/info-modal/index.js
- packages/compass-shell/src/components/info-modal/info-modal.jsx
- packages/compass-shell/src/components/info-modal/info-modal.less
- packages/compass-shell/src/components/info-modal/info-model.spec.js
- packages/compass-shell/src/components/shell-header/shell-header.jsx
- packages/compass-shell/src/components/shell-header/shell-header.less
- packages/compass-shell/src/components/shell-header/shell-header.spec.js
- packages/compass-shell/src/modules/index.js
- packages/compass-shell/src/modules/info-modal.js
https://jira.mongodb.org/browse/COMPASS-4292
This PR adds an info modal with existing ace editor hotkeys listed. I'd like to add ctrl+r search functionality but we can do that in another PR. 
The mocks had some other hotkeys listed, some of which we can't support now (background processing): https://mongodb.invisionapp.com/share/RZVV94NAY6B#/screens/403867891
Here's where we're linking to: https://docs.mongodb.com/manual/products/mongosh
I'm going to check that's the right place.
Currently the behavior is that the info button does not show unless the shell is expanded. Is this expected?
> COMPASS-4292: Shell plugin info modal

- packages/cli-repl/src/cli-repl.ts
> exit if node version too low

- packages/cli-repl/src/cli-repl.ts
We are not checking for a minimum, we are checking if the version matches the one we expect but the error message was still talking about a minimum version required.
> Changed copy of node version mismatched message.

- packages/cli-repl/src/cli-repl.ts
`process.exit` if connection does not succeed or connection with username/password does not succeed.
> MONGOSH-259: process.exit when connection fails

- .evergreen.yml
Use just the usual `test` task for cygwin build.
> run regular tests for cygwin build

- packages/browser-repl/package-lock.json
- packages/cli-repl/src/cli-repl.ts
- packages/compass-shell/package-lock.json
We are currently not using an already established `MongoshWarning` when informing user on mismatched nodejs version. This PRs uses the designated error, as well as formats using our standard error formatter.
> use MongoshWarning when nodejs are mismatched

- packages/shell-api/src/enums.ts
`export const shellApiType = Symbol('...')` is working fine in node js with `npm run start` but in the binary we get actually 2 distinct unique symbols: one used in the class definition and one used in the shell evaluator.
To fix this we use `Symbol.for('...')` with a unique name.
> fix duplicated symbol in compiled binary

- .evergreen.yml
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/helpers.ts
- packages/cli-repl/test/test-shell.ts
- testing/integration-testing-hooks.ts
Run e2e tests on compiled binaries
> Run e2e tests on compiled binaries

- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/connect-info.spec.ts
- packages/service-provider-core/src/connect-info.ts
- packages/service-provider-server/src/cli-service-provider.ts
- adds `mongosh_version` (from package.json) to `getConnectInfo` function return.
- `mongosh_version` is then sent to analytics and gets logged to logger
> MONGOSH-240: log out mongosh_version to log file

- packages/service-provider-core/package.json
- packages/service-provider-core/src/connect-info.spec.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
https://jira.mongodb.org/browse/MONGOSH-268
Small fix: the uri passed to the service provider is optional, however when we were fetching connection info to have the mongo version for autocomplete we were running string operations on the uri, which were erroring out. Added a small test to catch in future. Was cool to learn more of the inner workings of mongosh.
I think in future we could make this a bit more streamlined by passing the connection information in from compass into the browser repl/shell api internal state, so we can avoid the extra fetching of connection info inside of mongosh. 
Auto completion working in compass-shell:
Was thinking about pulling telemetry into this ticket, but since it involves changes in compass metrics also I opened a new ticket and can work on that: …
> MONGOSH-268: Fix autocompletion in compass-shell

- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/shell-api/src/integration.spec.ts
See https://jira.mongodb.org/browse/SPEC-1399
Starting in MongoDB 4.4, the ns field will no longer be present in the index specifications returned from the listIndexes server command. This updates the integration tests so that we don't assume there is a 'ns' field present.
> Handle missing 'ns' in listIndexes

- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
- packages/compass-shell/src/components/shell-header/shell-header.spec.js
- packages/compass-shell/src/modules/index.js
- packages/compass-shell/src/modules/runtime.js
- packages/compass-shell/src/plugin.spec.js
- packages/compass-shell/src/stores/store.js
- packages/compass-shell/src/stores/store.spec.js
- packages/shell-api/src/integration.spec.ts
COMPASS-4351
This PR adds telemetry events for the compass shell plugin. When the plugin is expanded it emits a `compass:compass-shell:opened`. The global appRegistry is passed as a message bus option to mongosh so that mongosh log events are emitted in compass land and can be consumed by the metrics (or possibly elsewhere later).
Here's the PR in `compass-metrics` where the events are being passed to the telemetry:  https://github.com/mongodb-js/compass-metrics/pull/147
After this is merged we'll want to do a release, we can see with the team if there's anything to be merged soon or if it can happen sooner. Then we can update the version in compass as well.
> COMPASS-4351: Add compass shell telemetry

- packages/cli-repl/src/completer.spec.ts
- packages/cli-repl/test/e2e-auth.spec.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/service-provider-browser/src/stitch-service-provider-browser.ts
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/auth-options.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/helpers.ts
- packages/shell-evaluator/src/shell-evaluator.ts
Two things I want to double check
- it won't ever be a problem that we are passing the options originally set by the user when the connect via the CLI (the auth ones are overwritten)
- command history hasn't been saving the ones with passwords, however, it's been a bit funky and has been not saving regular commands as well
> MONGOSH-180 - Support user management commands

- packages/cli-repl/src/completer.spec.ts
- packages/i18n/src/locales/en_US.js
- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
Not implementing Database.getSisterDB , see https://jira.mongodb.org/browse/SERVER-46231
Collection.getCollection is not mentioned in docs, plus the behavior in the old shell is weird: db.abc.getCollection('def') --> Collection("abc.def")
> MONGOSH-305 - Support database and collection helper methods

- .evergreen.yml
- .evergreen/DownloadAndRunMongod.ps1
- .gitignore
- packages/browser-repl/config/webpack.config.base.js
- packages/compass-shell/config/webpack.base.config.js
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/shell-api/src/integration.spec.ts
- testing/integration-testing-hooks.ts
Changes:
- Just download and run mongo on windows instead of using `mongo-runner`
- Add `skipIfServerVersion(<semver-expr>)` helper to skip tests in case the mongodb version under test does not apply to the test suite `ie. skipIfServerVersion('< 4.4')`.
> MONGOSH-224: fix windows tests

- package.json
- packages/browser-repl/src/components/editor.spec.tsx
- packages/browser-repl/src/components/editor.tsx
- packages/browser-repl/src/components/shell-input.less
- packages/browser-repl/src/components/shell-input.spec.tsx
- packages/browser-repl/src/components/shell-input.tsx
- packages/browser-repl/src/components/shell-loader.less
- packages/browser-repl/src/components/shell-loader.tsx
- packages/browser-repl/src/components/shell-output-line.less
- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
- packages/browser-repl/src/index.stories.tsx
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
Disables the input while a command is being executed. Fixes usability issues with slow commands:
> Browser repl disable input between commands

- packages/i18n/src/locales/en_US.js
The help link/text/example were copy-pasted from `db.dropDatabase()`. Now they have the right content.
> MONGOSH-319: fix for db.getCollection.help()

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/logger.spec.ts
- packages/cli-repl/src/logger.ts
Uses [`nanobounce`](github.com/choojs/nanobounce) to debounce sending analytics event for `mongosh:api-call`. I feel like all other events are quite singular, and for now, we can only just debounce api calls. Debounce timing is set to `1000`, but we can of course push it to more, if we feel like this will still flood Segment.
Added a few small tests super quickly to check if listeners are attached to our events, since we had no tests at all (this is on me!) in this module.
> MONGOSH-328: debounce telemetry

- packages/build/src/tarball.ts
`tar.c` does not use `gtarball` as an option. It should be `gzip` instead.
> fix(build): tar.c takes gzip as an option

- package.json
- scripts/generate-homebrew-formula.js
Generates and print (no automated PR), the homebrew formula for the latest release of `@mongosh/cli-repl`. Gets the latest version with `npm view` and then renders a `mongosh.rb` template to the standard output with the correct `sha`.
> chore: generate homebrew formula

- packages/cli-repl/test/e2e.spec.ts
This otherwise results in an unhandled rejection, because
`describe()` callbacks run immediately, without waiting for
`beforeEach()` to populate the `shell` variable.
> test: fix test for 'version' command

- packages/cli-repl/test/e2e-bson.spec.ts
- packages/service-provider-core/src/printable-bson.ts
- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
- Allows to create `NumberLong` bigger than `Number.MAX_SAFE_INTEGER`.
- Requires the argument of `NumberLong` and `NumberDecimal` to always be a string so to prevent users to get a misrepresented value by mistake.
- Makes `NumberInt()` to be equivalent to `NumberInt(0)`, aligning the behaviour with the other constructors and with the old shell.
> MONGOSH-341: Fix wrong values with NumberLong for numbers > Number.MAX_SAFE_INTEGER

- README.md
- config/build.conf.js
- packages/build/README.md
- packages/build/src/build-and-release.ts
- packages/build/src/config.ts
- packages/build/src/index.ts
- scripts/compile-exec.js
- scripts/release.js
Provide an easy way to create distribution tarballs without also
uploading them for testing.
> feat: add ability to perform tarball dry-run

- packages/cli-repl/test/e2e-bson.spec.ts
- packages/service-provider-core/src/printable-bson.ts
- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
Print `BinData` values in a way that accounts for their subtype
(i.e. format UUID and MD5 in their common representation) and
generic `BinData` values as base64, to ensure that binary data is not
written directly to the terminal. This also enables copy-pasting of
the output for `BinData` values to be used as input for other
operations.
> MONGOSH-323 - Pretty-print BinData values

- packages/cli-repl/test/helpers.ts
This makes a lot more tests pass locally for me, and it shouldn’t
really increase the time it takes to run the tests.
> test: unconditionally set `eventually()` timeout to 10s

- packages/cli-repl/src/cli-repl.ts
When Node.js pushes a release candidate, the version will contain
a suffix like `-rc.0`, but semver doesn’t account for that in its
`satisfies()` function and rejects all versions tagged that way.
> fix: allow running mongosh with Node.js release candidates

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/test-shell.ts
This enables Ctrl+C to interrupt both the current synchronous JS
execution and awaiting the result.
Refs: https://nodejs.org/api/repl.html#repl_repl_start_options
> MONGOSH-346 - enable Ctrl+C in shell for sync and async operations

- packages/errors/index.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
For all shell helpers that use runCommand, use runCommandWithCheck instead that checks the results for `ok: 0`. If so, it throws `MongoshCommandFailed` with an error message that includes the original command and a suggestion to use `runCommand` if you want the raw results.
The PR looks big because I had to rename every instance of runCommand --> runCommandWithCheck, but it's actually quite a small change.
> MONGOSH-320 - Consistently throw when command returns ok:0

- .evergreen.yml
- package-lock.json
- package.json
- packages/build/README.md
- packages/build/src/build-variant.spec.ts
- packages/build/src/build-variant.ts
- packages/build/src/download-center.ts
- packages/build/src/tarball.spec.ts
- packages/build/src/tarball.ts
Uses [pkg-rpm](github.com/mongodb-js/pkg-rpm) to create an rpm package. This
package will be uploaded to download's centre when doing a release.
Additionally, this PR adds `rhel80-large` build variant. This build variant runs a
`check` and `release` tasks, and depends on tests passing on our existing linux
build variant.
> MONGOSH-121: upload rpm to downloads centre

- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
Because this gives a better error than
```
$ mongosh /x
Cannot read property '1' of null
```
:)
> fix: report explicit error when invalid connection URI is passed

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/download-center-schema.ts
- packages/build/src/download-center.spec.ts
- packages/build/src/download-center.ts
- Fixes malformed download center JSON
- Add tests to prevent future issues
> fix: fix download center json and add tests

- scripts/publish-npm.js
Check npm access to make sure the user has enough permission to publish packages before starting a release.
> chore: check user permissions to publish

- packages/cli-repl/src/constants.ts
Cleaned up the `mongosh --help` output to only include things that are supported.
1. Removed options that are not yet supported (e.g. FLE, loading scripts from files, etc.)
2. Removed options that are not supported in the driver and therefore for the foreseeable future we won't support in the shell either:
* `--ipv6`: if nothing is specified, the driver will try IPv6 first and fall back to IPv4 ([details](https://mongodb.github.io/node-mongodb-native/3.5/api/MongoClient.html#.connect))
* `--tlsCRLFile`: this is not an option that the driver supports
Everything is removed rather than commented out to not leave big spaces in the help output. This PR is referenced as a comment in the code so we can go back and check what was removed.
> Help cleanup

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/test-shell.ts
- packages/shell-evaluator/src/shell-evaluator.ts
The added comment goes into a bit more detail here, but basically,
our shell evaluation function was under the wrong assumption that the
built-in eval code would always call its callback, even if evaluation
of the code threw an error. That does not turn out to be the case
for Node.js; instead, the REPL would handle the error internally
and not call its callback, leaving us with an async function that
never finishes.
This had the side effect that listeners for SIGINT would not be removed
(because from the cli-repl perspective, the inner eval would never
finish), leading to odd results when entering Ctrl+C after an earlier
statement had thrown an exception.
The solution here is hacky; we should probably take the time
at some point to find a better one.
> fix: Ctrl+C should work after exceptions

- package.json
- packages/async-rewriter/package.json
- packages/browser-repl/package.json
- packages/browser-runtime-core/package.json
- packages/browser-runtime-electron/package.json
- packages/build/package.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/test/test-shell.ts
- packages/compass-shell/package.json
- packages/errors/package.json
- packages/history/package.json
- packages/i18n/package.json
- packages/java-shell/package.json
- packages/mongosh/package.json
- packages/service-provider-core/package.json
- packages/service-provider-server/package.json
- packages/shell-api/package.json
- packages/shell-evaluator/package.json
- Disable REPL preview because it is not accurate for our evaluator
- Fix tests (`String.prototype.matchAll()` requires a global regexp)
- Update `package.json`s to not restrict to v12.x only
> chore: support Node.js 14.x for testing

- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.ts
Cursors were created with `Collection` and `Database` instances instead of expected `Mongo`
> Create cursors with expected Mongo instance

- .evergreen.yml
- package.json
- packages/build/package.json
- packages/cli-repl/package.json
- scripts/docker/ubuntu16.04-build.Dockerfile
Stop releasing `@mongosh/build`
> chore: make build package private

- config/repo-config.yml
We were building previously only for 18.04. This adds an additional
20.04 upload.
> chore(build): upload mongosh PPA to ubuntu2004 dist

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
Currently requiring `@mongosh/browser-runtime-electron` from vscode errors since `@mongosh/cli-repl` has `@mongosh/build` as a dependency, and it's now a private package. 
* Edit: The package-lock.json changes look a bit funny, looking into.
> Remove @mongosh/build from @mongosh/cli-repl dependencies

- packages/i18n/src/locales/en_US.js
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shard.spec.ts
- packages/shell-api/src/shard.ts
- I didn't include integration tests in this PR because it will make more sense to do so when there are more methods to test as one (i.e. enableSharding, then disableSharding, etc)
- I didn't include tests for sh.status since it's mostly legacy and just very complicated
> MONGOSH-638 - Enable sharding methods

- scripts/publish-npm.js
`0.4.2` release errored out on the version verification:
```Successfully published:
- @mongosh/async-rewriter@0.4.2
- @mongosh/browser-repl@0.4.2
- @mongosh/browser-runtime-core@0.4.2
- @mongosh/browser-runtime-electron@0.4.2
- @mongosh/cli-repl@0.4.2
- @mongodb-js/compass-shell@0.4.2
- @mongosh/errors@0.4.2
- @mongosh/history@0.4.2
- @mongosh/i18n@0.4.2
- mongosh@0.4.2
- @mongosh/service-provider-core@0.4.2
- @mongosh/service-provider-server@0.4.2
- @mongosh/shell-api@0.4.2
- @mongosh/shell-evaluator@0.4.2
lerna success published 14 packages
(node:88007) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The published version should have been changed: before 0.4.1, after: 0.4.1
at publish (/private/tmp/mongosh/scripts/publish-npm.js:137:12)
at main …
```
> Add 10s wait before checking if npm version has been published

- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
Validate the input to be in ISO-8601 format and set the
default timezone to UTC.
> MONGOSH-354 - Validate ISODate input

- packages/i18n/src/locales/en_US.js
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/replica-set.ts
This PR removes MongoshUnimplementedError for Replica Set API and adds
rs.config, rs.initiate, rs.reconfig APIs. 
This PR exludes end-to-end tests, as it would be good to have a few more
implemented APIs so we can test replication properly.
> feat(shell-api): MONGOSH-358 add rs.config, rs.intiate, rs.reconfig commands

- package-lock.json
- package.json
Now that signing Works™, use a public package instead of my
personal fork. :)
> chore: switch node-codesign to official package

- packages/i18n/src/locales/en_US.js
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/helpers.ts
For results from calls on collections, add metadata about the source of
the returned data (database name, collection name, method, arguments)
so that consumers of the shell can figure out from what source
the result was generated, e.g. in order to understand how to modify
that original data.
This also adds a fake `Document` type to the `ShellResult` reported
for e.g. `findOne()`, so that it is possible to tell those apart
from other plain JavaScript objects, e.g. in order to be able to
know whether the result is a modifiable object in the database or not.
> MONGOSH-376 - Include metadata about data source in result

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/test/resources/collection/insertOne.expected.txt
- packages/java-shell/src/test/resources/literal/undefined.expected.txt
Fix Java shell after PR #361
JavaServiceProvider should return only JS objects so they support 'defineProperty'.
All Java tests now pass. No core files were touched
> Fix Java shell after PR #361

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
- packages/java-shell/src/test/resources/db/showCollections.expected.txt
- packages/java-shell/src/test/resources/db/showCollections.js
- packages/shell-api/src/shell-internal-state.ts
GraalJS does not allow to define property on top context, so we need to update database in internal state manually.
> [java-shell] fix "show collections" command (it always uses "test" database)

- packages/java-shell/src/test/kotlin/com/mongodb/mongosh/util.kt
Some tests, e.g. those that refer to BSON types, don’t have their
test resource files starting with a lowercase letter. Change the
test code to accept either variant.
> fix: account for case-sensitive filesystems in java-shell tests

- packages/browser-repl/package.json
- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
- packages/browser-repl/src/iframe-runtime/iframe-runtime.ts
- packages/browser-runtime-core/src/open-context-runtime.ts
- packages/browser-runtime-core/src/runtime.ts
- packages/browser-runtime-electron/package.json
- packages/browser-runtime-electron/src/electron-runtime.spec.ts
- packages/browser-runtime-electron/src/electron-runtime.ts
- packages/cli-repl/src/cli-repl.ts
- packages/shell-api/src/index.ts
- packages/shell-api/src/shell-internal-state.ts
- packages/shell-evaluator/src/index.ts
- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
Fwiw, alternatives that I’ve considered are a) passing this over the `messageBus` instead or b) changing the return value of `ShellEvaluator.customEval()` (to e.g. an async iterable instead of a plain promise), but in the end this seemed like the best choice to me because this might be helpful if we ever need another way to customize shell evaluation.
> MONGOSH-237 - Allow custom print/printjson for individual platforms

- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
Use mongodb-js/saslprep@b7aeb7b2e8fd4861ba8c45cfde90ae3f12c8f879,
which reduces file size significantly and lets us bundle the library
in the dist .js file, because this stops saslprep from loading files
from disk manually.
> Make saslprep bundle-able

- packages/browser-runtime-electron/src/electron-runtime.spec.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/mongo.spec.ts
This is no longer used in any dependants.
> chore: remove `value` from `ShellResult`

- packages/cli-repl/test/e2e.spec.ts
- packages/shell-api/src/shell-internal-state.ts
Discovered during demoing :)
I’m not removing the `onPrint()` implementation for the cli-repl here because, while that might also fix this problem, I think we should stick to using a single source of truth for the output stream of the cli-repl.
> fix: guard against double print from console.log()

- packages/build/src/download-center.ts
I think we can do what `mongocli` does and add more distributions to the rpm.
```
maurizio ~/Downloads $ docker run --rm -it -v $PWD/mongosh-0.5.0-x86_64.rpm:/mongosh-0.5.0-x86_64.rpm opensuse/leap bash
91cab0958513:/ # rpm -i mongosh-0.5.0-x86_64.rpm 
91cab0958513:/ # mongosh 
Current sessionID:  31394d3592d87bba9e239b00
Connecting to:      mongodb://127.0.0.1:27017
```
```
maurizio ~/Downloads $ docker run --rm -it -v $PWD/mongosh-0.5.0-x86_64.rpm:/mongosh-0.5.0-x86_64.rpm amazonlinux bash
bash-4.2# rpm -i mongosh-0.5.0-x86_64.rpm 
bash-4.2# mongosh
Current sessionID:  3141ffe94f80899c2fa196a4
Connecting to:      mongodb://127.0.0.1:27017
```
> chore: Add CentOS / SUSE / Amazon Linux for rpm in download center

- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/clr.ts
- packages/cli-repl/src/constants.ts
- packages/cli-repl/src/format-output.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/cli-repl/test/test-shell.ts
Don’t assume that `process.stdout.isTTY` is a good indicator
for coloring strings:
- Not all terminals have color support
- We should honour environment variables like `NO_COLOR`
- Not all formatted strings end up printed to stdout
Also, don’t tell the Node.js repl that we are working with a terminal
if we don’t know so for sure.
> chore: clean up color/tty handling core in cli-repl

- .nycrc
This might help resolve flaky CI coverage by avoiding coverage
for already-transpiled files.
> chore: ignore lib/ directories in .nycrc

- packages/shell-api/src/enums.ts
ServerVersions are used to determine whether a particular feature is available
in 'autocomplete'. This allows for autocomplete to work on latest mongodb.
> fix(shell-api): MONGOSH-381 update ServerVersions enum to include 4.4.1

- .evergreen/.install_node
- .evergreen/.setup_env
- packages/browser-repl/src/components/shell-output-line.spec.tsx
- packages/browser-repl/src/components/shell-output-line.tsx
- packages/browser-repl/src/components/shell-output.spec.tsx
- packages/browser-repl/src/components/shell-output.tsx
- packages/browser-repl/src/components/types/simple-type-output.tsx
- packages/browser-repl/src/components/types/stats-result-output.tsx
- packages/browser-repl/src/components/utils/inspect.spec.ts
- packages/browser-repl/src/components/utils/inspect.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-core/src/printable-bson.spec.ts
- packages/service-provider-core/src/printable-bson.ts
- packages/shell-api/src/shell-bson.ts
Update the formatting for several values in the browser REPL.
Since fixing this for Date objects consistently enabled doing
straightforward fixes for a few other issues, this addresses:
- COMPASS-4440 (Consistently formatting `Date` objects)
- COMPASS-4441 (Ignoring `undefined` results)
- MONGOSH-410 (`sh.status()` formatting)
- COMPASS-4465 (`ObjectId` formatting in nested objects)
> fix: correctly format several values in browser-repl

- .evergreen/.setup_env
Otherwise, we just build with any newer Node.js 12.x version,
unlike Windows.
This bug led to the 0.5.1 release happening with Node.js 12.18.4
on Windows and Node.js 12.19.0 on other platforms.
Let’s pick a consistent version. Pick 12.18.4 rather than 12.19.0
because we’re currently seeing Node.js deprecation warnings being
shown with 12.19.0 (until
https://github.com/mongodb-js/boxednode/pull/9 is merged).
> fix(build): set NODE_JS_VERSION in Unix CI

- scripts/generate-homebrew-formula.js
Pass version as a second argument when running as a standalone script
> Fix generate-homebrew-formula script

- scripts/publish-npm.js
Tiny inconvenience that we stumbled on during the release today:
In cases where new package was added to the repo and is published for the first time with the others the access rights check can return a false-positive while checking for access rights: the package is not on remote yet so read-write is not returned. In addition to checking the access rights we will additionally check if the package exists already to allow publishing new packages.
> Check if package exists while checking the access rights before publishing

- package-lock.json
- package.json
This prevents the `Buffer` deprecation warnings that were accidentally
displayed from the 0.5.1 release from showing up again by making sure
that our `process.execArgv === process.argv[1]` check in the cli-repl
runner works correctly.
> chore(deps): bump boxednode to 1.7.1

- packages/cli-repl/src/setup-logger-and-telemetry.ts
This PR is to keep Segment logs a bit cleaner by only sending `error.name` and
`error.code` to analytics.
Typescript eslint was complainging about `segment_id`, so fixes that as well.
> chore(cli-repl): send only error.name and error.code to segment

- packages/cli-repl/src/async-repl.spec.ts
- packages/cli-repl/src/async-repl.ts
- packages/cli-repl/src/cli-repl.ts
Split out the parts of the `CliRepl` class that are specific to async
evaluation and test them entirely.
> chore(cli-repl): split out async eval bits of CliRepl MONGOSH-436

- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
(Following up to https://github.com/mongodb-js/mongosh/pull/414#discussion_r525383389)
Remove the `Container` argument that the `ShellEvaluator` class took,
and instead handle `toggleTelemetry()` like `print()`/`console.log()`.
This moves the user-facing methods to the shell-api,
including adding documentation for them.
> chore(cli-repl): move toggleTelemetry to evaluation listener

- packages/cli-repl/test/e2e.spec.ts
- packages/java-shell/src/test/js/run-tests.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/shard.spec.ts
- testing/integration-testing-hooks.ts
Instead of having an odd double-async structure where you’d first
await the test server, then await the results of async methods on it,
just have a single class that provides async methods.
> chore(test): simplify mlaunch spawning a bit

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/repl-helpers.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
This is a partial implementation of
* MONGOSH-314
* MONGOSH-315
and picks up https://github.com/mongodb-js/mongosh/pull/381 again
now that it’s easier to test this. :)
> feat(cli-repl): add passwordPrompt() support MONGOSH-315

- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
- packages/shell-api/src/replica-set.spec.ts
We will reactivate the rs.init tests when we upgrade to 4.0 due to https://jira.mongodb.org/browse/NODE-2901
> Upgrade node driver to 3.6.3; deactivate rs.init tests

- package.json
- packages/java-shell/package-lock.json
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/ReadableServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt
- packages/java-shell/src/test/resources/URI.txt
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-core/src/readable.ts
- packages/service-provider-core/src/session-options.ts
- packages/service-provider-core/src/session.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/replica-set.ts
- packages/shell-api/src/session.spec.ts
- packages/shell-api/src/session.ts
- packages/shell-api/src/shard.spec.ts
- packages/shell-api/src/shard.ts
- packages/shell-api/src/shell-internal-state.ts
- testing/helpers.ts
This PR includes tickets:
- MONGOSH-444 - Create Session Object
- MONGOSH-445 - Session Object Methods
- MONGOSH-448 - Throw for unsupported sessions methods
- MONGOSH-446 - Transaction Methods
- MONGOSH-342 - Mongo.readPreference methods
- MONGOSH-449 - Investigate if reconnecting MongoClient will interfere with sessions
- If a user has an active session, then calls a command like `db.auth` or `db.setReadPreference` then nothing will error. However if they try to use the session again, any command will fail with `inactive session`. I think this behavior is acceptable and no further work is required from us because the user should expect that resetting connection-wide options or reauthenticating should close a current session.
For more information about driver sessions, see [the …
> Support for Sessions & Transactions

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
Babel aliases loop statements as 'scopable' which I was not expecting. This means that there's slightly different behavior between conditionals and loops, specifically that if a variable is introduced in the `test` expression of a loop then it is scoped only to the body of that loop.
This led to a bug where we were pushing a scope on the stack before visiting a while statement but never popping it (because we call `path.skip()` in order to traverse the subtree.) Scopes are popped in the `exit` call of the `scopable` expression, but this was not being called. The fix is to pop the scope at the end of the while expression - however if babel ever changes it so loops are not scopable then it'll break.
> Pop scope in async-rewriter after loops

- packages/async-rewriter/package-lock.json
- packages/async-rewriter/package.json
- packages/async-rewriter/src/async-writer-babel.ts
We list typescript and ts-node as dependencies in the top-level
package.json, so they should not be specified in the async-rewriter
package.json (and, more importantly, not as full dependencies
and rather as devDependencies).
> chore(async-rewriter): remove unused typescript deps

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
- packages/java-shell/src/test/kotlin/com/mongodb/mongosh/CursorTest.kt
- packages/java-shell/src/test/kotlin/com/mongodb/mongosh/util.kt
- packages/java-shell/src/test/resources/collection/aggregateWithNegativeBatchSize.expected.txt
- packages/java-shell/src/test/resources/cursor/tailable.expected.txt
- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
This PR includes:
1. commit 170142901052e0e167dae068c8945c2fcf450f81 from @addaleax that allows to set custom result handler
2. my commit that adds custom result handler to java shell so cursor is not fetched before it's returned to user
BTW: after these commits are merges java shell will not need `rawValue` field in shell result, so maybe it should be removed.
> [java-shell] Don't fetch cursor twice

- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
We disabled caching the database objects on the driver level so that
we would be able to access the same database multiple times with
different options, and not get the same cached instance (with the
options from the first call) every time.
This has the major drawback that every time we do any operation that
uses such a database object, we create a new one. Due to the way
the driver creates those objects, they essentially cannot be gargage
collected for the lifetime of the `MongoClient` instance.
This is a memory leak that can crash mongosh.
To resolve this, we perform our own caching of the database instance
that also takes the options into account.
> fix(service-provider-server): perform db caching MONGOSH-464

- packages/cli-repl/src/line-by-line-input.spec.ts
- packages/cli-repl/src/line-by-line-input.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/test-shell.ts
- packages/java-shell/src/test/js/run-tests.ts
Instead of controlling whether `data` events are emitted or not
in the LineByLineInput implementation, make LineByLineInput
an actual Readable stream and emit data that way.
This ensures that the relative timing of `'data'` events is the
same as it would otherwise be for streams, which the Node.js
readline implementation expects.
> fix(cli-repl): turn LineByLineInput into Readable stream MONGOSH-401

- .evergreen.yml
- config/build.conf.js
- packages/build/src/index.ts
- scripts/download-linux-artifact.js
- testing/download-mongodb.ts
This is basically a revamp the evergreen config:
- Rename CI tasks to be more descriptive
- Add CI tasks to verify that the Linux artifacts actually run on
their target platforms (we previously had jobs in CI that were
*named* to imply that they were using RHEL 8.0 and Debian 10
but did not actually run those OSes in any way, only built
packages targeting those)
- Add test_m??x tasks where ?? represents the target server version
for testing
- Update the mongod download script to account for those different
server versions across the supported OSes
- Move darwin testing off the codesign machine (because there is
only one host for that) – compiling still takes place there
- Update the build config script to account for the fact that
the `revision` expansion only represents the *base* …
> chore(ci): add jobs for testing across mongod versions MONGOSH-312

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/ConsoleLogSupport.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShell.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellContext.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellConverter.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellEvaluator.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/result/Cursor.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/result/FindCursor.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/BaseMongoIterableHelper.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/Cursor.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/util.kt
I split `MongoShellContext` into smaller parts:
* `MongoShellContext` now contains only GraalVM context and code for creating JS functions
* `MongoShellConverter` knows how to convert JS <-> Java values
* `ConsoleLogSupport` initializes console.log function 
* `MongoShellEvaluator` instantiates shell evaluator and shell internal state + add some constructors like ISODate
> [java-shell] Refactor MongoShellContext

- packages/browser-repl/src/components/password-prompt.less
- packages/browser-repl/src/components/password-prompt.tsx
- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
Adds a password prompt feature to the browser-repl for parity with
the CLI.
> feat(browser-repl): support passwordPrompt() MONGOSH-315

- packages/cli-repl/test/e2e.spec.ts
Example failure: https://evergreen.mongodb.com/task/mongosh_win32_test_m42x_win_7ec01ec01310c9270e83925c4bc782c9a1882427_20_11_26_12_29_44
> chore(test): do not fail tests if cleaning up fake homedir fails

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/test/repl-helpers.ts
With a similar purpose like https://github.com/mongodb-js/mongosh/pull/449.
Example failure: https://evergreen.mongodb.com/task/mongosh_win32_test_m42x_win_7ec01ec01310c9270e83925c4bc782c9a1882427_20_11_26_12_29_44
> chore(cli-repl): use separate tmpdir for userId persistence test

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
Make sure we clean up all resources even in the case of a test failure.
> chore(cli-repl): close MongoshNodeRepl in integration test

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt
- packages/java-shell/src/test/kotlin/com/mongodb/mongosh/CollectionTest.kt
- packages/java-shell/src/test/resources/collection/createIndex.expected.1.txt
- packages/java-shell/src/test/resources/collection/createIndex.expected.txt
- packages/java-shell/src/test/resources/collection/createIndex.js
- packages/java-shell/src/test/resources/collection/createIndexes.expected.txt
- packages/java-shell/src/test/resources/collection/createIndexes.js
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
Note that it contains a small change in core code in `collection.ts`.
`dbOptions` there were not passed as last argument to `serviceProvider.createIndexes` that caused `Arity error - expected: 3 actual: 4`
> [java-shell] Fix createIndexes. Core did not pass dbOptions as a last argument

- config/build.conf.js
In particular, map `darwin_codesign` to `darwin` because that
influences the path where the release artifact ends up being put.
> fix(config): map build variants correctly

- config/eslintrc.base.js
- packages/cli-repl/src/cli-repl.spec.ts
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/change-stream-cursor.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/toIterator.spec.ts
- packages/shell-api/src/toIterator.ts
- Make all cursor types async iterables (this is just for us,
the async rewriter does not support async iteration at this point)
- Use the same iteration in `toIterator` for all input types
- Add tests for `toIterator`
- Add an e2e test to cover this feature
> chore(shell-api): refactor and test toIterator

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/AdminServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt
- packages/java-shell/src/test/resources/collection/dropIndex.expected.1.txt
- packages/java-shell/src/test/resources/collection/dropIndex.expected.txt
- packages/java-shell/src/test/resources/collection/dropIndexes.expected.1.txt
- packages/java-shell/src/test/resources/collection/dropIndexes.expected.txt
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/mongo.ts
There are currently a few service provider methods (buildInfo,
getCmdLineOpts, dropIndexes, reIndex, convertToCapped)
that just do runCommand so those should not be in the SP API.
> chore(service-provider-core): remove extra methods MONGOSH-451

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
The last argument to each serviceProvider method is generally DbOptions, which are database-wide options that need to be passed to the drivers `getDatabase` method. We currently don't have anything we set there, but it's likely we will in the future, so right now that argument is optional and left off in most cases. There was a bug where the createIndexes method was passing command options as database options, which would mean those options would be ignored.
Because the drivers can either accept options as part of the index specification or as a separate options object, we now pass both instead of only within the index spec.
> MONGOSH-478 - Pass session correctly to createIndexes

- .nycrc
- packages/browser-runtime-core/src/open-context-runtime.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/shell-evaluator/src/shell-evaluator.ts
Any user of `ShellEvaluator` already has access to the
`ShellInternalState` instance, and therefore doesn't need
a method for forwarding this.
As drive-by changes, fix a small inconsistency that @gribnoysup 
pointed out to me and update the .nycrc to exclude explicit
test directories from coverage.
> chore(shell-evaluator): remove setEvaluationListener

- .nycrc
- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/build/src/generate-input.spec.ts
- packages/build/src/generate-input.ts
- packages/errors/index.spec.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/change-stream-cursor.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/mongo.spec.ts
This measured 95.0033 % line coverage on one run locally, so it
*technically* meets the acceptance criteria of MONGOSH-490,
but we’ll probably want to add a few more tests for wiggle room before
we bump the minimum coverage threshold :)
Current coverage report with this PR: [coverage.zip](https://github.com/mongodb-js/mongosh/files/5660758/coverage.zip)
> chore(test): add various more tests

- packages/cli-repl/test/e2e-direct.spec.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/shell-api.spec.ts
This fixes the breaking behavioral change when connecting to a specific node. The old shell directly connected to a node as specified whereas we so far tried to establish a connection to e.g. the primary node of a replica set.
The default behavior now is to add the `directConnection=true` query parameter to the connection string automatically _except_:
* the `replicaSet` query parameter is present in the connection string
* the connection string uses the `mongodb+srv://` scheme
* the connection string contains a seed list with multiple hosts
> fix(service-provider-core): Default to direct connection to specified node MONGOSH-465

- packages/service-provider-core/src/readable.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/bulk.ts
- packages/shell-api/src/integration.spec.ts
Due to the Node driver decision here: https://jira.mongodb.org/browse/NODE-2602 we need to update our code to expect only index names from createIndexes instead of the raw server result.
> MONGOSH-501 createIndex return index name

- packages/shell-api/src/helpers.spec.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shard.ts
- testing/shard-test-fake-data.ts
Refactor `getPrintableShardStatus()` to be more parallelized then it
already was, and add unit tests based on a fake `config` database.
> chore(shell-api): refactor and test getPrintableShardStatus MONGOSH-490

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
- packages/async-rewriter/src/await.spec.ts
- packages/async-rewriter/src/await.ts
- packages/async-rewriter/src/symbol-table.spec.ts
- packages/async-rewriter/src/symbol-table.ts
This covers edge cases and removes essentially duplicate code to increase coverage for `async-rewriter`.
> chore(test): increase test coverage for async-rewriter

- packages/browser-runtime-core/package.json
… because otherwise this makes installing the compass-shell in compass
fail because cli-repl requires Node.js 14 according to its package.json.
> fix(browser-runtime-core): drop unused dependency on cli-repl package

- packages/shell-api/src/integration.spec.ts
The references bug has been resolved, this just adds unit tests
(in particular, actually tests explaining `.aggregate()` calls
instead of duplicating the test for `.find()`).
> chore(test): test aggregate + explain behavior MONGOSH-203

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- packages/autocomplete/package-lock.json
- packages/autocomplete/package.json
As a minor part of MONGOSH-463 (mongodb 4.4 support).
> deps(autocomplete): update mongodb-ace-autocompleter to 0.4.14

- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/explainable.ts
- packages/shell-api/src/helpers.ts
Do the same thing the old shell does. While the driver would also just
accept boolean values, we perform the mapping ourselves so that e.g.
`.getVerbosity()` still returns the mapped value (like the old shell).
> fix(shell-api): support legacy explain verbosity values MONGOSH-204

- packages/cli-repl/test/e2e.spec.ts
This ensures that the test-e2e runs in CI also check that the addon is
actually working in the compiled binary.
> chore(test): verify that fle addon is available in executable

- packages/cli-repl/src/mongosh-repl.ts
We’re explicitly calling `process.exit()` in the CLI repl once the
REPL has been closed, stops all asynchronous operations, including
writing to asynchronous stdio streams.
We should at least wait until all currently pending output has been
written to stdout before doing so. This seems fix a problem that
I cannot reproduce locally, but @gribnoysup can. :)
> fix(cli-repl): wait for output drain before exiting

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/test/repl-helpers.ts
To reproduce you can try doing something like `echo "print('Hello' + ' ' + 'World')" | mongosh --nodb | grep -q "Hello"` in your shell (at least this is a way to reproduce on macos). The reason for this is that `q` argument forces `grep` to exit as soon as the match is found, destroying the stream after it is done, causing shell to throw:
The fix adds an 'error' listener to the passed output stream and reports caught issues to the telemetry
> fix(cli-repl): Catch output stream errors to avoid uncaught exceptions

- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
Instead of replacing the Node.js REPL autocompletion function, use both
that and our own autocompletion and merge the results in order to
provide expected results to users.
> fix(cli-repl): merge Node.js REPL and mongosh autocompletion MONGOSH-164

- packages/i18n/src/locales/en_US.ts
- packages/service-provider-core/src/all-transport-types.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/explainable.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/shard.ts
Add `.explain()` support for non-cursor methods. In the process,
also fix up the options handling for `collection.remove()`, which
previously passed the `justOne` option to the driver instead of
handling it in mongosh (which was ignored by the driver).
> feat(shell-api): support non-cursor explainable methods MONGOSH-185

- packages/cli-repl/test/e2e-analytics.spec.ts
Adds connectivity tests for analytics nodes.
The test spawns 4 nodes in a replica set, 3 nodes with voting, 1 passive node (priority: 0 and votes: 0). The passive node also has the `nodeType: 'ANALYTICS'` tag.
> chore(test): Add Analytics node connectivity tests MONGOSH-418

- .evergreen.yml
- packages/connectivity-tests/test/all.sh
- packages/connectivity-tests/test/atlas.sh
- scripts/print-expansions.js
This PR adds the following tests for remote servers following the mongosh test matrix
All secrets are added in evergreen config, hopefully everything is wired up together correctly 🤞
> test(connectivity-tests): Add connectivity tests for atlas and data lake MONGOSH-419

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
MongoDB on desktop returns `{ok: 1.0}` but MongoDB Atlas returns `{ok: 1}`
> [java-shell] don't require runCommand to return double value in "ok" field

- packages/cli-repl/test/e2e-tls.spec.ts
See the comment in the test – hopefully, this lets CI finish
on Windows now.
> fix(test): shut down TLS-based servers through the shell

- .evergreen.yml
- .evergreen/Check.ps1
- .evergreen/CompileAndUpload.ps1
- .evergreen/InstallNode.ps1
- .evergreen/SetupEnv.ps1
- .evergreen/Test.ps1
- scripts/prep-fle-addon.sh
I noticed due to some other build failures that the scripts we were executing inside powershell do not fail as expected.
Code declared in a `shell.exec` step is piped into the powershell executable via stdin (see https://github.com/evergreen-ci/evergreen/blob/master/agent/command/shell.go#L137). This treats every line completely separate in powershell and powershell will always continue execution. A failing line is disregarded (regardless of `$ErrorActionPreference`).
The scripts are now moved to dedicated `.ps1` files and are started using `subprocess.exec`.
> chore(ci): move powershell scripts into dedicated files

- packages/build/src/generate-input.spec.ts
- packages/build/src/generate-input.ts
- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/setup-logger-and-telemetry.ts
- packages/cli-repl/test/e2e-tls.spec.ts
As stumbled upon during MONGOSH-418 (see #496), the `minimist` arguments parser will explicitly set default values for boolean flags even when the flags are not provided (see also https://github.com/substack/minimist/issues/94). This makes it impossible to distinguish between a default value and a value specified by the user.
Passing on these flags automatically interferes with parsing the query parameters of the connection string. Explicit options passed to `MongoClient` will always override connection string query parameters.
This PR replaces `minimist` with `yargs-parser`. `yargs-parser` does not set default values for flags that are not specified. All our flags defaulted to `false` with `minimist`. Their value now still qualifies as _falsly_ and the migration thus should have no user …
> chore(cli-repl): replace minimist with yargs-parser

- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
Add support for the `cls` (clear screen command) through using
`console.clear` in Node.js and using the existing method for the
browser REPL.
As drive-by cleanups:
- Move other global methods to the `ShellApi` class and document
them accordingly
- Use decorators on the `ShellApi` methods that are exposed as
bash-like commands instead of special-casing them in the
shell-evaluator package.
> feat(shell-api): add cls support MONGOSH-239

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/config-directory.spec.ts
- packages/cli-repl/src/config-directory.ts
- packages/cli-repl/src/index.ts
- packages/cli-repl/src/run.ts
- packages/cli-repl/test/e2e.spec.ts
Store config and history in `%APPDATA%` on Windows, and the log
files in `%LOCALAPPDATA%` since roaming them is not meaningful.
The location for other OSes remains `~/.mongodb/mongosh`.
> fix(cli-repl): store files in APPDATA on Windows MONGOSH-230

- packages/browser-repl/src/components/types/cursor-iteration-result-output.tsx
- packages/browser-repl/src/components/types/cursor-output.spec.tsx
- packages/browser-repl/src/components/types/cursor-output.tsx
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/format-output.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/change-stream-cursor.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/enums.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/result.spec.ts
- packages/shell-api/src/result.ts
Make the iteration batch size for cursors controllable through
`.batchSize()` (the ticket suggested using `DBQuery.shellBatchSize`
for this, like the old shell did, but we’ve deprecated that and
are already explicitly telling users to use `.batchSize()` instead)
and print `Type "it" for more` in the shell when the current cursor
is iterable.
> feat: control iteration batch size + add 'Type "it"' prompt MONGOSH-361

- packages/browser-runtime-electron/src/electron-interpreter-environment.ts
`breakOnSigint` defaults to `true` in modern node version but is defaults to `false` in the older ones. This PR explicitly allows to interrupt vm for consistency
> feat(browser-runtime-electron): Allow to interrupt vm on sigint COMPASS-4513

- packages/service-provider-server/package.json
Seems like typescript is not always able to pick up types of this package correctly without `types` being specified in `package.json`
> fix(service-provider-server): Specify types export in the package.json

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- packages/browser-runtime-core/src/autocompleter/shell-api-autocompleter.spec.ts
- packages/browser-runtime-core/src/autocompleter/shell-api-autocompleter.ts
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/repl-helpers.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/shell-internal-state.spec.ts
- packages/shell-api/src/shell-internal-state.ts
- packages/types/src/index.ts
Also implicitly address MONGOSH-291 by adding a 200ms timeout after
which cached results are used (which may seem either high or low,
so I’m happy to adjust it – see also the comment about that value).
> feat(autocomplete): autocomplete collection names MONGOSH-335

- packages/shell-api/src/shell-internal-state.spec.ts
- packages/shell-api/src/shell-internal-state.ts
This augments the default shell prompt to show `Atlas Data Lake >` when connected to an ADL. This works like the `Enterprise` prefix.
> feat: show Atlas Data Lake hint in prompt

- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/MongoShellEvaluator.kt
- packages/java-shell/src/test/resources/literal/ISODate.expected.txt
- packages/java-shell/src/test/resources/literal/ISODate.js
Issue in JDBC driver: https://github.com/DataGrip/mongo-jdbc-driver/issues/13
> [java-shell] support dates without separators e.g. ISODate('20121219')

- packages/compass-shell/electron/index.js
- packages/compass-shell/electron/renderer/index.js
- packages/compass-shell/package-lock.json
- packages/compass-shell/package.json
- packages/compass-shell/src/modules/runtime.js
- packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
- packages/node-runtime-worker-thread/src/index.ts
Integrates new runtime in compass shell behind a feature flag to make further development easier. As promised in #533 it's much much smaller than the first patch in this epic 😄
> feat(compass-shell): Integrate worker thread runtime in compass shell COMPASS-4556

- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
The best solution I could find was connecting twice, once with the autoencryption options entirely removed. This connection runs buildInfo, and if it's not enterprise, then it will close the connection and error. If it is enterprise, then it will close the connection and reconnect with the autoencryption options included.
TODO: the message that is thrown should be written & reviewed by the legal team per @mmarcon
> MONGOSH-523 - AutoEncryption only run on enterprise

- .evergreen.yml
Just realized that this is fairly easy to do, and this might be helpful
for us in figuring out where we could improve test coverage.
> chore(ci): upload coverage tarball for CI runs

- .evergreen.yml
Evergreen implements bash script execution by piping into bash.
This is not good, because it means that commands might actually
end up in a subprocess’s stdin instead of bash itself, leading to
commands being skipped. Use curly brackets to make sure that bash
has read the entire script before it starts executing it.
(See https://jira.mongodb.org/browse/EVG-13667)
> chore(ci): wrap bash scripts in curly brackets

- packages/shell-api/src/database.ts
Based on seeing this output in CI, it seems reasonable to assume that
`listCollections().toArray()` can return `undefined`, even if the TypeScript
definitions don’t indicate that.
[2021/01/18 10:13:20.959] (node:18714) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
[2021/01/18 10:13:20.959]     at Proxy._getCollectionNames (/data/mci/63c1249309c29dbf51f08a235fcdfa5e/src/packages/shell-api/src/database.ts:144:41)
> fix(shell-api): default to empty list for listCollections()

- package-lock.json
- package.json
- packages/node-runtime-worker-thread/package.json
- testing/download-mongodb.ts
This is required for FLE testing and makes mongocryptd bundling easier.
> chore(ci): run tests against enterprise server versions

- packages/shell-api/src/bulk.ts
- packages/shell-api/src/field-level-encryption.ts
`import type` allows loading only the types without actually creating
circular dependencies between the files at runtime.
> chore(shell-api): avoid using any to avoid circular references

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/async-writer-babel.ts
Tiny fix for async rewriter: it currently throws unexpectedly when array has holes. This PR fixes the issue by skipping them during AST traversal
> fix(async-rewriter): Ignore empty items in the arrays when traversing ast

- packages/browser-repl/.storybook/webpack.config.js
- packages/browser-repl/config/empty.js
- packages/browser-repl/config/webpack.config.base.js
- packages/service-provider-core/src/connection-string.ts
- packages/service-provider-core/src/whatwg-url.ts
Fixes a few issues with `service-provider-core` compatibility with the browser environment:
- Makes `url` and `whatwg-url` an "optional" import so `browser-repl` can ignore them and removes it from the `browser-repl` build by aliasing library to an empty module
- Fixes serialization issue with auth string occuring due to the browser URL behavior. Having a rouge `@` in the hosthame when username/password are not provided was causing `ConnectionString.clone` to basically produce a different url when no credentials were passed
> fix(service-provider-core, browser-repl): Make ConnectionString compatible with browser environment

- config/build.conf.js
- packages/build/src/config.ts
- packages/build/src/do-upload.ts
- packages/build/src/evergreen.ts
- packages/build/src/redact-config.ts
Add a way to write the S3 URL for an uploaded package to a specified
location on disk. This is useful for MONGOSH-506, because it makes it
possible to store that file in a location that evergreen can understand
on its own (i.e. it doesn't need to use JS code to figure out where
the artifact is stored) and use it as a pointer to the actual artifact
URL.
> chore(build): add way to write uploaded URL to file

- packages/compass-shell/electron/renderer/index.js
- packages/compass-shell/src/modules/runtime.js
As discussed in [this thread](https://mongodb.slack.com/archives/GJ2CBBY86/p1611321819035300), worker runtime uses mongodb driver 4, but the connection options are currently passed from mongodb driver 3, this causes some "deprecated param" issues while runtime is connecting. To work around the issue, this PR removes deprecated connection options before passing options to the runtime
> fix(compass-shell): Exclude deprecated driver 3.x options before passing them to the worker runtime

- packages/build/src/npm-packages.ts
- scripts/docker/centos7-build.Dockerfile
- scripts/docker/centos7-package.Dockerfile
Adapted the CentOS docker images to include git 2.24. By default, CentOS comes with git v1.8.3.1 which is way too old for `lerna` to be able to bump the package versions.
It went undetected, as we only bump the version when we tag a commit.
> chore(build): ensure git 2.24 is installed in centos MONGOSH-505

- packages/cli-repl/test/e2e-auth.spec.ts
The `createRole` command in the test case used a `serverAddress: {}` instead of `serverAddress: []` (see https://docs.mongodb.com/manual/reference/command/createRole/index.html#dbcmd.createRole).
> chore(cli-repl): fix createRole test case

- .evergreen.yml
- packages/build/src/npm-packages.ts
- packages/build/src/release.ts
- scripts/evergreen-release.js
Added a new "evergreen-release" command `bump` which just bumps the package.json versions to the potentially present tag version.
I chose to always bump the version now, as for example the E2E tests verify the version that is output by `mongosh --version`. To avoid any additional issues with the version, it's now always bumped. I left the explicit bump also in for the other commands to ensure any other potential changes to the version will always be forced correctly when releasing.
> chore(build): always bump package version number MONGOSH-505

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- Use word-boundary matching instead of substring tests for
top-level identifiers.
- Make sure that completions for collections aren’t accidentally
provided for function calls.
- Provide completions for `rs.` and `sh.` only if immediate methods
on these objects are being completed.
> fix(autocomplete): return fewer false positives MONGOSH-507

- packages/shell-api/src/shell-internal-state.ts
Make sure we’re not running into unhandled rejections when updating
information after a database switch.
> fix(shell-api): catch Promise rejections caused by db switch

- .evergreen.yml
This activates that a real publish is run on `release_publish`. Was disabled for testing the tagging behavior.
Evergreen is now configured properly so that when we tag a commit with a release tag it will also run `release_publish`.
So far this does not include separating the publishing from the rest, i.e. tagging with a release tag will still run the whole compile, package, etc. This is tracked by https://jira.mongodb.org/browse/MONGOSH-554
> chore(build): remove safeguard from testing MONGOSH-505

- packages/shell-api/src/replica-set.ts
- packages/shell-api/src/shard.ts
Do the same thing we do for printing `Mongo` and
`ClientEncryption` classes.
> fix(shell-api): use redactPassword in rs/sh print methods

- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/service-provider-server/src/compass/compass-service-provider.ts
Tiny fix to `CliServiceProvider` constructor types and dependants
> fix(service-provider-server): Fix constructor types in CliServiceProvider

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/bulk.spec.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/change-stream-cursor.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/deprecated.ts
- packages/shell-api/src/explainable-cursor.spec.ts
- packages/shell-api/src/explainable.spec.ts
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/index.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
- packages/shell-api/src/plan-cache.spec.ts
- packages/shell-api/src/plan-cache.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/replica-set.ts
- packages/shell-api/src/session.spec.ts
- packages/shell-api/src/shard.spec.ts
- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-bson.ts
Mark methods as deprecated and skip them for autocompletion.
> feat(shell-api,autocomplete): skip deprecated methods MONGOSH-509

- packages/cli-repl/test/e2e-direct.spec.ts
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/AdminServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/service-provider-core/src/admin.ts
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
If `readPreference` has been explicitly set, either through
a) the connection string or b) by using `setReadPref()`,
then pass it for `db.runCommand()` as well.
The reason we’re not always using it is that the driver will
report it back to use as `primary` by default, which would then
break `db.runCommand()` for almost all calls when we’re connected
to a secondary.
As part of this, update the default `Mongo` instance to also
report the connection string, like a programmatically created `Mongo`
instance would (and like it worked in the old shell).
(Also addresses MONGOSH-557)
Refs: https://docs.google.com/document/d/10FTlhliWtg_XquUGbEmZQ7ccUiImMLlBT5Qlm2O1ZxI/edit?pli=1
People don’t necessarily expect `show` to follow the same rules as
other shell calls, and expect it to work even when …
> fix(shell-api): use readPref for runCommand if explicitly set MONGOSH-508

- config/build.conf.js
To be reverted after the 0.7.0 release.
> feat(build): exclude mongocryptd from packaging

- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/fixtures/asi-script.js
This verifies that the behavior is the same as in the old shell.
> chore(test): add ASI script test

- .evergreen/.setup_env
> chore(ci): use git 2.x on RHEL hosts

- packages/node-runtime-worker-thread/src/worker-runtime.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/service-provider-server/src/compass/compass-service-provider.ts
Tiny fix for unsupported shell apis to reject correctly:
> refactor(node-runtime-worker-thread): Use Compass service provider to correctly resolve unsupported shell api methods

- packages/node-runtime-worker-thread/src/index.spec.ts
- packages/node-runtime-worker-thread/src/index.ts
@mcasimir spotted that the prompt is missing while we were trying out the new runtime, this fixes the issue by actually making the method callable on the worker runtime
> fix(node-runtime-worker-thread): Expose getShellPrompt method on the childProcessRuntime

- packages/build/src/npm-packages.spec.ts
- packages/build/src/npm-packages.ts
The underlying issue with our CI release pipeline is that we bump the version of the packages only in the CI environment. This leads to uncommitted changes in the git repository. The `lerna publish` command will fail in this case and the `--force-publish` option does not have any effect (see also https://github.com/lerna/lerna/issues/2550).
The alternative would be to do a dummy commit in the CI environment before publishing. I chose against this to at least keep consistency between the commit hash of the published package information and the tagged version. While we still knowingly have tagged versions without the package version being properly set.
This PR includes:
- uses a helper function to ensure spawn.sync calls throw if not successful
- before lerna publish marks known changed …
> fix(build): ensure to check spawn result and assume files unchanged MONGOSH-521

- packages/compass-shell/src/modules/runtime.js
Temporary workaround for NODE-3061
> fix(compass-shell): Remove checkServerIdentity option that is incompatible with driver 4

- packages/compass-shell/src/modules/runtime.js
In #597 I forgot to actually pass the emitter to the runtime 😬
> feat(compass-shell): Connect appRegistry to worker runtime telemetry

- .gitignore
- packages/build/src/npm-packages.spec.ts
- packages/build/src/npm-packages.ts
Ignore the locally unused but in CI generated `.npmrc`.
> fix(build): ignore .npmrc MONGOSH-521

- packages/build/src/npm-packages.spec.ts
- packages/build/src/npm-packages.ts
`name` would be the package name, e.g. `@mongosh/build`, which would
not be present in that form on the file system.
We also need to use `lerna list --all`, since otherwise private
packages are not included.
> fix(build): fix markBumpedFilesAsAssumeUnchanged file location

- .evergreen/test-package-win32.sh
Apparently, spawn hosts are not particularly isolated either,
and can be re-used:
[2021/02/03 12:00:30.604] + cd '/cygdrive/c/Program Files/'
[2021/02/03 12:00:30.604] + mkdir mongosh
[2021/02/03 12:00:30.618] Starting script on SSH host
[2021/02/03 12:00:30.618] mkdir: cannot create directory 'mongosh': File exists
[2021/02/03 12:00:30.618] Command failed: error waiting on process 'ee956461-7225-4eae-9dda-d9bb8237be7b': exit status 1
[2021/02/03 12:00:30.619] Task completed - FAILURE.
> fix(ci): rimraf mongosh install dir on ssh host

- packages/browser-repl/src/components/shell-output-line.tsx
- packages/cli-repl/src/format-output.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/result.spec.ts
- packages/shell-api/src/result.ts
Treat AggregationCursor instances like Cursor instances in the output
handling functions.
Simplify `CursorIterationResult` so that we don’t need a separate
class for its printable version, since it is already supposed
to be printable.
> fix: print AggregationCursor output correctly MONGOSH-562

- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/field-level-encryption.ts
This was incorrect before (as mentioned in the ticket), but now
that we’ve updated `mongodb-client-encryption` this actually
becomes necessary, since no valid value for `masterKey` can
be specified when the kms is `local`.
> fix(shell-api): fix KeyVault.createKey signature MONGOSH-546

- packages/compass-shell/src/modules/runtime.js
driver 3+ allows buffers and file paths to be passed as some ssl* options, driver 4 does not allow for that and node driver team is [not sure if they want to support this or not](https://jira.mongodb.org/browse/NODE-3067), to work around the issue we pick file paths directly from connection-model instead of using processed options that connection mode
> feat(node-runtime-worker-thread): Transform ssl* options to their driver 4 compatible version COMPASS-4611

- config/build.conf.js
This reverts commit a83b40fd2d4b8f2485dc17175f656a5d77017e68.
(To be merged after the 0.7.0 release is done.)
> Revert "feat(build): exclude mongocryptd from packaging (#591)"

- .evergreen/.setup_env
Apparently, weird things happen otherwise when running for one
Node.js version on a host and then later a different Node.js version
on the same host.
> fix(ci): add explicit nvm use statement

- packages/cli-repl/src/async-repl.ts
- packages/cli-repl/src/mongosh-repl.ts
Instead of the default of 30. This matches the old shell:
https://github.com/mongodb/mongo/blob/c575750f73b7a490a60919777dc49c45ec4f2e0c/src/mongo/shell/linenoise.cpp#L144
> fix(cli-repl): set history limit to 1000

- .evergreen.yml
- .evergreen/package-and-upload-artifact.sh
- .gitignore
- packages/cli-repl/src/run.ts
- packages/cli-repl/src/smoke-tests-fle.ts
- packages/cli-repl/src/smoke-tests.spec.ts
- packages/cli-repl/src/smoke-tests.ts
- packaging/deb-template/mongosh/DEBIAN/control
- scripts/docker/run.sh
- scripts/docker/ubuntu16.04-deb.Dockerfile
- scripts/docker/ubuntu18.04-deb.Dockerfile
- scripts/docker/ubuntu20.04-deb.Dockerfile
Run a FLE script that verifies that automatic FLE using mongocryptd
works. This uses the same endpoint as the connectivity tests.
This also involves changing the mongocryptd binary we use for .deb
packages: The one from Ubuntu 16.04 only works there, so we use
the one from Ubuntu 18.04 instead. Ubuntu 16.04 users will have
to install mongocryptd manually (unless we decide to offer multiple
.deb packages at some point).
> chore(ci): add FLE smoke test MONGOSH-543

- packages/compass-shell/src/modules/runtime.js
- packages/compass-shell/test/setup.js
`compass-shell` tests are currently failing on master due to `URL` mock and and `dataService` mocks being not up to date. This PR fixes the issue by removing URL mock that we don't really need anymore and restructuring runtime module so that un-mocked method is not reachable in tests (we are not testing it yet this is why I decided not to add it to the mocks yet)
> fix(compass-shell): Remove URL mock and move getConnectionOptions so that tests don't break

- packages/build/src/github-repo.spec.ts
- packages/build/src/github-repo.ts
- packages/build/src/run-draft.ts
Upload and draft were using different names for the tarball so draft could not find it. Also includes increasing coverage for the `github-repo`.
> chore(build): fix tarball name construction in draft

- packages/cli-repl/src/smoke-tests-fle.ts
- packages/cli-repl/src/smoke-tests.spec.ts
Don’t skip fully for 4.0, and rather only skip the FLE test when
connected to a 4.0 server.
> chore(cli-repl): refactor smoke test skipping

- package.json
- packages/cli-repl/src/smoke-tests-fle.ts
- packages/service-provider-core/package-lock.json
- packages/service-provider-core/package.json
- packages/service-provider-core/src/admin.ts
- packages/service-provider-core/src/all-fle-types.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/field-level-encryption.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shell-api.spec.ts
This PR includes the use of the types provided by `mongodb-client-encryption` as well as support of the new Azure and GCP KMS providers.
> chore: update FLE API MONGOSH-540

- package-lock.json
- package.json
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/field-level-encryption.ts
- packages/shell-api/src/mongo.ts
- testing/fake-kms.ts
(Blocked on #553, and thus still hitting a slightly moving target here)
Provide fake KMS services in order to test local, AWS, GCP and Azure
FLE integration.
Also introduce an undocumented (unless we want to document it)
`bypassAutoEncryptionFully` that lets us create `Mongo` objects
which do not try to perform automatic encryption themselves,
but which still provide working `.getClientEncryption()` and
`.getKeyVault()` methods (which is otherwise impossible).
> chore(shell-api): add FLE integration tests MONGOSH-496

- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/field-level-encryption.ts
- packages/shell-api/src/mongo.ts
Rename the previously introduced option with a better name, in order
to provide a good public API, and add a check that verifies that this
is not used in combination with `schemaMap` (because the options would
contradict each other).
> feat(shell-api): add/rename explicitEncryptionOnly option MONGOSH-590

- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
> fix(compass-shell): make max height 95% view height instead of 800 pixels COMPASS-4629

- packages/compass-shell/src/modules/adapt-driver-v36-connection-params.js
- packages/compass-shell/src/modules/adapt-driver-v36-connection-params.spec.js
If options are added even when nothing was extracted from 3.6 options, mongodb driver would still try to use connection options and will not connect successfully
> fix(compass-shell): Do not add authMechanismProperties when not present

- packages/cli-repl/src/smoke-tests.spec.ts
- packages/cli-repl/test/e2e-fle.spec.ts
- packages/cli-repl/test/fixtures/redirect-network-io.js
- packages/shell-api/src/field-level-encryption.spec.ts
- testing/fake-kms.ts
- testing/integration-testing-hooks.ts
Add integration tests for the AWS-related FLE command line options.
This involves:
- The fake KMS HTTP services can now be spun up as actual HTTP servers
- We inject a script into the target process that redirects network
connections to such HTTP servers
- We provide a utility method for adding the downloaded mongodb
package’s binary path to the PATH environment variable, so that
tests that use it can access `mongocryptd`
- We insert fake data into a test database that the driver will attempt
to decrypt (but fail), and make a request to the fake AWS KMS
server in the process that we take as validation that the AWS
options were correctly passed.
> chore(cli-repl): add FLE option integration test

- packages/i18n/src/locales/en_US.ts
As suggested in MONGOSH-565, this PR makes the copy for the docs message/link shorter.
This is what it looks like with this change:
> MONGOSH-565: Tweaked copy for docs link

- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
This aligns mongosh with the legacy shell.
> fix(shell-api): make UUID() generate random UUID MONGOSH-593

- .evergreen.yml
See MONGOSH-592, this should be skipped until SERVER-54508 is resolved.
> chore(ci): skip latest server alpha on macOS for now

- packages/cli-repl/src/line-by-line-input.spec.ts
- packages/cli-repl/src/line-by-line-input.ts
First half of addressing MONGOSH-586.
Before this commit, what could happen in blocked mode is that:
- There is data that was entered on the input stream but not yet
released
- Ctrl+C was received
- The handler for released data would do something that leads
to another `_flush()` call
- This inner `_flush()` call would start emitting data while
we were already doing so, which is not something that the
readline implementation expects from its input stream
(which is arguably a bug in Node.js)
Concretely, in the situation described in the ticket:
1. Autocompleting during `.editor` puts the stream into blocking
mode (the other half of the ticket)
2. Pressing Ctrl+C to abort that means that the Ctrl+C character
is forwarded immediately
3. The readline implementation reads it and emits its …
> fix(cli-repl): do not recursively push() in LineByLineInput MONGOSH-586

- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
This is the second half of MONGOSH-586.
The REPL’s built-in autocompleter uses `repl.eval()` to figure out
what JS object’s properties it would be autocompleting. These
`.eval()` calls don’t represent a state change as far as input
handling is concerned, so they should not affect the prompt and not
enable block-on-newline.
> fix(cli-repl): disregard autocomplete eval for input stream MONGOSH-586

- packages/cli-repl/src/smoke-tests-fle.ts
- packages/cli-repl/test/e2e-fle.spec.ts
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/field-level-encryption.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shell-api.spec.ts
As noted in the issue, this was a typo in the documentation.
The old shell expects `kmsProviders` (like the drivers), and we should
not deviate here and instead update the documentation.
> fix(shell-api): rename kmsProvider to kmsProviders MONGOSH-604

- .evergreen.yml
- .evergreen/compile-artifact.sh
- .evergreen/package-and-upload-artifact.sh
- config/build.conf.js
- packages/build/README.md
- packages/build/src/barque.spec.ts
- packages/build/src/barque.ts
- packages/build/src/config/build-variant.ts
- packages/build/src/config/config.ts
- packages/build/src/config/redact-config.ts
- packages/build/src/index.ts
- packages/build/src/package/run-package.ts
- packages/build/src/run-publish.spec.ts
- packages/build/src/run-upload.spec.ts
Uses an explicit expansion to define the "variant" the distribution should be built for. Also uses task tags for easier dependency definition.
> chore(build): decouple tasks from build variant names MONGOSH-534

- packages/browser-repl/src/components/shell-input.spec.tsx
- packages/browser-repl/src/components/shell-input.tsx
- packages/browser-repl/src/components/shell-loader.less
- packages/browser-repl/src/components/shell-loader.tsx
- packages/browser-repl/src/components/shell.spec.tsx
- packages/browser-repl/src/components/shell.tsx
- packages/browser-repl/src/index.tsx
- packages/compass-shell/src/components/compass-shell/compass-shell.jsx
- packages/compass-shell/src/components/compass-shell/compass-shell.less
- packages/compass-shell/src/components/compass-shell/compass-shell.spec.js
- packages/compass-shell/src/components/shell-header/shell-header.jsx
- packages/compass-shell/src/components/shell-header/shell-header.less
- packages/compass-shell/src/components/shell-header/shell-header.spec.js
Adds a `Command in Progress...` indicator while a command is in progress and the shell is collapsed. 
Couple other changes:
- Tweaks to the styles of the header text.
- Updated the loader indicator - different color and animation.
- Keep the shell mounted when collapsed so we avoid reloading react-ace and also can keep using the component coupled with the runtime (set state doesn't blow up when collapsed).
https://user-images.githubusercontent.com/1791149/108212349-0c13f180-712e-11eb-929e-d78d54d32497.mp4
> feat: add compass shell progress indicator COMPASS-4515

- package.json
Up until very recently, this was taken care of by always running
compile-ts before evergreen-release, but since that’s no longer
the case, we need to manually run compile-cli before compile-exec.
> fix(build): run compile-cli before compile-exec

- packages/build/src/analytics.ts
Templates are what template strings are for. :)
> chore(build): simplify analytics config generation

- packages/cli-repl/src/async-repl.spec.ts
- packages/cli-repl/src/async-repl.ts
This otherwise messes with cases where the input stream ends while
async evaluation is still in progress (e.g. when piping into mongosh).
> fix(cli-repl): defer exit event until evalutation done

- packages/build/src/local/get-latest-tag.spec.ts
- packages/build/src/local/get-latest-tag.ts
- packages/build/src/local/repository-status.spec.ts
- packages/build/src/local/repository-status.ts
- packages/build/src/local/trigger-release-draft.spec.ts
- packages/build/src/local/trigger-release-draft.ts
- packages/build/src/local/trigger-release-publish.ts
This also allows running the local release task from a branch of the form `release/v0.0.0` or `release/v0.x.x`. In these cases `draft` will auto-bump the patch if the latest tag matching the branch version is a release. Otherwise it will create a new draft as usual.
> chore(build): allow support releases MONGOSH-535

- packages/build/src/barque.spec.ts
- packages/build/src/barque.ts
- packages/build/src/local/trigger-release-publish.spec.ts
- packages/build/src/local/trigger-release-publish.ts
- packages/build/src/run-publish.spec.ts
- packages/build/src/run-publish.ts
Fixes an issue with releasing to Barque and asks to still publish a release if some evergreen tasks failed.
> chore(build): fix releasing to barque and evergreen checks

- packages/node-runtime-worker-thread/src/child-process-proxy.ts
This fixes an issue of using the worker from electron asar bundle that doesn't allow worker to resolve the path
correctly.
> fix(node-runtime-worker-thread): Read worker source and eval instead of passing path to the worker constructor

- packages/build/src/evergreen/rest-api.spec.ts
- packages/build/src/evergreen/rest-api.ts
- packages/build/src/local/trigger-release-publish.spec.ts
- packages/build/src/local/trigger-release-publish.ts
The Evergreen REST API returns all tasks that ever ran _based_ on the commit SHA. This includes multiple waterfall builds (e.g.  because these were triggered by tags), and also patch builds that are based on the given SHA.
We therefore have to filter based on the draft tag we are looking for.
> chore(build): fix detection of tasks for latest draft build

- packages/i18n/src/locales/en_US.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
This came up in a recent conversation in slack, where passing
multiple hosts through the `--host` option separated by commas
did not fail properly and instead led to connecting to the wrong
set of hosts.
> fix(service-provider-core): validate --host option more strictly

- packages/build/src/barque.spec.ts
- packages/build/src/barque.ts
The issue was caused because it tried to publish the `-linux.tgz` files to the Ubuntu PPA instead of the `.deb` packages.
It is more or less "safe" to test for a release since publishing to Barque is the first step in the publishing stage. So in the worst case we will have to re-start publishing.
> chore(build): ensure packages are published for all distros MONGOSH-483

- packages/build/src/git/repository-status.spec.ts
- packages/build/src/git/repository-status.ts
Runs a `git fetch --tags` before verifying local repository status on `npm run release <draft|publish>`.
> chore(build): ensure remote information is up-to-date MONGOSH-610

- packages/build/src/barque.spec.ts
- packages/build/src/barque.ts
- packages/build/src/run-publish.spec.ts
- packages/build/src/run-publish.ts
This PR adds the following behavior:
* Publishing a distributable using Barque returns the URLs we expect the packages to be available at
* After all distributables are published we wait at most 5 minutes for them to become available checking every 10 seconds
Note: We are only doing a `HEAD` request instead of downloading the full package. Example to see with an existing package locally:
```
$ curl --head https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/RPMS/mongosh-0.8.2-x86_64.rpm
HTTP/2 200
...
```
**Open Question:** Should I calibrate timeout and interval to different values?
> chore(build): wait until packages are really available in PPAs MONGOSH-619

- .evergreen.yml
Since https://jira.mongodb.org/browse/SERVER-54508 has been fixed,
the macos + latest combination works fine again.
> chore(ci): depend on all unit test runs again

- packages/build/src/github-repo.spec.ts
- packages/build/src/github-repo.ts
The GitHub API for updating a release requires the `tag_name` to be present or otherwise it will remove the associated tag (at least for draft releases where the tag does not yet exist).
> chore(build): fix updating draft releases to contain tag

- packages/compass-shell/config/webpack.base.config.js
- packages/compass-shell/src/modules/runtime.js
- packages/compass-shell/src/modules/worker-runtime.js
- packages/node-runtime-worker-thread/src/child-process-proxy.ts
This change should finally allow us to include compass-shell with new runtime in compass without any issues. Current implementation doesn't work because `worker_threads` Worker when spawned in electron environment can't resolve anything correctly inside the `.asar` bundle, so worker code just fails when trying to resolve `interruptor` (that needs to stay external because it has a native module dependency). As a workaround we will ensure that if we are trying to import `node-runtime-worker-thread` from inside the `.asar` archive we would instead look for the unpacked version and hard fail if it doesn't exist as requiring one that is not unpacked would not work correctly anyway.
> fix: change runtime importing approach MONGOSH-618

- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
The `pwd` field is not allowed for `createUser` on the `$external`
database. For any other database the `pwd` field is required.
> fix(shell-api): createUser on $external handles pwd properly MONGOSH-622

- packages/cli-repl/src/arg-parser.spec.ts
- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/index.ts
- packages/service-provider-core/src/cli-options.ts
Adds deprecation warnings for all `ssl` arguments and at the same time transforms them to their new `tls` counterparts for backwards compatibility.
Will also throw an error for unsupported arguments, currently:
- `eval`
- `tls/sslFIPSMode`
- `tls/sslCertificateSelector`
Also dedupes the tests as in #701 but keeps the node as well as direct invocation tests.
> feat(cli-repl): improve argument handling MONGOSH-571

- packages/cli-repl/src/arg-mapper.spec.ts
- packages/cli-repl/src/arg-mapper.ts
- packages/cli-repl/src/arg-parser.spec.ts
- packages/cli-repl/src/arg-parser.ts
~~The arg-parser tests contained hundreds of duplicated lines.
This was confusing for when it comes to adding new tests, and in fact,
the two duplicated sections were already slightly out of sync.
Improve this by only having one copy of each of those tests.~~
Since testing this is a separate issue, I’ve only confirmed that it
“works” insofar as that I’ve verified that AWS authentication breaks
when I specify an invalid token (but works without any token at all).
> chore(cli-repl): add awsIamSessionToken support MONGOSH-572

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/fixtures/load/a.js
- packages/cli-repl/test/fixtures/load/b.js
- packages/cli-repl/test/fixtures/load/c.js
- packages/node-runtime-worker-thread/src/child-process-evaluation-listener.ts
- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
Paired on this with Michael because it seemed like a good ticket to
pair on and we’re going to be doing the loading-files epic soon.
> feat(cli-repl): add load() support MONGOSH-386

- packages/cli-repl/test/e2e-direct.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/shell-internal-state.spec.ts
- packages/shell-api/src/shell-internal-state.ts
This is also what we do for `show dbs`/`show collections` in order
to ensure that they work on secondary nodes.
> fix: always autocomplete with read pref primaryPreferred MONGOSH-624

- packages/cli-repl/src/mongosh-repl.ts
- packages/shell-api/src/index.ts
- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
This will make it easier to implement these features in a fully
equivalent way in Compass/VSCode, without having to duplicate this
particular bit of code (and not risk divergence, e.g. if we should
ever decide to use a separate stack for storing filename info).
> chore: move load() __filename and __dirname handling to shell-api

- packages/i18n/src/locales/en_US.ts
Copied description from [mongo docs](https://docs.mongodb.com/manual/reference/method/load/). No link yet as `mongosh` version of the docs is WIP, but a quick fix that removes the "not implemented" part seems warranted before we do 0.9.0 release
> chore(i18n): Update load description

- packages/connectivity-tests/test/all.sh
- packages/connectivity-tests/test/ldap.sh
Depends on https://github.com/mongodb-js/devtools-docker-test-envs/pull/3 to run the LDAP tests also against MongoDB Enterprise v4.2.
> chore(ci): expand LDAP integration tests MONGOSH-577

- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
Since the Homebrew formula uses the cli-repl package, the aws4
dependency has to be added to it in order for it to be available after
brewing it.
> fix(cli-repl): add aws4 as dependency to cli-repl to enable AWS auth

- packages/shell-api/src/collection.ts
https://jira.mongodb.org/browse/MONGOSH-522
> chore(shell-api): Update deprecation messages for collection crud commands MONGOSH-522

- packages/compass-shell/src/modules/worker-runtime.js
- packages/node-runtime-worker-thread/__fixtures__/script-that-throws.js
- packages/node-runtime-worker-thread/src/child-process-proxy.ts
- packages/node-runtime-worker-thread/src/index.spec.ts
- packages/node-runtime-worker-thread/src/index.ts
As spotted by @addaleax if child process or worker thread fails to start (e.g., when you are developing a new feature), worker runtime just never resolves any requests to `evaluate`. This PR fixes the issue by handling possible errors during the init state of the worker runtime and re-throwing them in the main thread so users can see them in the shell:
Also spotted and fixed a tiny issue when running compass-shell in isolation locally (shakes fist at webpack)
> fix(node-runtime-worker-thread): Propagate child process startup errors for thread runtime

- package-lock.json
- package.json
- packages/i18n/src/locales/en_US.ts
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/JavaServiceProvider.kt
- packages/java-shell/src/main/kotlin/com/mongodb/mongosh/service/WritableServiceProvider.kt
- packages/service-provider-core/package-lock.json
- packages/service-provider-core/package.json
- packages/service-provider-core/src/all-transport-types.ts
- packages/service-provider-core/src/writable.ts
- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
- packages/service-provider-server/src/cli-service-provider.integration.spec.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/explainable.ts
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/shell-internal-state.ts
Along with this:
- Update mongodb-client-encryption to 1.2.2
- ~~Revert adc916e9cca2ddeadb7a (go back to `npm@latest`)~~ (need at least also https://jira.mongodb.org/browse/NODE-3161)
- Remove `findAndModify()` from the service providers
because it is gone in the drivers
- Make the shell `findAndModify()` API method multiplex
over its `findOneAnd...` replacements
- Fix explain functionality for `findOneAnd...` methods
- Add `findOneAnd...` methods to the `Explainable` class
- Update driver type names where they have changed
> chore(deps): update driver to 4.0.0-beta.2

- packages/cli-repl/src/async-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/fixtures/load/infinite-loop.js
This was previously broken because the async repl implementation
adds an `process.on('SIGINT')` listener for the duration of the
*async* part of the evaluation. That listener would interfere with
breaking on sigint if another *synchronous* evaluation would be
started while it is present.
Fix this by not being lazy anymore and temporarily disabling
existing `SIGINT` event listeners on both `process` and `repl`
(and not just `repl`). In this case, the “inner” evaluation
also temporarily removes the “outer” `SIGINT` listener and
can go about as usual.
> fix(cli-repl): allow interrupting load()ed code MONGOSH-641

- packages/async-rewriter/src/async-writer-babel.spec.ts
- packages/async-rewriter/src/await.spec.ts
- packages/async-rewriter/src/await.ts
This allows having single-line comments on the last line of input.
> fix(async-rewriter): give each input its own line MONGOSH-644

- packages/cli-repl/package.json
`npm test` also runs the end-to-end tests. Because the e2e tests
are run on the already-compiled code, we have a `pretest-e2e`
script that recompiles TypeScript, but we should also run that
script before `npm test` for the same reason.
> chore(cli-repl): add compile-ts as pretest script

- packages/shell-api/src/replica-set.spec.ts
4.2.13 broke our tests today. Skip the broken bit for now.
https://jira.mongodb.org/browse/SERVER-55371
> fix(ci): work around SERVER-55371 with mongod 4.2.13

- packages/cli-repl/src/format-output.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/service-provider-core/src/all-transport-types.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/explainable-cursor.spec.ts
- packages/shell-api/src/explainable-cursor.ts
- packages/shell-api/src/explainable.spec.ts
- packages/shell-api/src/explainable.ts
- packages/shell-api/src/helpers.ts
Fully expand output from explain commands, by identifying them
with a specific ShellResult type tag.
This also un-breaks `db.coll.aggregate(..., { explain: ... })`.
> fix: make explain output fully expanded MONGOSH-583

- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
Only tell users that the db has been changed if it actually
has been changed, so that they are not confused about whether
the previous state of the shell has been different from the
current one.
> chore(shell-api): be more accurate in message from 'use'

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- packages/cli-repl/src/cli-repl.spec.ts
Passing back the input as a possible completion would prevent
single-tab autocompletion in the shell.
> fix(autocomplete): do not act as if input is completion MONGOSH-646

- packages/shell-api/src/helpers.spec.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
- packages/shell-api/src/shell-internal-state.ts
Ensures that the following classes accept both number and string arguments:
* `NumberDecimal`
* `NumberLong`
* `NumberInt`
Also shows a deprecation / precision warning:
```
> NumberDecimal(128)
Warning: NumberDecimal: specifying a number as argument is deprecated and may lead to loss of precision
```
> chore(shell-api): ensure backwards compatibility of old number classes

- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shard.spec.ts
The old `mongodb shell` returns sharded and not shared databases as a result of `sh.status()` command. Remove the filtering by `partitioned` value in order to ensure `mongosh` behavior compatible with the old shell.
> MONGOSH-596: sh status should include not sharder dbs

- .nycrc
- packages/async-rewriter2/.eslintignore
- packages/async-rewriter2/.eslintrc.js
- packages/async-rewriter2/.gitignore
- packages/async-rewriter2/.npmignore
- packages/async-rewriter2/AUTHORS
- packages/async-rewriter2/LICENSE
- packages/async-rewriter2/README.md
- packages/async-rewriter2/package-lock.json
- packages/async-rewriter2/package.json
- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/async-writer-babel.ts
- packages/async-rewriter2/src/index.ts
- packages/async-rewriter2/src/runtime-support.nocov.js
- packages/async-rewriter2/tsconfig.json
- packages/cli-repl/test/e2e-fle.spec.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shell-internal-state.ts
- packages/shell-evaluator/src/shell-evaluator.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
This is about as far as I’d want to go without some kind of confirmation that we want to explore this further, but I am quite happy with it so far, and it already passes the test suite (almost – except for the parts that specifically test the “old” async-rewriter integration) locally.
---
See the [package’s README.md](https://github.com/mongodb-js/mongosh/blob/async-rewriter2/packages/async-rewriter2/README.md) for details on the why and how.
This is feature-flagged behind the `MONGOSH_ASYNC_REWRITER2`
env var and introduced as a separate package in this commit,
but if we do adopt this it’s going to enable us to remove
a lot of code *and* have a more flexible async-rewriting system.
> feat(async-rewriter2): introduce new async-rewriter alternative ✨

- packages/async-rewriter2/README.md
- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/async-writer-babel.ts
Improve the error messages thrown at runtime by storing the
original source code next to the expression, and then using the
fact that literals are preserved in error messages by V8
in order to restore the original source code of the expression
at runtime.
> fix(async-rewriter2): improve error messages MONGOSH-656

- .evergreen/.setup_env
For some reason, Windows builds started failing recently.
The windows-64-vs2019-small image, the Node.js version,
the npm version, the git version, and the package-lock.json
all remained the same in that period, so it is unclear
what exactly caused this.
While a full investigation would likely be interesting,
that’s not easy with Evergreen’s current capabilities.
However, fixing this seems possible by explicitly adding
the git binaries (including libexec ones) to the PATH,
so let’s do that for now.
> fix(ci): work around CI Windows git failure MONGOSH-660

- packages/async-rewriter2/README.md
- packages/async-rewriter2/package.json
- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/async-writer-babel.ts
- packages/async-rewriter2/test/fixtures/with-domain.js
The fix I previously inserted for the “Node.js prints a warning
if we intentionally disregard a rejected Promise from the generated
inner async function” problem turned out to be problematic, because
it creates an infinite loop in the domain handler system.
This problem goes away with Node.js v14.15.2 (due to https://github.com/nodejs/node/commit/0ad4f70db596934b3ff390cde7380ab8bf5480f5),
but since we also support Node.js-v12.x environments
(and we would want to be resilient against changes to the
platform internals anyway), it makes sense to aim for a better
solution here.
This patch makes sure that the generated inner async function only
returns a meaningful value if its return value is actually used,
i.e. if we’re encountering an async-evaluation case where the
generated outer function …
> fix(async-rewriter2): fix interaction with domains MONGOSH-662

- packages/cli-repl/src/mongocryptd-manager.spec.ts
Example failure:
[2021/04/01 09:26:24.908]   1) MongocryptdManager
[2021/04/01 09:26:24.908]        with network testing
[2021/04/01 09:26:24.908]          performs keepalive pings:
[2021/04/01 09:26:24.908]      SyntaxError: Unexpected end of JSON input
[2021/04/01 09:26:24.908]       at JSON.parse (<anonymous>)
[2021/04/01 09:26:24.908]       at Context.<anonymous> (src/mongocryptd-manager.spec.ts:184:19)
Presumably this is happening because the connections aren’t established
fast enough when the host is under load, e.g. because multiple tests
are running at the same time. Using the `eventually` helper would be
the right thing to do here anyway, because it allows for a longer
timeout while at the same time finishing faster under normal
circumstances.
> chore(cli-repl): (hopefully) fix flaky mongocryptd test

- packages/async-rewriter2/README.md
- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/async-writer-babel.ts
- packages/async-rewriter2/src/runtime-support.nocov.js
- packages/cli-repl/test/e2e.spec.ts
Add a copy of the original source code at the beginning of transformed
functions, so that `Function.prototype.toString` works properly
for them.
> fix(async-rewriter2): properly stringify functions MONGOSH-664

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/async-writer-babel.ts
Includes #751, #752, #753 to avoid git conflicts/make sure the tests pass here
---
In always-synchronous contexts like class constructors and synchronous
generator functions, throw an exception if a synthetic Promise is
encountered, since there is no way to actually act as if it is a
synchronous expression.
> feat(async-rewriter2): throw for async in sync contexts MONGOSH-654

- packages/shell-evaluator/src/shell-evaluator.ts
`hasAppliedAsyncWriterRuntimeSupport` was supposed to be a run-only
guard, it was just the actual setting of the variable that was missing
so far.
This fix makes the shell respond a lot faster when using the new async
rewriter. :)
> fix(shell-evaluator): only apply async-rewriter2 runtime support once

- packages/java-shell/src/test/resources/collection/createIndex.expected.txt
- packages/java-shell/src/test/resources/collection/createIndex.js
`weight` is only valid for text indices, so use a text index here.
> fix(java-shell): update tests for latest server alpha MONGOSH-667

- packages/service-provider-core/src/connection-string.spec.ts
- packages/service-provider-core/src/connection-string.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/whatwg-url.ts
When adding or changing keys, make sure not to ignore already-existing
but differently-cased keys.
> fix(service-provider-core): connection str options casing MONGOSH-669

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/stages/transform-maybe-await.ts
Treat for-in/for-of with a non-variable-declarator left-hand side
like assignment expressions (which they effectively are).
> fix(async-rewriter2): treat for-in/of as assignments

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/stages/transform-maybe-await.ts
The source code comments hopefully explain well enough what’s
going on here.
> fix(async-rewriter2): handle typeof + identifier properly

- package-lock.json
- package.json
- packages/node-runtime-worker-thread/package-lock.json
- packages/node-runtime-worker-thread/package.json
- packages/service-provider-core/package-lock.json
- packages/service-provider-core/package.json
- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
Also updates `mongodb-client-encryption` to `1.2.3`.
> chore: update to driver 4.0.0-beta.3 MONGOSH-673

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/test/e2e.spec.ts
Load lodash (all of it) and moment.js into the shell and perform
a basic test that verifies that they can be used with the new
async rewriter.
> chore(cli-repl): add async-rewriter library integration test

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/stages/transform-maybe-await.ts
This might help with performance a bit.
> chore(async-rewriter2): further limit number of wrapped expressions

- packages/shell-api/src/replica-set.spec.ts
See the referenced server issue, the problematic change has been
applied not only to 4.2.x but also to 4.0.x and 4.4.x, so let’s
skip this entirely for now.
> fix(shell-api): never check $clusterTime in rs integration tests

- packages/async-rewriter/src/async-writer-babel.ts
- packages/async-rewriter2/src/async-writer-babel.ts
- packages/cli-repl/test/e2e.spec.ts
This turns off warnings when processing large scripts.
This change uses a lower ‘compact’ code size limit than the
babel default, because we don’t really need the code to
be auto-styled except when we’re developing.
> chore(async-rewriter): use babel compact option MONGOSH-678

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
Otherwise, you end up with
`Enter password: ****************Current Mongosh Log ID: [...]`.
> fix(cli-repl): print newline after password prompt

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/e2e.spec.ts
`--eval` always prints its result in the old shell (with or
without `--shell`). Do the same thing in mongosh.
> fix(cli-repl): print result of --eval MONGOSH-683

- packages/shell-api/src/shell-api.ts
I don’t think this was intentionally exposed as a global
(it was because all own properties of the `ShellApi` instance
are copied onto the global object). Hide it by making it a non-own
property.
> fix(shell-api): do not expose internalState as global

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/node-runtime-worker-thread/src/index.spec.ts
- packages/node-runtime-worker-thread/src/worker-runtime.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-evaluator/src/shell-evaluator.ts
After further manual testing, it seems to be a good idea to
flip the switch to enable the new async rewriter by default,
as doing so does improve the user experience significantly
and we do likely want to have some time between enabling it and
the shell 1.0 release.
(e.g.: Without this, running scripts like https://github.com/addaleax/mongosh-snippets/blob/main/snippets/analyze-schema/index.js would be virtually impossible)
> feat: flip async-rewriter switch MONGOSH-651

- packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
- packages/cli-repl/src/setup-logger-and-telemetry.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/shell-evaluator/src/shell-evaluator.ts
- packages/types/src/index.ts
With the new async rewriter, the rewritten code is unfortunately quite
a bit larger in size than the input, so logging both input and output
leads to large log files. However, since the new rewriter is stateless,
we also don’t need to worry about the output anymore, and can just
skip logging it.
> chore(shell-evaluator): do not log full rewritten code

- packages/service-provider-core/src/index.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
This has the catch that it’s not going to work fully until
https://jira.mongodb.org/browse/NODE-3208 is fixed
(but I wouldn’t have caught that without trying it out here,
so it’s still good that I did, I guess).
> feat(shell-api): add EJSON global MONGOSH-670

- packages/service-provider-core/src/connection-string.ts
https://github.com/mongodb-js/mongosh/pull/760 broke the compass-shell
tests, likely because there are multiple conflicting implementations of
`URLSearchParams` that come into play. We didn't notice because the
compass-shell tests don't run in CI (-> https://jira.mongodb.org/browse/MONGOSH-689).
Instead of using a fixed prototype, make the case-insensitive
URLSearchParams implementation a mixin.
> fix(service-provider-core): re-fix connection string casing

- packages/build/src/compile/generate-bundle.spec.ts
This *might* fix flakiness like this:
[2021/04/19 11:53:57.707]   1) compile generateBundle
[2021/04/19 11:53:57.707]        does not attempt to load ES6 modules because parcel cannot handle them properly:
[2021/04/19 11:53:57.707]      Error: ENOENT: no such file or directory, open 'Z:\data\mci\b2b62ed7d54f2bcd3c5e2ddd5846c7d9\src\packages\tmp\test-build-1618833168859-0.6650505642822344\a.js'
> chore(build): give each bundling test its own tmpdir

- packages/cli-repl/test/helpers.ts
- packages/cli-repl/test/test-shell.ts
The Node.js REPL produces errors like this when a module is not found:
```js
Uncaught Error: Cannot find module 'a'
Require stack:
- <repl>
[ ... ]
```
Our test helpers interpreted the `- <repl>` string as a prompt, which
it is not.
Fix that by requiring the prompt not to contain a matching
angle bracket, and provide more precise error messages from our
test helpers in general to help debug future problems.
> chore(cli-repl): fix flaky test and improve errors

- packages/async-rewriter2/bin/async-rewrite.js
I’ve used this during development a few times recently,
so it might make sense to just commit it.
> chore(async-rewriter2): add small helper cli for testing

- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/shell-api/src/mongo.ts
- packages/shell-api/src/shell-internal-state.spec.ts
- packages/shell-api/src/shell-internal-state.ts
When connected to a server that we know is an Atlas server but
announces itself as a mongos, print “atlas proxy” in the prompt
rather than “mongos” to avoid confusion.
As a drive-by fix, make sure to use the service provider of the
current database, and not necessarily the initial one, as new
connections can be assigned to `db`.
> fix(shell-api): fix prompt for Atlas-proxy-style mongos MONGOSH-680

- packages/service-provider-core/src/connect-info.spec.ts
- packages/service-provider-core/src/connect-info.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/src/shell-internal-state.spec.ts
- packages/shell-api/src/shell-internal-state.ts
This seems a bit more reliable than hostname parsing.
> chore(service-provider-server): use atlasVersion to identify Atlas

- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/repl-helpers.ts
In addition to the fix in c8cee80616162f, the test here is also flaky
because of a Node.js REPL bug where `repl.displayPrompt()` was called
twice after we reported an error, which confused the prompt detection
in the shell and made the test flaky depending on whether both prompts
where received in the same output data chunk or not.
For now, just wait until both parts of the double prompt are present
in the output before executing the next input line.
> chore(cli-repl): work around Node.js REPL bug MONGOSH-589

- packages/cli-repl/test/e2e-analytics.spec.ts
- packages/cli-repl/test/e2e-auth.spec.ts
- packages/cli-repl/test/e2e-aws.spec.ts
- packages/cli-repl/test/e2e-bson.spec.ts
- packages/cli-repl/test/e2e-direct.spec.ts
- packages/cli-repl/test/e2e-fle.spec.ts
- packages/cli-repl/test/e2e-tls.spec.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/test-shell.ts
This is just to get better debugging in the future for flaky tests
in general.
> chore(cli-repl): print test shell output for failing e2e tests

- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/test-shell.ts
- packages/service-provider-core/src/fast-failure-connect.spec.ts
- packages/service-provider-core/src/fast-failure-connect.ts
- packages/service-provider-core/src/index.ts
- packages/service-provider-server/src/cli-service-provider.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
This was brought up as a nice way of erroring early in the driver sync
meeting today.
> chore(service-provider-server): fail fast for doomed connect MONGOSH-705

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/abstract-cursor.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/aggregation-cursor.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/cursor.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/explainable-cursor.ts
Create an `AbstractCursor` class (named like the driver equivalent)
as a common base class for `Cursor` and `AggregationCursor`
to reduce code duplication.
This helps with more code deduplication, because it can make wrappers
go away that were only needed to re-specify the return type
in a subclass.
> chore(shell-api): combine common Cursor + AbstractCursor code

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
As suggested in https://github.com/mongodb-js/mongosh/pull/811#discussion_r621150695
> chore(cli-repl): use tab constant instead of using U+0009 explicitly

- CONTRIBUTING.md
- README.md
- packages/build/src/index.ts
Also update the main build script to actually set the right
distribution variant value in the config, which had accidentally
been broken (and so the example in the README wouldn’t work).
> chore: update README to reflect current situation

- packages/java-shell/src/test/resources/cursor/forEach.expected.txt
- packages/shell-api/src/abstract-cursor.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/change-stream-cursor.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/explainable-cursor.spec.ts
- packages/shell-api/src/helpers.ts
- packages/shell-api/src/integration.spec.ts
(Includes #809 for now, until that is merged.)
Handle exceptions from callbacks passed to `cursor.map()` and
`cursor.forEach()`.
Since `cursor.forEach()` returns a Promise, use that to propagate
the error to the user.
For `cursor.map()`, this is a bit trickier, since the method itself
does not return any results to the user. Therefore, we add checks
before and after accessing cursor methods that read data which forward
the exception if one has occurred.
Both of these feel like situations that the driver should take care of
explicitly, so NODE tickets have been opened for both cases.
(One alternative would have been to add async context/Node.js domain
propagation to these methods. However, I decided against that, because
that solution would be a) Node.js-specific, and b) because it would …
> fix(shell-api): handle errors in cursor.map/.forEach MONGOSH-703

- packages/shell-api/src/collection.ts
- packages/shell-api/src/shard.spec.ts
`result.shards` is an object in sharded clusters, so it is never
an iterable.
`result.shards` is also a (non-empty object) in sharded clusters
for unsharded collections.
Therefore, just always iterate over all entries in the object here.
> fix(shell-api): handle coll.stats() in sharded clusters MONGOSH-731

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/integration.spec.ts
(db.hello() is part of MONGOSH-558, but I guess having it earlier
than later is not a bad thing.)
> feat(shell-api): add db.rotateCertificates and db.hello MONGOSH-277

- .github/workflows/cron-tasks.yml
Apparently, this action does not actually check the default branch
name.
> chore(github): set branch name for github action

- packages/cli-repl/src/constants.ts
- packages/i18n/src/locales/en_US.ts
Added description for --quiet and --verbose in shell help.
> feat(cli-repl): add help for quiet and verbose MONGOSH-581

- packages/autocomplete/index.spec.ts
- packages/autocomplete/index.ts
- packages/browser-runtime-core/src/autocompleter/shell-api-autocompleter.spec.ts
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/shell-api/src/aggregation-cursor.spec.ts
- packages/shell-api/src/bulk.spec.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/cursor.spec.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/decorators.ts
- packages/shell-api/src/explainable-cursor.spec.ts
- packages/shell-api/src/explainable.spec.ts
- packages/shell-api/src/field-level-encryption.spec.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
- packages/shell-api/src/plan-cache.spec.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/session.spec.ts
- packages/shell-api/src/shard.spec.ts
- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-api.ts
- packages/shell-api/src/shell-internal-state.ts
Add support for autocompletion for shell commands, in particular,
`show` and `use`. Autocompletion for `use` works similar to
autocompletion for `db.<collection>`.
The implementation details for use/show autocompletion here have
been left to the shell-api package, so that changes to them do not
require any autocompletion changes.
> feat(autocomplete): add show/use completions MONGOSH-563

- packages/shell-api/src/database.ts
- packages/shell-api/src/integration.spec.ts
If `db.hello()` is not available, fall back to the legacy variant, and
always make `isWritablePrimary` available in the return value for both
variants.
> feat(shell-api): make db.hello() fall back to legacy variant MONGOSH-558

- packages/cli-repl/src/setup-logger-and-telemetry.spec.ts
- packages/cli-repl/src/setup-logger-and-telemetry.ts
With support for multiple architectures expanding, it seems to make
sense to track the system architecture along with the OS.
> chore(cli-repl): track arch in telemetry

- packages/cli-repl/src/format-output.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/e2e-bson.spec.ts
This is done a bit differently from the other BSON types because
it is a JS builtin type.
> fix(cli-repl): print Date objects as ISODate MONGOSH-723

- .evergreen/.install_node
Both Node.js 12 and Node.js 14 ship with npm@6.x out of the box,
and [this failed recently on an s390x machine](https://evergreen.mongodb.com/task_log_raw/mongosh_linux_ppc64le_build_compile_artifact_patch_504e9cc2fd486b88c253d911cd3699e1fa5c4c55_60918a33850e611944cf9e27_21_05_04_17_53_56/0?type=T) where it tried to
write to the already-present Node.js 8 installation, so let’s
skip this for now unless that’s a problem too.
[2021/05/04 19:24:59.963] ++ npm install -g npm@6
[2021/05/04 19:24:59.963] npm WARN checkPermissions Missing write access to /opt/node-v8.11.3-linux-ppc64le/lib/node_modules/npm/node_modules/ansi-regex
[2021/05/04 19:24:59.963] npm WARN checkPermissions Missing write access to /opt/node-v8.11.3-linux-ppc64le/lib/node_modules/npm/node_modules/aproba
[2021/05/04 …
> fix(ci): do not try to install npm globally

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/bulk.spec.ts
- packages/shell-api/src/bulk.ts
This happens to account for the changes made in NODE-2978 (https://github.com/mongodb/node-mongodb-native/commit/c3a183938289).
The old names are kept as deprecated aliases.
MONGOSH-752
> feat(shell-api): provide bulk.find().delete() instead of .remove() MONGOSH-752

- packages/cli-repl/src/smoke-tests-fle.ts
Using the local test db name is nicer because that means that we don’t
clutter up the encryption db of the test environment, and we drop
the test db at the end of the test anyway.
> chore(cli-repl): do not use encryption db name for smoke tests

- .evergreen/.setup_env
Waterfall builds for ppc64le are currently failing because nvm
somehow doesn’t modify `$PATH` as it should:
[2021/05/06 12:02:21.433] Now using node v14.15.1 (npm v5.6.0)
<...>
[2021/05/06 12:02:21.680] Using node version:
[2021/05/06 12:02:21.680] v8.11.3
[2021/05/06 12:02:21.680] Using npm version:
[2021/05/06 12:02:21.680] 5.6.0
<...>
[2021/05/06 12:02:21.984] > npm ci
[2021/05/06 12:02:22.288] Usage: npm <command>
Try this to see if it helps.
> chore(ci): try setting PATH to include NVM_BIN explicitly

- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/cli-repl/test/repl-helpers.ts
Since the bug has more implications than making our tests flaky, start
working around it instead of skipping tests.
In particular, this fixes the linked ticket, because the REPL
implementation calling `repl.displayPrompt()` twice after an error
would also call `lineByLineInput.nextLine()` twice in our code,
which would start two async evaluations happening at the same time,
which breaks the async REPL wrapper’s API contract.
> fix(cli-repl): work around double-prompt Node.js REPL bug MONGOSH-727

- packages/build/src/packaging/run-package.ts
Since the required properties are now configured in evergreen we can activate signing:
https://user-images.githubusercontent.com/4354632/117446981-2dba9300-af3d-11eb-9724-29afbfd50899.mov
> chore(build): enable signing MSIs with notary service MONGOSH-567

- config/build.conf.js
- packages/build/src/barque.spec.ts
- packages/build/src/download-center/config.spec.ts
- packages/build/src/download-center/config.ts
- packages/build/src/packaging/package/create-package.ts
- packages/build/src/packaging/package/debian.ts
- packages/build/src/packaging/package/get-package-file.spec.ts
- packages/build/src/packaging/package/get-package-file.ts
- packages/build/src/packaging/package/package-information.ts
- packages/build/src/packaging/package/redhat.ts
- packages/build/src/run-draft.ts
- packages/build/src/run-publish.spec.ts
- packages/build/src/run-publish.ts
- packages/build/test/fixtures/pkgconf.js
- packaging/deb-template/mongodb-mongosh/DEBIAN/control
- packaging/rpm-template/SPECS/mongodb-mongosh.spec
- scripts/docker/centos7-rpm.Dockerfile
- scripts/docker/centos8-rpm.Dockerfile
- scripts/docker/ubuntu16.04-deb.Dockerfile
- scripts/docker/ubuntu18.04-deb.Dockerfile
- scripts/docker/ubuntu20.04-deb.Dockerfile
The RPM and Debian packages are renamed to mongodb-mongosh to fit a
common Linux package naming convention which allows users to locate
software more easily. A Provides: tag is also added to the packages to
provide a stable naming alias in case we ever decide to rename packages
again.
> MONGOSH-692 Rename package to mongodb-mongosh

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/js-multiline-to-singleline.spec.ts
- packages/cli-repl/src/js-multiline-to-singleline.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
The changes for this feature are fairly self-contained, however,
.editor support relies a lot more strongly on automated semicolon
insertion (ASI) than the previous multi-line input handling,
so the bigger part of the changes here is getting the semantics for
that right. (This would also have affected the original multi-line
aggregating functionality, e.g. `() => { 1\n2 }` would have resulted
in a broken `() => { 1 2 }` history entry.)
> feat(cli-repl): aggregate .editor multiline input MONGOSH-518

- .evergreen.yml
This addresses MONGOSH-685 and unblocks MONGOSH-442.
> chore: bump Node.js to 14.17.0

- packages/cli-repl/src/mongosh-repl.ts
- packages/service-provider-core/src/connect-info.spec.ts
- packages/service-provider-core/src/connect-info.ts
This does not yet add integration tests, which is left for MONGOSH-765.
> fix: make shell run with --apiStrict

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/mongo.ts
These were present in the legacy shell, and while they were
undocumented, I feel like they are obvious candidates for inclusion
in the API, so I’m just going ahead and opening a PR.
> feat(shell-api): add mongo.getDBs() and .getDBNames() MONGOSH-766

- packages/build/src/packaging/package/helpers.ts
Fixes the issue of images not showing in the MSI installer.
> fix(build): do not utf8-read/write images MONGOSH-763

- packages/cli-repl/package-lock.json
- packages/cli-repl/package.json
- packages/cli-repl/src/arg-mapper.spec.ts
This brings in https://github.com/mongodb-js/macos-export-certificate-and-key/releases/tag/v1.0.1 which contains a fix to prevent crashes when we cannot get a valid subject name from a certificate.
> fix(cli-repl): prevent failures in macOS certificate selector MONGOSH-762

- packages/java-shell/src/test/resources/cursor/explain.expected.txt
- packages/java-shell/src/test/resources/cursor/explain.js
The SBE engine has been turned on by default in the latest server
versions, which returns a different explain output in executionStats.
Therefore, skip validation in the java-shell tests, which currently
expect the pre-5.0 format.
> chore(java-shell): skip executionStats validation in tests

- .evergreen/.install_node
- .evergreen/.setup_env
There is no git 2.x on the s390x hosts. Lerna needs git 2.x.
Consequentially, we build it before running our tasks.
> fix(ci): build git 2.x if not present on host

- packages/build/src/run-publish.spec.ts
These were broken because I landed the darwin-arm64 without rebasing
against the other recent build changes.
> fix(build): fix build tests

- packages/cli-repl/src/smoke-tests.ts
Since we now (at least temporarily) have a platform without FLE
support in our CLI, we should add a smoke test that does also test
db interactivity but does not require FLE specifically.
> chore(cli-repl): add a non-FLE db interaction smoke test

- README.md
- packages/cli-repl/README.md
- packages/cli-repl/package.json
- packages/cli-repl/src/arg-parser.spec.ts
- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
- packages/i18n/src/locales/en_US.ts
- packages/service-provider-core/src/cli-options.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
- packages/shell-api/src/mongo.ts
(includes #887 and commits from main for passing CI/avoiding conflicts, only the last commit is original here)
- If the first positional argument ends in .mongo or .js and is not a
connection string, treat it as a filename.
- Add a `--file` (`-f`) flag for specifying filenames that avoids this
ambiguity.
- Internally, avoid referring to positional arguments in general and
be specific about whether the connection specifier or the filenames
are being accessed
- As drive-by fixes, fix the spelling of `tlsAllowInvalidHostname` and
drop the extra unnecessary `start` argument handling.
> feat(cli-repl): fix files as positional arguments and add --file MONGOSH-769

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/format-output.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/types/src/index.ts
Some people prefer to have a very verbose, single-line-per-property
output. Node.js supports that, so we add a config options for those
who want it.
> feat(cli-repl): add inspectCompact option MONGOSH-684

- packages/errors/README.md
- packages/errors/index.spec.ts
- packages/errors/index.ts
If someone decides to create a bug when they find something
broken, we should point them directly to the JIRA project rather
than letting them figure out how to get to it.
> fix(errors): direct link to JIRA project

- packages/shell-api/src/shell-api.spec.ts
- packages/shell-api/src/shell-internal-state.ts
Use plain functions instead of arrow functions so that they can be used
with new as well.
> fix(shell-api): allow ShellApi methods to be called with new MONGOSH-786

- packages/cli-repl/test/e2e.spec.ts
(Because waiting for the prompt has a timeout of 10s, waiting for exit has a timeout of 60ms. This has been flaky on Windows.)
> chore(cli-repl): wait longer in ENOTFOUND fail-fast test

- packages/cli-repl/test/e2e-direct.spec.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
This also means that e.g. `host:port?option=value` is not allowed,
and instead any optional part after the port in the non-URL variant
needs to be separated by a slash (which was also the case in
the legacy shell).
> fix(service-provider-core): allow non-hostname chars in DB name MONGOSH-792

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/shard.spec.ts
- packages/shell-api/src/shard.ts
Integration tests are omitted, because it seems like they would
take a fairly long time (see the conversation in the ticket).
> feat(shell-api): add reshard collection helpers MONGOSH-754

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
My previous fix for REPL command completion in 720728d721e was wrong,
this fixes the integraion of the Node.js and mongosh autocompleters
properly.
> fix(cli-repl): fix query operator completion MONGOSH-793

- packages/i18n/src/locales/en_US.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/replica-set.ts
This provides the same functionality as the newly introduced legacy
shell equivalent.
Notable differences are:
- This does some type cleanup around the replset code
- This is more verbose, and prints:
- A warning if the new member is already in the existing config
with a different _id but the same hostname
- Indicators that retrying is still going on when it is
- The second reconfig commmand, if it failed, so that the user
can retry manually
- This performs exponential backoff while waiting for the second
reconfig to succeed
- This uses a fixed number of attempts (12) instead of a fixed
duration (90 seconds) for performing the second reconfig
> feat(shell-api): add reconfigForPSASet helper MONGOSH-702

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/cli-repl.ts
For context, the original motivation here was that for snippets,
if we change the default index URL, users should receive that change
if  they have not explicitly changed the config themselves.
> feat(cli-repl): only store non-default config keys on disk MONGOSH-794

- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
- packages/service-provider-core/src/cli-options.ts
- packages/types/src/index.spec.ts
- packages/types/src/index.ts
Remove the undocumented, untested `--redactInfo` CLI flag and offer
a config option with three possible values:
- `keep`: Retain the history as-is
- `remove`: Remove lines with sensitive commands
- `remove-redact`: `remove` + redact sensitive data from non-sensitive
commands (e.g. email addresses)
> feat(cli-repl): add redactHistory config option MONGOSH-603

- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/replica-set.ts
- testing/integration-testing-hooks.ts
I'll adjust the tests so that the `reconfig` methods gets the full tests on backoff etc. that are currently on the `reconfigPSASet`.
> fix(shell-api): improve rs.reconfig helper for 5.0 changes MONGOSH-785

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
This is also not the cleanest approach in the world, but aside from
a full refactor of the autocomplete implementation (which would be
coming in MONGOSH-538), this seems like a decent tradeoff between
implementation complexity and result accuracy.
> fix(cli-repl): always autocomplete own enumerable properties MONGOSH-808

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/stages/transform-maybe-await.ts
I did check the babel AST definitions for `LValue`s, so that we can
skip transformation for them, but it turns out `delete x.y` is actually
a UnaryExpression and doesn’t even need an `LValue` argument,
which is how this was missed.
> fix(async-rewriter2): fix `delete` behavior MONGOSH-817

- README.md
- packages/cli-repl/src/constants.ts
- packages/i18n/src/locales/en_US.ts
The `--tlsCRLFile` option was missing in the output of `mongosh --help`. Now it's not anymore.
> fix: add --tlsCRLFile option to help

- packages/cli-repl/test/e2e.spec.ts
This should fix
[2021/06/08 14:26:20.478]   1 failing
[2021/06/08 14:26:20.478]   1) e2e
[2021/06/08 14:26:20.478]        collection names with types
[2021/06/08 14:26:20.478]          prints collections with their types:
[2021/06/08 14:26:20.478]      AssertionError: expected '{\n  acknowledged: true,\n  insertedId: ObjectId("60bf7e0b80872cc7f0cde639")\n}\nEnterprise > ' to include 'coll1'
[2021/06/08 14:26:20.478]       at Context.<anonymous> (test/e2e.spec.ts:963:62)
and aligns the test here with the other sections, where we also
wait for the prompt to show up first.
> chore(cli-repl): fix flaky show collections test

- packages/build/src/github-repo.spec.ts
- packages/build/src/github-repo.ts
- packages/build/src/homebrew/publish-to-homebrew.spec.ts
- packages/build/src/homebrew/publish-to-homebrew.ts
- packages/build/src/run-publish.ts
This tackles the issue we saw in https://github.com/Homebrew/homebrew-core/pull/79146.
CC @nandahkrishna 😊 
https://github.com/mongodb-js/mongosh/pull/947/files#diff-45b0bf05b15b45d3a5dc5003bbc5ef6a4cab9117ac7088a81379d7f2b426d3b7R36
> fix(build): add description to homebrew PR

- packages/shell-api/src/replica-set.spec.ts
We recently changed the code to allow retries when changing the
rs config, so we should account for that in the test as well.
> chore(shell-api): loosen rs test version restrictions

- packages/cli-repl/test/e2e-snippet.spec.ts
This is hopefully noticeably less flaky.
> chore(cli-repl): use eventually in e2e snippet test

- .evergreen/.install_node
- packages/build/src/compile/signable-compiler.ts
- packages/cli-repl/test/e2e-auth.spec.ts
- packages/service-provider-core/package-lock.json
- packages/service-provider-core/package.json
- packages/service-provider-server/package-lock.json
- packages/service-provider-server/package.json
- packaging/deb-template/mongodb-mongosh/DEBIAN/control
~~This is WIP because it turns out there’s actually a conflict between the `Init` functions of the libmongocryptd bindings and the kerberos addon, because they are not declared as `static`. That’s something for tomorrow, though :)~~
Tomorrow has happened and now that bug is gone thanks to the Node.js driver team :)
> feat(service-provider-server): add kerberos addon MONGOSH-823

- .evergreen.yml
- package.json
- packages/cli-repl/package.json
- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/test/e2e-analytics.spec.ts
- packages/cli-repl/test/e2e-auth.spec.ts
- packages/cli-repl/test/e2e-aws.spec.ts
- packages/cli-repl/test/e2e-direct.spec.ts
- packages/cli-repl/test/e2e-tls.spec.ts
- packages/cli-repl/test/e2e.spec.ts
- packages/service-provider-server/src/cli-service-provider.ts
- packages/shell-api/package.json
- packages/shell-api/src/integration.spec.ts
- packages/shell-api/src/replica-set.spec.ts
- packages/shell-api/src/session.spec.ts
- packages/shell-api/src/shard.spec.ts
- testing/helpers.ts
- testing/integration-testing-hooks.ts
Run the shell-api and cli-repl test suites with the `strict` and
`deprecationErrors` versioned API options, and skip tests where
this does not apply.
> chore: add apiStrict-only test to CI MONGOSH-756

- packages/snippet-manager/src/snippet-manager.spec.ts
- packages/snippet-manager/src/snippet-manager.ts
I added the await for the fetch index promise when we change the index URL in the test. This potentially caused a race condition with a stale index in a recent test case: https://evergreen.mongodb.com/task/mongosh_linux_test_m42xc_n12_d201e37cbe4f627a07a4754d56d6a63f83fd9fb7_21_06_15_21_06_57.
I also changed the logic of replacing the snippet names on `ls` / `outdated` since the first line is the directory path. Mine contains `mongodb` and got replaced with `mongosh:mongodb-example`.
> fix(test): flaky snippet manager tests

- packages/connectivity-tests/test/all.sh
Updates the referenced devtools env repo commit to https://github.com/mongodb-js/devtools-docker-test-envs/commit/3d04063586ba95a3bd72d38f5569469c81e54987
> fix(test): use devtools with different keyserver MONGOSH-843

- packages/shell-api/src/helpers.ts
- packages/shell-api/src/shard.spec.ts
This only works for environments using the Node.js `util.inspect()`,
but most likely those environments are also the main issue here.
> feat(shell-api): disable line breaks in sh.status chunks MONGOSH-802

- packages/cli-repl/src/cli-repl.spec.ts
- packages/cli-repl/src/config-directory.spec.ts
- packages/cli-repl/src/config-directory.ts
- packages/cli-repl/test/e2e.spec.ts
EJSON comes with support for values like `Infinity`, unlike
plain JSON.
> fix(cli-repl): store config using EJSON MONGOSH-850

- packages/build/src/barque.spec.ts
- packages/build/src/barque.ts
- packages/build/test/fixtures/bin/curator
For any given package, we upload it to multiple PPAs
(5.0/4.4, enterprise/org, and possibly also for multiple distros).
In order to save time during publishing, run those tasks in parallel
rather than sequentially.
> chore(build): run curator tasks for a pkg in parallel

- packages/shell-api/src/collection.ts
- packages/shell-api/src/integration.spec.ts
Allow passing options through to the driver for `coll.find()`
and `coll.findOne()`.
> feat(shell-api): allow options in find() and findOne() MONGOSH-857

- packages/shell-api/src/shell-bson.spec.ts
- packages/shell-api/src/shell-bson.ts
Since for the types that the BSON library itself provides, the
only benefit of our wrappers is the extra type validation,
we should ensure that it is accurate.
> fix(shell-api): relax BSON type validation MONGOSH-865

- packages/cli-repl/src/arg-mapper.spec.ts
- packages/cli-repl/src/arg-mapper.ts
- packages/cli-repl/src/arg-parser.spec.ts
- packages/cli-repl/src/arg-parser.ts
- packages/cli-repl/src/constants.ts
- packages/i18n/src/locales/en_US.ts
- packages/service-provider-core/src/cli-options.ts
- packages/service-provider-core/src/uri-generator.spec.ts
- packages/service-provider-core/src/uri-generator.ts
Adds support for handling:
* `--gssapiServiceName`
* `--sspiHostnameCanonicalization=none|forward`
* `--sspiRealmOverride`
* throws an error when `gssapiServiceName` is used as a query parameter
`gssapiServiceName` and `sspiRealmOverride` will only work properly when a new driver version is available.
> chore: support Kerberos-specific CLI arguments MONGOSH-838

- .evergreen.yml
- .evergreen/.setup_env
- packages/cli-repl/src/smoke-tests-fle.ts
The platform support matrix for the 5.0 server now indicates that
RHEL 8 will be supported in addition to, not instead of, RHEL 7
on the zSeries/s390x platform.
This is the optimistic approach, where we build the same executable
for both targets. If this fails in CI, we may need to start
building separate binaries.
> chore(ci): test s390x builds on RHEL 8.0 MONGOSH-768

- packages/build/src/github-repo.spec.ts
- packages/build/src/github-repo.ts
- packages/build/src/homebrew/publish-to-homebrew.spec.ts
- packages/build/src/homebrew/publish-to-homebrew.ts
- packages/build/src/homebrew/update-homebrew-fork.spec.ts
- packages/build/src/homebrew/update-homebrew-fork.ts
- packages/build/src/run-publish.spec.ts
- packages/build/src/run-publish.ts
This should fix the issue observed in https://github.com/Homebrew/homebrew-core/pull/80462. I've also replaced the release URL with a ordinary string template as it turned out to be rendered very awkwardly in the PRs...
> fix(build): use latest upstream master for Homebrew PR MONGOSH-874

- packages/browser-repl/src/components/utils/inspect.ts
- packages/cli-repl/test/e2e-bson.spec.ts
- packages/service-provider-core/src/printable-bson.spec.ts
- packages/service-provider-core/src/printable-bson.ts
`DBRef` object id values can be anything (just as the `_id` field
of a document can be anything), so we should not act as if it
is always an `ObjectId`, and in particular, we should print it out
in a way that allows for re-evaluation.
> fix(service-provider-core): print DBRef properly MONGOSH-875

- packages/cli-repl/test/e2e-auth.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/shell-internal-state.ts
Reset the current cursor on:
- Assignment to `db`
- `db.auth()`
- `db.logout()`
> feat(shell-api): reset current cursor when db changes or auths MONGOSH-13

- packages/shell-api/src/change-stream-cursor.spec.ts
- packages/shell-api/src/collection.spec.ts
- packages/shell-api/src/collection.ts
- packages/shell-api/src/database.spec.ts
- packages/shell-api/src/database.ts
- packages/shell-api/src/mongo.spec.ts
- packages/shell-api/src/mongo.ts
Call `.tryNext()` on each change stream cursor after its creation,
in order to initialize the cursor on the driver side and make it
start listening for events immediately.
> fix(shell-api): call tryNext on new change stream cursors MONGOSH-889

- packages/service-provider-server/src/mongodb-patches.ts
- packages/shell-api/src/change-stream-cursor.spec.ts
MONGOSH-888
When a user interrupts running code while a change stream `.next()`
call is running, that closes the network connection. However,
network errors are considered retryable by the driver (in line
with the spec); this makes the change stream cursor `.next()`
operation attempt to re-try itself, which fails because the
MongoClient is already unusable at that point.
In order to address this, we call the driver-internal
`Connection.handleIssue()` method (which should be okay, since the
relevant code here is concerned only with driver internals anyway)
with a non-network-error state, which still closes ongoing operations.
> fix(service-provider-server): fix change stream .next() interrupt 

- packages/async-rewriter2/src/async-writer-babel.spec.ts
- packages/async-rewriter2/src/stages/wrap-as-iife.ts
- Fix dumb bug where I forgot to check whether the program
actually contains a body before assuming that the presence of
a single directive would indicate that the program consisted
only of that
- Make sure that 'use strict' actually gets propagated into
the transpiled result
> fix(async-rewriter2): fix 'use strict' handling MONGOSH-890

- scripts/docker/ubuntu18.04-xvfb.Dockerfile
- testing/test-vscode.sh
Account for the fact that some things apparently don’t work with the
git version of the driver.
> fix(ci): fix vscode integration test

- packages/build/src/packaging/download-mongocryptd.ts
We need to use the mongocryptd from RHEL for s390x/ppc64le
because that is the only platform where these architectures
are supported by the 5.x server.
> fix(build): use RHEL for s390x/ppc64le mongocryptd MONGOSH-897

- packages/cli-repl/src/format-output.ts
- packages/cli-repl/src/mongosh-repl.spec.ts
- packages/cli-repl/src/mongosh-repl.ts
Instead of returning the ShellResult interpretation of the evaluation
result back to the Node.js REPL, return the original raw value and
keep the ShellResult stored separately (which still needs to happen
during `eval`, as the formatting itself is a synchronous operation).
This ensures that `_` will always refer to the actual value of the
last evaluation result.
> fix(cli-repl): return original evaluation value to REPL MONGOSH-902
